### PR TITLE
Preview info - Product

### PR DESCRIPTION
**Pull request by torvista**
Fixes bug (white screen) introduced in last PR to this file

https://github.com/zencart/zencart/commit/30f9bfc9ee3940556a8eebf99328c5a9c457d862#diff-2d0663a226d3074aec93b3f41745b5cd

and other minor changes...PRs to similar files affected by this bug to follow.

### CODE REVIEW

**Comment by torvista** [comment]
So, these are identical:
/document_product/preview_info.php
/product/preview_info.php
/product_free_shipping/preview_info.php
/product_music/preview_info.php

and this almost:
/document_general/preview_info.php

Is this redundancy-removal planned?

**Comment by drbyte** [comment]
First, thanks for the bugfixes.

I want to comment on the rest, as I see a growing trend here lately which is contrary to our usual workflow ...

Bugfixes are one thing. And it's always preferable for those to be done independent of other changes in a PR. Otherwise it's really hard to identify the exact change when researching later.
While I appreciate that at least you've done those as separate commits, it would be preferred to keep bugfixes in their own PR, and leave other "code improvements" or "code reformatting" as separate PRs.

Question:
IMO a whole lot of the changes in here are completely unnecessary if you allow the loose comparisons.
I don't see why strictly-typed comparisons add any value in most of these cases. They just make the code more complicated. 
Q: Other than to satisfy an IDE is there a purpose behind the change?

**Comment by torvista** [comment]
I was under the impression that with each release php gets more "strict".
So, from a shop owner point of view, I should use the latest php with strict reporting to get an early warning on things that will subsequently become a problem/error.

I assumed the inspection warnings fall under that remit, early warnings that while not a problem now, will be at some point. Otherwise, why do they have inspections at all, if not to help/give pointers to  improve the code?

Also, in a similar vein to the much-loved html validator, when there are a mass of inspections/"errors" for minor non-issues like this: 
specialsold
it's much easier to spot the new ones I've added when it's like this:
Clipboard03specialsnew
Ideally a file would have none to begin with, and then every mistake would be easier to see.

Apart from the actual syntax error in this particular file (which was suprising to see uncaught by an IDE), there was another (post variable comparison as integer), which showed up after making all the strict comparisons. 

I don't think any of the files are going away any time soon,  so I thought the strict thing would be some measure of future-proofing. I didn't think it made the code any more complicated, just more correct/less open to errors and hence more secure.
Isn't that the end goal?

**Comment by barco57** [comment]
> the much-loved html validator

lol

**Comment by drbyte** [comment]
Can we simplify this to just the bugfix, and the clarification made to delineate the section on multiple languages?

**Comment by torvista** [comment]
I see that comparing files/commits in Github online is awful even when it's only formatting...but very easy to see the no-real-changes with Beyond Compare.
Anyway, simplified as requested.

**Comment by drbyte** [comment]
Thanks. This is good.  👍 

Are you willing to apply the same to the other product types?

**Comment by torvista** [comment]
...are there no plans to sort out the duplication instead?

**Comment by drbyte** [comment]
> ...are there no plans to sort out the duplication instead?

No, the duplication is intentional, as each product-type is intended to be able to stand on its own.

I agree: frustrating. I hate it equally when doing upgrades and when merging the updates that plugins make. But the "right" solution is a more complex overhaul, which is separate from this PR. (Plus, I hate the "preview" step in the first place: I never "use" it, just sigh at it and click the next submit button.)

**Comment by torvista** [comment]
> I hate the "preview" step in the first place: I never "use" it, just sigh at it and click the next submit button.
I put autosubmit javascript in it, so I don't even have to click it.

**Comment by torvista** [comment]
that should be it

**Pull request merged**
