### PR TITLE
If comments are removed after being added, clear SESSION data

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
What's the scenario that this is fixing?

**Comment by scottcwilson** [comment]
Repro steps: 
- on checkout shipping, enter comments, press continue. 
- on payment page, click checkout (for example, you realize the shipping you have chosen is too expensive) and go back to checkout.
- now you're back on the checkout shipping page.  change your shipping method. 
- decide you don't want the comments after all, and remove them from the checkout shipping page.
- click continue to go to payment.  Oops - comments are still there.

**Comment by drbyte** [comment]
Does the same problem exist with comments that get blanked out on checkout-payment page?

**Comment by scottcwilson** [comment]
No - if you remove comments on the payment page and submit, the confirmation page correctly shows no comments.

**Comment by drbyte** [comment]
How about instead of adding an `else` clause, why don't we just change things like this:

```diff
-    if (isset($_POST['comments'])) {
+    if (zen_not_null($_POST['comments'])) {
```

**Comment by scottcwilson** [comment]
I'm not following your suggestion.

**Comment by drbyte** [comment]
You did the following:

```diff
    if (zen_not_null($_POST['comments'])) {
       $_SESSION['comments'] = zen_output_string_protected($_POST['comments']);
+     } else {
+       $_SESSION['comments'] = ''; 
     }
```

I'd rather you did this instead:
```diff
-    if (zen_not_null($_POST['comments'])) {
+    if (isset($_POST['comments'])) {
       $_SESSION['comments'] = zen_output_string_protected($_POST['comments']);
     }
```

**Pull request merged**
