### PR TITLE
Fix copy attributes warnings

### PR DESCRIPTION
**Pull request by marco-pm**

### CODE REVIEW

**Comment by scottcwilson** [comment]
If you have copies of the warning logs, please paste them in here so people searching for this problem can find your solution.  Thanks!

**Comment by marco-pm** [comment]
> If you have copies of the warning logs, please paste them in here so people searching for this problem can find your solution. Thanks!

Sure:

```
Request URI: /admin/index.php?cmd=category_product_listing&action=update_attributes_copy_to_product&cPath=7&page=1
#0 /home/user/public_html/admin/category_product_listing.php(281): zen_debug_error_handler()
#1 /home/user/public_html/admin/index.php(11): require('/home/user/...')
--> PHP Warning: Undefined array key "products_id" in /home/user/public_html/admin/category_product_listing.php on line 281.
```

```
Request URI: /admin/index.php?cmd=category_product_listing&cPath=1_1_1&pID=10&action=attribute_features_copy_to_product&page=1&products_id=20
#0 /home/user/public_html/admin/category_product_listing.php(1133): zen_debug_error_handler()
#1 /home/user/public_html/admin/index.php(11): require('/home/user/...')
--> PHP Warning: Undefined array key "copy_attributes" in /home/user/public_html/admin/category_product_listing.php on line 1133.`
```

**Comment by lat9** [comment]
Under what condition did the 'copy_attributes' value not get set?  Did the product not have attributes?

**Comment by marco-pm** [comment]
> Under what condition did the 'copy_attributes' value not get set? Did the product not have attributes?

It's an hidden field of the form. The same form has another radio field with the same name `copy_attributes`.
I don't know why there is an hidden field with the same name and under what circumnstances it gets the value from `$_GET['copy_attributes']`, I wanted to remove it but maybe it's there for a reason.
If you have a product with attributes and click Copy Attributes to another product, you're getting a warning (PHP 8.1).

**Comment by torvista** [comment]
Strange, I use that regularly without issues on 8.1.4.  I don't get it when copying in a vanilla shop in 8.2.4 either.
You are talking about this action:
image

**Comment by marco-pm** [comment]
> Strange, I use that regularly without issues on 8.1.4. I don't get it when copying in a vanilla shop in 8.2.4 either. You are talking about this action: image

Nope, action `attribute_features_copy_to_product`. Click on the attributes button of a product with attributes, then on Copy To

**Comment by torvista** [comment]
Ah, never used those options, yes to debugs.

**Pull request merged**
