### PR TITLE
Redirect to home on bad URL

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes bad URL:
index.php?inc_subcat=0&keyword=1&main_page=advanced_search_result&page=7&search_in_description=1&sort[]=20a

Reported in 
https://www.zen-cart.com/showthread.php?228698-Error-logs-generated-from-Microsoft-IP

### CODE REVIEW

**Comment by lat9** [comment]
I'm wondering whether this should be moved to init_sanitize.php, performing that redirection if **_any_** of the $_GET variables are arrays ... there's nothing (at least in the core) that uses a $_GET array, is there?

**Comment by proseLA** [comment]
i agree with @lat9.

hard coding specific `$_GET` vars seems pretty....  i can't think of a specific word right now...

**Comment by scottcwilson** [comment]
I'd be happy to try this ... we'll have to do some testing to be sure nothing gets broken by it.

**Comment by torvista** [comment]
I've had this in place for a couple of weeks replacing an old change I made for the same reason, and have not detected anything not working (advanced shipper, ceon uri mapping in use).

**Comment by scottcwilson** [comment]
As soon as we find exceptions I'll add them to the list. :)

**Comment by torvista** [comment]
After trying various search permutations on **my** site, I did find this in the Advanced Shipper **admin**

$_POST = array_map('stripslashes_deep', $_POST);
$_GET = array_map('stripslashes_deep', $_GET);   
$_COOKIE = array_map('stripslashes_deep', $_COOKIE);   
$_REQUEST = array_map('stripslashes_deep', $_REQUEST);

which is it's own sanitation.
 but no other uses of GET related to an array.

**Comment by scottcwilson** [comment]
Yes, this is also my recollection.

**Comment by lat9** [comment]
One more (isn't there always?) teeny bit, how about adding a notification just prior to the redirect to enable a site-specific override, e.g.

```php
$site_array_override = false;
$zco_notifier->notify('NOTIFY_INIT_SANITIZE_GET_VAR_CHECK', ['getvarname' => $getvar], $site_array_override);
if ($site_array_override === false) {
   then do the redirect
}
```

**Pull request merged**
