### PR TITLE
Add template-specific settings support

### PR DESCRIPTION
**Pull request by drbyte**
This allows template-specific override capability.

### CODE REVIEW

**Review by lat9 — COMMENTED** [review]
It might be worth mentioning in the `template_settings.php` files' comments that database setting (i.e. constant definitions) cannot be overridden, only the soft settings.

**Comment by drbyte** [comment]
FYI - ZC load order:
- extra-datafiles before breakpoint 0
- db constants at breakpoint 40
- non-db constants at breakpoint 45
- functions files at breakpoint 60
- template-settings at breakpoint 110, followed by language-defines and extra_definitions

**Comment by drbyte** [comment]
For interoperability with the BS4 template, and to allow it to use the `template_settings.php` file on older ZC versions, since extra_definitions loads fairly soon after the core template_settings.php would get loaded, I'm pretty sure we can simply add the following to the `extra_definitions/zca_bootstrap_id.php` file, or a new file maybe named `zca_bootstrap_settings.php`:
```php
// For pre-v2.0.0 support, load the template_settings.php file if not yet loaded
if (!isset($tpl_settings['IS_ZCA_BOOTSTRAP_TEMPLATE'])) {
    require_once DIR_WS_TEMPLATE . 'template_settings.php';
}
```

Then later one could review whether the `extra_datafiles/site-specific-bootstrap-settings.php` needs to remain where it is or if its content could be relocated to `template_settings.php`. Load-order may be the primary determinant there.

**Comment by drbyte** [comment]
Documentation: https://docs.zen-cart.com/dev/code/template_settings/

**Pull request merged**
