### PR TITLE
Admin layout updates for Options Manager screens

### PR DESCRIPTION
**Pull request by Zen4All**
This is an update for the page layout. Giving it a more modern look.
There are no functional changes , only  things like "while" to "foreach", and removing obsolete/unused code

Related to #1511 

new_options_values

new_product_options

---
This change is [Reviewable](https://reviewable.io/reviews/zencart/zencart/1546)

### CODE REVIEW

**Comment by drbyte** [comment]
I like it!

Was there more you wanted to do with this?

**Comment by Zen4All** [comment]
These files are ready, but I have a whole bunch of other files.
Like configuration, modules, and many more that are based on the same layout.

**Comment by drbyte** [comment]
👍

**Comment by zcwilt** [comment]
:+1:

**Comment by ajeh** [comment]
:+1:

**Pull request merged**
