### PR TITLE
no redirect on error; change action and continue #3873

### PR DESCRIPTION
**Pull request by proseLA**

### CODE REVIEW

**Comment by drbyte** [comment]
Interesting - what's the use-case for changing `$action`?

**Comment by proseLA** [comment]
in the first commit, we established that by changing the action, we can preserve all of the post data, and still provide the error message without the need to reload the page via a redirect.  if we redirect the page as is, we would need to rebuild all of the post data which is currently lost the way ZC stands right now.

to get to a preview page we would normally have something like `$product->isValid()` returning true prior to doing a preview.

the second commit, allows us to do that validation through the notifier; if the validation fails, we can change the action again from the `new_product_preview` to `new_product`.

classic use case would be something like UPC or EAN numbers, which ideally need to be validated prior to saving into the database.  although there could be any number of additional fields that are required and would need to be validated.

**Comment by drbyte** [comment]
@proseLA eventually I'd like to remove the "preview" page altogether. 
Ideally validation would happen still on submit, but would come back to this same page if there were a problem, instead of using an intermediary preview page. I'm mentioning it just to encourage you to architect whatever you're working on to not expect the presence of a preview page.

**Comment by proseLA** [comment]
> @proseLA eventually I'd like to remove the "preview" page altogether.
> Ideally validation would happen still on submit, but would come back to this same page if there were a problem, instead of using an intermediary preview page. I'm mentioning it just to encourage you to architect whatever you're working on to not expect the presence of a preview page.

- appreciate the heads up
- i'm comfortable with whatever decision you make on this/direction you take.
- i'm confident that i will be able to work with whatever gets done.  

thanks again for the heads up.

**Pull request merged**
