### PR TITLE
Simplify admin tab name logic

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
In english, what's the new logic here?

**Comment by scottcwilson** [comment]
Remove the need to check TEXT_ADMIN_TAB_PREFIX before setting the title string.

**Comment by drbyte** [comment]
Okay.
What's the problem/symptom that this is solving from the end-user perspective?

**Comment by scottcwilson** [comment]
The issue is that if they switch to the second define of TEXT_ADMIN_TAB_PREFIX (which people with multiple stores would want), you'd need to add code because of the additional check I removed. with my update, you can use either define for TEXT_ADMIN_TAB_PREFIX with no additional changes.

**Comment by drbyte** [comment]
Okay, I found the old PR where the code you're removing was initially added:
https://github.com/zencart/zencart/pull/2061/files

**Pull request merged**
