### PR TITLE
zc_install - skip "Tips" info header if no errors or warnings

### LINKED ISSUE #6660: System check display in ZC installer when no problem detected
When installing ZC and no configuration problem has been found, hint about clicking on error message title is displayed although there is no error message. Would a message saying system check did not find any problem not be better?
Capture2024-08-16_035835

### PR DESCRIPTION
**Pull request by drbyte**
And add another check to allow the existing "Success" message to display when `configure.php` file is present but blank.

Fixes #6660

Screen Shot 2024-08-17 at 10 13 27 PM

### CODE REVIEW

**Comment by drbyte** [comment]
Testing note: I haven't tested this with an "old-style" configure.php file to be sure that the buttons for upgrading that file aren't messed up by this change.

**Comment by piloujp** [comment]
I still get the 'tips' message (same as before) with this PR. If I use browser's reload button, then I have the green success message.
It seems the first time the page is loaded, configure.php files are not yet there when the message is set.

**Comment by drbyte** [comment]
Oh. Are you starting from the point of having "no" configure.php files present? 
(And then zc_install is creating blank files, which it then later populates?)

**Comment by piloujp** [comment]
> Oh. Are you starting from the point of having "no" configure.php files present? (And then zc_install is creating blank files, which it then later populates?)

Yes, like a fresh new ZC install.

**Comment by drbyte** [comment]
I reworked some things to trigger the file-creation sooner. I think it's better now. Please try to break it! (Seriously!)

**Comment by piloujp** [comment]
> I reworked some things to trigger the file-creation sooner. I think it's better now. Please try to break it! (Seriously!)

Install works has intended, no more tips displayed. I got the green message stating there is no problem and all install went smoothly.
BUT, I got 4 DEBUG log files with same content:
```
[27-Aug-2024 23:59:36 Asia/Tokyo] PHP Warning:  Undefined variable $hasFatalErrors in D:\wamp\www\testcart\zc_install\includes\template\common\tpl_main_page.php on line 14
[27-Aug-2024 23:59:36 Asia/Tokyo] PHP Warning:  Undefined variable $hasWarnErrors in D:\wamp\www\testcart\zc_install\includes\template\common\tpl_main_page.php on line 14
[27-Aug-2024 23:59:36 Asia/Tokyo] PHP Warning:  Undefined variable $hasUpdatedConfigFile in D:\wamp\www\testcart\zc_install\includes\template\common\tpl_main_page.php on line 14
[27-Aug-2024 23:59:36 Asia/Tokyo] PHP Warning:  Undefined variable $hasSaneConfigFile in D:\wamp\www\testcart\zc_install\includes\template\common\tpl_main_page.php on line 14
[27-Aug-2024 23:59:36 Asia/Tokyo] PHP Warning:  Undefined variable $configFilePresent in D:\wamp\www\testcart\zc_install\includes\template\common\tpl_main_page.php on line 14
```

**Comment by drbyte** [comment]
Yes, I discovered the same. Fixed.

**Pull request merged**
