### PR TITLE
Configuration settings for non-transactional email

### LINKED ISSUE #3886: Feature: Newsletter specific SMTP credentials
Provide configuration fields to support the option of sending newsletters to a specific SMTP account, different from the main store SMTP.  

This configuration could point to Mailgun, SMTP2Go, Mandrill, etc.

### PR DESCRIPTION
**Pull request by scottcwilson**
Allows newsletters, product notifications, back in stock mail, abandoned cart mail, etc. to be sent from an SMTP server designed for bulk emailing (rather than your regular email server).  

Fixes #3886 as discussed with Chris.

### CODE REVIEW

**Comment by scottcwilson** [comment]
For documentation: 

How to test this with your SMTP email server.
- Modify NEWSLETTER_MODULES in Configuration > Email Settings so that the list includes `direct_email`.
- Go to Customers > Customers and find your account.   Press the email button and send yourself a test email.

This email will be delivered by the EMAIL_SMTPAUTH_MAIL_SERVER.

**Comment by scottcwilson** [comment]
Verified using SendGrid as an external SMTP server.

**Comment by torvista** [comment]
Once the upgrade script runs, these email templates  
newsletters,product_notification,back_in_stock_notification,recover_cart_sale
will be sent using the credentials in the new fields....but there are none.

Just to be failsafe, should not the script either 
copy the existing settings, 
or there be a check on sending for the account name being "YourEmailAccountNameHere" / empty, to fallback to the default email settings?

**Comment by scottcwilson** [comment]
> Once the upgrade script runs, these email templates ... will be sent using the credentials in the new fields....but there are none.

This is not correct.  See line 215 of  includes/functions/functions_email.php

**Comment by torvista** [comment]
Yes, I see it checks for content in NEWSLETTER_EMAIL_SMTPAUTH_MAIL_SERVER, which is an empty field by default.
Thanks.

**Pull request merged**
