### PR TITLE
Updating SQL syntax

### PR DESCRIPTION
**Pull request by scottcwilson**
In this sprit of #3169, this set of updates is limited to ensuring the following:
* SQL statements are in upper case
* The last entry in an array has a comma, and the closing bracket is on a new line
* File does not end with ?>
In addition, meaningless comments may be removed.

### CODE REVIEW

**Comment by Zen4All** [comment]
When updating these queries, why not remove the single quotes from integer values at the same time?

**Comment by drbyte** [comment]
> When updating these queries, why not remove the single quotes from integer values at the same time?

Yes, but be sure to ONLY do it for values that are clearly cast as integers. 
(eg: Sometimes the products_id is a string, such as the customers_basket_attributes table, etc.)

**Comment by scottcwilson** [comment]
This is a lot more work and a lot more chance of error.  Are you SURE we want to do this?

**Comment by drbyte** [comment]
hmmm

**Pull request merged**
