### PR TITLE
Update to option name manager

### PR DESCRIPTION
**Pull request by Zen4All**
- html layout update
- type casting

### CODE REVIEW

**Comment by lankeeyankee** [comment]
I get this undefined constant TEXT_DISPLAY_NUMBER_OF_OPTIONS on line 574

**Comment by Zen4All** [comment]
@lankeeyankee Thanks, yes that defines need to to added. Will do shortly

**Comment by Zen4All** [comment]
> Lines 688 -689, change class="text-right" to class="text-center" to match the class of the headings and keep it all aligned.

Did it a bit different, because IMO integers should align to the right

**Comment by lankeeyankee** [comment]
Looks great. The only other thing I thought it needed from a personal preference was hardcoding padding-bottom:5px to the div on line 567 so the display links wasn't sitting right on top of the table.

**Comment by drbyte** [comment]
Is this ready for merge? Or are you still sorting out some things?

**Comment by Zen4All** [comment]
I'll do a review today, and make changes if necessary. Should be ready tonight (UTC). 
When ready I will post here

**Comment by Zen4All** [comment]
@lankeeyankee 
> had the same issue with next id and 1.5.6c

fixed with https://github.com/zencart/zencart/pull/2954/commits/daf0c32d2e72a9b3fd32b3e4b0ef228a3f724443

**Comment by Zen4All** [comment]
@drbyte I am ready with this pr

**Pull request merged**
