### PR TITLE
EZPages display control for mobile

### PR DESCRIPTION
**Pull request by scottcwilson**
You may not want ezpages in your header bar in desktop view, but you still need them in
the hamburger menu.

### CODE REVIEW

**Comment by scottcwilson** [comment]
This newly created file `includes/modules/responsive_classic/ezpages_bar_header.php` is identical to the core file `includes/modules/responsive_classic/ezpages_bar_header.php` except for line 18, which adds a check for mobile.

**Comment by dbltoe** [comment]
Works a charm but, I would put it in the
emplate_default or it could be lost shortly after installation.

**Comment by scottcwilson** [comment]
I'm not sure you can count on `$detect` being defined, which would be required if this were in template_default.

**Comment by scottcwilson** [comment]
@dbltoe Maybe you could build a help file specifically for responsive_classic that would point out issues like this?

**Comment by drbyte** [comment]
> @dbltoe Maybe you could build a help file specifically for responsive_classic that would point out issues like this?

No, let's not create docs specific to a template.

**Comment by drbyte** [comment]
> I'm not sure you can count on `$detect` being defined, which would be required if this were in template_default.

Perhaps `isset($detect) && $detect->...` would make it generic enough?

**Comment by scottcwilson** [comment]
Let's start with what's there, which is a valuable fix.  I'm not sure why @dbltoe thinks things will get overwritten and lost - that's the whole point of override folders is to prevent that.

**Comment by dbltoe** [comment]
Upon further review... Out of the Doctor's waiting lounge.
I can see where there is no need for a responsive file in the non-responsive template_default UNLESS we wanted to make sure this operation happened no matter what template the owner chooses.
And, since we have no idea if the chosen template will even use that type menu, I suppose a your_template would be out of the question as well.

**Comment by wiztechinc** [comment]
I figured out some unusual ways of doing this kind of thing with my template. I’m extremely interested in this possibility. Seems to me this can be handy for template developers?

**Comment by scottcwilson** [comment]
Go for it!  Thank you, Delia.   
John, this doesn't mean you're off the hook. :)

**Comment by scottcwilson** [comment]
Possibly useful pages to cross link: 

https://docs.zen-cart.com/user/template/mobile_mode/
https://docs.zen-cart.com/user/template/responsive/

**Comment by wiztechinc** [comment]
> Go for it! Thank you, Delia.
> John, this doesn't mean you're off the hook. :)

Well, as much as I like this idea, I have never used the responsive template so any documenation may be far in the future if I do it.

**Pull request merged**
