### PR TITLE
split page results correct count #4558

### PR DESCRIPTION
**Pull request by proseLA**
#4558 

i pulled out code that was not needed; and left in code that was used for `$this->paginateByLetter` which is only used in countries and seems to work fine.

this solution makes use of a mysql CTE in case anyone is curious.

### CODE REVIEW

**Comment by proseLA** [comment]
i have now fixed the paginate by letter to at least display results that seem reasonable.

this does **not** change any of the pagination by letter logic.  it only displays accurate information when calling the `display_count` method

**Comment by scottcwilson** [comment]
Is this ready to merge?  If so would you please squash?

**Comment by proseLA** [comment]
squashed...

**Comment by scottcwilson** [comment]
I'd rather not change these files: 
```
admin/downloads_manager.php
admin/ezpages.php
admin/gv_sent.php
admin/paypal.php
```
Those extra fields are sometimes used by plugins and mods. 

I am nervous about this change:
`admin/includes/languages/lang.english.php`

I think seeing "Displaying <start> to <end> of <count>" can be very useful to let you know where you are.

**Comment by proseLA** [comment]
> I'd rather not change these files:
> 
> ```
> admin/downloads_manager.php
> admin/ezpages.php
> admin/gv_sent.php
> admin/paypal.php
> ```
> 
> Those extra fields are sometimes used by plugins and mods.

what extra fields might you be talking about?

`gv_sent` has `c.coupon_id` in there twice.  all i did on that file was remove the extra instance of that field.  the same goes for `paypal` and the field `p.mc_currency`.  even if this PR does not get merged, those 2 scripts should be changed.

the only field missing from `ezpages` is the `languages_id` which the sql selects based on the `$_SESSION['languages_id']`.  i am not sure why a developer would need that field.  but that field could be easily added back.

with regards to the `downloads_manager`, i would be interested to see what plugin or mod uses that script.  and if they are modifying the script, they can very easily change the sql for any fields that they may need.  but in this instance, you are correct: there are fields missing.  i only accounted for the fields used by this script, which is a SQL best practices.

> I am nervous about this change: `admin/includes/languages/lang.english.php`
> 
> I think seeing "Displaying to of " can be very useful to let you know where you are.

with regards to your nerves, lets see what is currently displayed when one clicks on `S` in countries:

image

now lets see that same display with this PR in place:

image

the information is much more accurate.  actually the information is correct.

i was not a fan of this pagination by letter when chris implemented it, although i can see how some people would be.  BUT, this pagination by letter NEVER had the code in there to provide pagination within a specific letter. ie, 2 pages for countries that start with the letter S.

the current pagination class does not work.  and the code is rather difficult to decifer.

this class is much easier to understand and provides accurate results.

**Comment by torvista** [comment]
Regarding Countries, as far as I can see, each letter shows **all** the countries with that letter, so there are no pages (plural) for any single letter, which for this almost permanent/unchanging list where 31 is the max, I think is the best solution.
The second example tells you how may countries have that letter, and the total countries. There's no more information necessary/possible.

**Comment by scottcwilson** [comment]
> what extra fields might you be talking about?

Each of those files has changes to the SELECT statements.  You are right about gv_sent and paypal.  I'll have to look at ezpages and downloads manager.   But why are they in this PR?  They are not related to pagination.

**Comment by scottcwilson** [comment]
To be very clear: please create new PRs for the corrections you are making to the files

```
admin/downloads_manager.php
admin/ezpages.php
admin/gv_sent.php
admin/paypal.php
```
and remove them from this PR.  They are not related to pagination, they are corrections (at least for the last two, I need to review the others still).  They should be in their own PRs.

**Comment by proseLA** [comment]
> To be very clear: please create new PRs for the corrections you are making to the files
> 
> ```
> admin/downloads_manager.php
> admin/ezpages.php
> admin/gv_sent.php
> admin/paypal.php
> ```
> 
> and remove them from this PR. They are not related to pagination, they are corrections (at least for the last two, I need to review the others still). They should be in their own PRs.

i would suggest you review #4558.  the new split page results exposes the problem with the mysql queries as merging the class without the changes to the mysql select statements results in fatal errors.  they are related.

**Comment by scottcwilson** [comment]
I am going to merge these changes I just want them in a separate PR because it's really confusing to view them in the context of this one.  Each one is a small simple change that should be quick to merge.

**Comment by proseLA** [comment]
creating 2 new PRs.  quicker for me than getting into some git debacle.

**Pull request closed without merging**
