### PR TITLE
Factor out common entries to avoid already defined notices

### LINKED ISSUE #3771: Modules > Payment page creating logfiles
[20-Jul-2020 12:01:19 UTC] PHP Notice:  Constant MODULE_PAYMENT_PAYPAL_ENTRY_ADDRESS_NAME already defined in /Users/scott/Sites/gh_demo_158/includes/languages/english/modules/payment/paypaldp.php on line 95
[20-Jul-2020 12:01:19 UTC] PHP Stack trace:
[20-Jul-2020 12:01:19 UTC] PHP   1. {main}() /Users/scott/Sites/gh_demo_158/admin/index.php:0
[20-Jul-2020 12:01:19 UTC] PHP   2. require_once() /Users/scott/Sites/gh_demo_158/admin/index.php:11
[20-Jul-2020 12:01:19 UTC] PHP   3. Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles() /Users/scott/Sites/gh_demo_158/admin/modules.php:185
[20-Jul-2020 12:01:19 UTC] PHP   4. Zencart\LanguageLoader\AdminFilesLanguageLoader->loadExtraLanguageFiles() /Users/scott/Sites/gh_demo_158/includes/classes/ResourceLoaders/LanguageLoader.php:57
[20-Jul-2020 12:01:19 UTC] PHP   5. Zencart\LanguageLoader\AdminFilesLanguageLoader->loadFileDefineFile() /Users/scott/Sites/gh_demo_158/includes/classes/ResourceLoaders/FilesLanguageLoader.php:20
[20-Jul-2020 12:01:19 UTC] PHP   6. include_once() /Users/scott/Sites/gh_demo_158/includes/classes/ResourceLoaders/FilesLanguageLoader.php:37
[20-Jul-2020 12:01:19 UTC] PHP   7. define() /Users/scott/Sites/gh_demo_158/includes/languages/english/modules/payment/paypaldp.php:95

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #3771.

### CODE REVIEW

**Comment by mc12345678** [comment]
Wouldn't putting this through the language define-to-array "converter" address this issue or has something changed about that feature?

**Comment by zcwilt** [comment]
@mc12345678 

While code exists to use arrays catalog side, we haven't yet converted any language files to the new array structure.

I guess the question is do we go ahead and do this for v158.

**Comment by scottcwilson** [comment]
The alternative would be to do `if (!defined('PAYPAL_value')) define('PAYPAL_value','value'); `

**Comment by drbyte** [comment]
> The alternative would be to do `if (!defined('PAYPAL_value')) define('PAYPAL_value','value');`

Given the interoperability of these modules and their files, I think the if-not-defined prefixing is best at this current stage, at least for the defines that they share in common. This also allows for easier backporting of the files to older versions.

**Comment by scottcwilson** [comment]
Superceded by #3857

**Pull request closed without merging**
