### PR TITLE
Weekly sales reports display months by months

### PR DESCRIPTION
**Pull request by piloujp**
Fixes issue #6600

### CODE REVIEW

**Comment by scottcwilson** [comment]
It goes back by groups of 5 weeks at a time.  What's there now looks fine to me, I don't think it makes sense to change.

**Comment by piloujp** [comment]
I think these weekly reports are made to be viewed one month of data at a time with week by week details like on a table calendar going from Sunday to Saturday for columns and first week of the month on first line and last line with last week.
Which means between 4 (rarely) and 6 lines per month.
That said, try this:
Click four times on Previous:  You should have five weeks per page each time, as you said.
Then click on Next until you are back to last data of this month:  I get an alternance of three and four lines pages and need to click six times.
Then, if I click on Previous again, at second time I get a nine lines page!

**Comment by scottcwilson** [comment]
If you want to change it, please make it jump back (and forward) by groups of 5 weeks.  It doesn't need to be month by month, people are looking for weekly numbers, not monthly.

**Comment by piloujp** [comment]
Why 5 weeks then? There is more room on the page.
Plus:
Hourly reports --> 1 day
Daily reports --> 1 week
Weekly reports --> 5 weeks ???
Monthly reports --> 1 year of data

Sorry to insist like that, but before I do something I like to understand why.

**Comment by scottcwilson** [comment]
Pick a number 5,6,8. Enough to give context.  You're trying to see your weekly performance.

**Comment by scottcwilson** [comment]
I appreciate the work you have done on this but it seems like any change we make is going to make someone (who's used to the old format) unhappy.  I think we should put this to bed.

**Pull request closed without merging**
