### PR TITLE
Added 7 new spider terms and  Added 9 consolidator terms and cleanup

### PR DESCRIPTION
**Pull request by Shrimp-Gumbo**
Added terms
alibaba
aliapp
cf-uc   (googlecontent)
frd-a100
headless   (chrome)
liebaofast
oppo

Added Consolidator terms
robo
fetch
search
link
seek
grab
browse
index
walk
libwww

Removed terms that would be caught by above consolidators

### CODE REVIEW

**Comment by drbyte** [comment]
Thanks for this update.

I'm undecided about whether all these consolidators are best. I'm a bit concerned that they'll fire false positives by being slightly too generic.

**Comment by drbyte** [comment]
I think `browse` and `index` shouldn't be consolidated. Others are probably fine.
Also, why was `blank` removed?

**Comment by Shrimp-Gumbo** [comment]
well blank was one I put it there.... without coding to create a "blank" one it really isn't doing anything....was something added to create a "blank" spider?
Forgive my ignorance, are you telling me the above so I will change and republish?   
Thanks for what you do!
Michael
    On Monday, December 30, 2019, 10:29:55 AM CST, Chris Brown <notifications@github.com> wrote:  
 
 
I think browse and index shouldn't be consolidated. Others are probably fine.
Also, why was blank removed?

**Comment by drbyte** [comment]
Hi Michael,
Yes are you okay with doing a commit which undoes the consolidation of `browse` and `index`?

**Comment by Shrimp-Gumbo** [comment]
Sure, it might take a few weeks before I can look at it again though.... sorry, I am very busy.
    On Monday, December 30, 2019, 08:44:59 PM CST, Chris Brown <notifications@github.com> wrote:  
 
 
Hi Michael,
Yes are you okay with doing a commit which undoes the consolidation of browse and index?

**Comment by drbyte** [comment]
Ya, no rush.

**Comment by drbyte** [comment]
Hi Michael,
I've made the changes I mentioned, and also made `java` more generic, since it's becoming problematic too.
Thanks for your work on this. 👍

**Pull request merged**
