### PR TITLE
Storefront language file conversion

### PR DESCRIPTION
**Pull request by scottcwilson**
Storefront language file conversions.  There's more fine tuning to do but I want to get the first version in so people can look for issues. 

These files intentionally do not yet have Zen Cart headers for the first version.  Will review before release.

### CODE REVIEW

**Comment by torvista** [comment]
This was all I found

General navigation, lots of debugs with same error.

> --> PHP Warning: Undefined variable $current_page_base in \zencart\includes\languages\english\lang.credit_cards.php on line 18.

On submission of a create account form, white screen of death.

> [11-Jan-2022 22:38:39 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "EMAIL_GV_CLOSURE" in \zencart\includes\modules\create_account.php:364

Select a record company or genre from sidebox, white screen of death

> [11-Jan-2022 22:44:03 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "TEXT_ATTRIBUTES_QTY_PRICE_HELP_LINK" in D:\GitHub\zencart\includes\languages\english\lang.product_music_info.php:21

Click on Search box, white screen of death

> [11-Jan-2022 22:45:33 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "HEADING_TITLE" in D:\GitHub\zencart\includes\modules\meta_tags.php:56

**Comment by scottcwilson** [comment]
Thanks for finding these.  I believe I have fixed most of them but I couldn't dup the search issue. I'm sure there will be other findings as we get some miles on these changes.

**Comment by scottcwilson** [comment]
> On submission of a create account form, white screen of death.

Good news - errors of this flavor (of which there are a bunch from the initial run of the converter) can be easily tracked down using `grep`.  I have added details to the documentation.

**Comment by lat9** [comment]
@torvista, do these changes satisfy your initial findings?

**Comment by torvista** [comment]
I don't find any problems now in storefront pages including logged in account pages.

**Pull request merged**
