### PR TITLE
Storefront image functions, alt-attribute changes

### LINKED ISSUE #5494: `zen_image`, remove 'role="presentation"' since it's now causing HTML validation errors
image

### PR DESCRIPTION
**Pull request by lat9**
Fixes #5494

### CODE REVIEW

**Comment by lat9** [comment]
Well crapola.  That change now results in various PHP warnings on the `downloads` page:
```
[15-Feb-2023 14:52:13 America/New_York] Request URI: /zc158/index.php?main_page=download&order=40&id=3, IP address: 127.0.0.1, Language id 1
#1  zen_image_OLD() called at [C:\xampp\htdocs\zc158\includes\functions\html_output.php:196]
#2  zen_image() called at [C:\xampp\htdocs\zc158\includes\languages\lang.english.php:524]
#3  require(C:\xampp\htdocs\zc158\includes\languages\lang.english.php) called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\ArraysLanguageLoader.php:143]
#4  Zencart\LanguageLoader\ArraysLanguageLoader->loadArrayDefineFile() called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\ArraysLanguageLoader.php:121]
#5  Zencart\LanguageLoader\ArraysLanguageLoader->loadDefinesWithFallback() called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\CatalogArraysLanguageLoader.php:65]
#6  Zencart\LanguageLoader\CatalogArraysLanguageLoader->loadMainLanguageFiles() called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\CatalogArraysLanguageLoader.php:18]
#7  Zencart\LanguageLoader\CatalogArraysLanguageLoader->loadInitialLanguageDefines() called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\LanguageLoader.php:28]
#8  Zencart\LanguageLoader\LanguageLoader->loadInitialLanguageDefines() called at [C:\xampp\htdocs\zc158\includes\init_includes\init_templates.php:87]
#9  require_once(C:\xampp\htdocs\zc158\includes\init_includes\init_templates.php) called at [C:\xampp\htdocs\zc158\includes\autoload_func.php:40]
#10 require(C:\xampp\htdocs\zc158\includes\autoload_func.php) called at [C:\xampp\htdocs\zc158\includes\application_top.php:237]
#11 require(C:\xampp\htdocs\zc158\includes\application_top.php) called at [C:\xampp\htdocs\zc158\index.php:25]
--> PHP Warning: Use of undefined constant IMAGE_ALT_PREFIX - assumed 'IMAGE_ALT_PREFIX' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\zc158\includes\functions\html_output.php on line 146.

[15-Feb-2023 14:52:13 America/New_York] Request URI: /zc158/index.php?main_page=download&order=40&id=3, IP address: 127.0.0.1, Language id 1
#1  zen_image_OLD() called at [C:\xampp\htdocs\zc158\includes\functions\html_output.php:196]
#2  zen_image() called at [C:\xampp\htdocs\zc158\includes\languages\english\lang.credit_cards.php:18]
#3  require(C:\xampp\htdocs\zc158\includes\languages\english\lang.credit_cards.php) called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\ArraysLanguageLoader.php:143]
#4  Zencart\LanguageLoader\ArraysLanguageLoader->loadArrayDefineFile() called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\ArraysLanguageLoader.php:121]
#5  Zencart\LanguageLoader\ArraysLanguageLoader->loadDefinesWithFallback() called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\ArraysLanguageLoader.php:86]
#6  Zencart\LanguageLoader\ArraysLanguageLoader->loadDefinesFromArrayFile() called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\ArraysLanguageLoader.php:74]
#7  Zencart\LanguageLoader\ArraysLanguageLoader->loadExtraLanguageFiles() called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\CatalogArraysLanguageLoader.php:75]
#8  Zencart\LanguageLoader\CatalogArraysLanguageLoader->loadMainLanguageFiles() called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\CatalogArraysLanguageLoader.php:18]
#9  Zencart\LanguageLoader\CatalogArraysLanguageLoader->loadInitialLanguageDefines() called at [C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\LanguageLoader.php:28]
#10 Zencart\LanguageLoader\LanguageLoader->loadInitialLanguageDefines() called at [C:\xampp\htdocs\zc158\includes\init_includes\init_templates.php:87]
#11 require_once(C:\xampp\htdocs\zc158\includes\init_includes\init_templates.php) called at [C:\xampp\htdocs\zc158\includes\autoload_func.php:40]
#12 require(C:\xampp\htdocs\zc158\includes\autoload_func.php) called at [C:\xampp\htdocs\zc158\includes\application_top.php:237]
#13 require(C:\xampp\htdocs\zc158\includes\application_top.php) called at [C:\xampp\htdocs\zc158\index.php:25]
--> PHP Warning: Use of undefined constant IMAGE_ALT_TEXT_NO_TITLE - assumed 'IMAGE_ALT_TEXT_NO_TITLE' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\zc158\includes\functions\html_output.php on line 143.
```

**Comment by dbltoe** [comment]
I will throw it on a site this afternoon.

Meanwhile, if we are using the product's title as the alt, do we even need a prefix?   "img of" might be more appropriate at times instead of "img for".  I would think the title is sufficient.

**Comment by lat9** [comment]
> I will throw it on a site this afternoon.
> 
> Meanwhile, if we are using the product's title as the alt, do we even need a prefix? "img of" might be more appropriate at times instead of "img for". I would think the title is sufficient.

Don't do that until I've got this mess worked out.  Noting that it's also happening for lang.credit_cards.php and /extra_definitions/lang.product_free_shipping.php

**Comment by dbltoe** [comment]
_Should_ be different is the ADA/WCAG stance.  Not in any standard as required.  But, does make logical sense to be different.

If you can work your magic to do both different, we will be that much more gooderer.

**Comment by lat9** [comment]
OK, that should be "good to go".

**Pull request merged**
