### PR TITLE
Add missing comment blocks

### LINKED ISSUE #5066: includes\classes\productPulldown.php has no id info/comments

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #5066

### CODE REVIEW

**Comment by proseLA** [comment]
i put a lot of work into these pulldowns.  i would appreciate seeing it accredited appropriately.

**Comment by zcwilt** [comment]
So this is a difficult outcome to achieve.
@scottcwilson could go in and touch the files to add you as author.
However when it comes to tagging the branch for release and running the version stamper, as he was the last person to touch the file, version stamper would update the author back to Scott.

To temporarily overcome this you would have to touch the file, maybe by updating the author yourself.

However, there's then nothing to stop someone in the future from updating he file for whatever reason, again removing you as author.

**Comment by proseLA** [comment]
i do not want to make a big thing about this.  i have tried to understand the version stamper in the past.  and i understand that the stamper will accredit the last person who touched the file.  and just so i understand what happened here, the stamper did not hit these files.  which to me is a bug in the stamper.  

scott wilson then did a PR and manually inserting the header block for these files.  (it seems that he did not enter `* Class productPulldown` in the header for that file).  as a way of making it easier for himself he just used his name for all 5 files.  and since he was the last person to touch the files, when the next release comes out and tagged, his name will be on it as he was the last person to touch the files.

do i have that correct?

the question to me is why did the stamper skip these files in this tagged release?  they were tagged for an alpha release.  and the stamper did seem to hit the other files.  

i see no need to create a PR just so my name gets put in the header.

**Comment by zcwilt** [comment]
I may move this conversation into an issue as I personally don't understand why we have the version stamper,
and given I wrote the versions stamper code !!!!!!

I have been told that some people use the version stamper headers to better diff code between versions when doing updates.
 
 I know others think that the version stamper adds to much in the way of commits between versions. 
 
 Personally if I'm looking to see contributions, I can use git blame or github history and https://github.com/zencart/zencart/graphs/contributors
 
 note: on why it missed, is that the stamper only looks to see if certain lines exist in the header and then wheter it needs to update them.
 
 If the lines don't exist in the first place it won't add the line.

**Comment by scottcwilson** [comment]
> when the next release comes out and tagged, his name will be on it as he was the last person to touch the files.

You are correct. 

> the question to me is why did the stamper skip these files in this tagged release? 

Like I said, it needs that stub at the top of the file to have something to update. 
Not going to argue that this is the world's greatest system, but it is what it is. 

I will update them to show your name.  No disrespect was intended, I was just trying to get things fixed.

**Comment by proseLA** [comment]
> > when the next release comes out and tagged, his name will be on it as he was the last person to touch the files.
> 
> You are correct.
> 
> > the question to me is why did the stamper skip these files in this tagged release?
> 
> Like I said, it needs that stub at the top of the file to have something to update. Not going to argue that this is the world's greatest system, but it is what it is.
> 
> I will update them to show your name. No disrespect was intended, I was just trying to get things fixed.

update is not necessary.  and after looking at it, i never thought any disrespect was intended.

some times, people just want to get things fixed and move on.  i get that.

so lets not spend another moment on this.  i'm good with it all.

**Comment by scottcwilson** [comment]
> I may move this conversation into an issue as I personally don't understand why we have the version stamper, and given I wrote the versions stamper code !!!!!!

LOL I cannot tell you how often I have had this feeling over the years.
"Who was the bonehead who ... oh, it was me."

**Comment by zcwilt** [comment]
bonehead is my middle name

**Comment by scottcwilson** [comment]
@proseLA  Remember too that the name used by the stamper is ephemeral, but `git log` is forever. :)

**Pull request merged**
