### PR TITLE
Code reformatting

### PR DESCRIPTION
**Pull request by scottcwilson**
This is such a nice practice -let's use it everywhere.

### CODE REVIEW

**Comment by proseLA** [comment]
1. why do you feel this is a “nice” practice.  it seems there are arguments are both sides.
2. if this is going to be the new practice, lets all agree to it and then add it to the developer docs.
3. we already have tons of legacy coding standards.  2 spaces for legacy scripts, PSR-2 for new ones going forward.  if we want to make it a new standard, lets do it going forward.  if there are no other differences in the code, lets leave well enough alone.
4. as someone who maintains a few live ZC carts, this is the sort of change that infuriates me whenever I do an update.  there is no FUNCTIONAL difference in the code, and yet it is something that I have to look at using diff because someone decided this is a better practice.  I am reminded of times when someone decided that parts of the sql statement should be in caps and other parts not in caps.  make a standard going forward.  and lets not touch legacy code for the sake of the standard.
5. PLEASE, PLEASE, PLEASE, lets NOT make innocuous changes to legacy code just because it is “nice”.  lets agree on a policy going forward for coding standards, and not make these changes just for the sake of making a change.

**Comment by scottcwilson** [comment]
Look carefully at the 1.5.6 code for  this file.  It is done everywhere except in this one place.

**Comment by scottcwilson** [comment]
The rationale behind doing this is that if you have to add items to the array, the last entry doesn't have to change (with a new ",").

**Comment by wiztechinc** [comment]
If I understand what you are talking about, I truly prefer this way instead of without the comma. But then again, I'm no longer creating or maintaining mods anymore for others (just for me now). I might feel differently otherwise.

**Comment by drbyte** [comment]
While "yes", this "keep a trailing comma after the last array entry, when entries span multiple lines" is preferable, and is even the PSR standard, I also agree that generally we ought to avoid creating unnecessary upgrade pain wherever possible.
(I'm aware of the irony that making this specific sort of change actually directly reduces upgrade pain once it's been done.)

So, yes, it should be in the coding standards (it is insomuch as PSR applies)

But ... let's **not** go looking for files to apply this format to.

**Comment by proseLA** [comment]
i will say one last thing (in order to clarify my point) and then move on.  i stand by what drB says...

with regards to the specific changes in this PR, there is no functional difference so i am inherently against that.

HOWEVER, between the current released version of ZC (v156c) and the new v157 version prior to this PR, it looks like there are changes already made to this file.  which necessitates someone already reviewing the file when doing an upgrade.  so i am not so vehemently opposed to the changes.

nothing infuriates me more (ok that's an overstatement), when reviewing changes on a file for an upgrade, and the only thing different is the added comma to the end of the array, and a new stamp at the top of the code.

**Comment by drbyte** [comment]
Merging because we've already touched this file aggressively for the next release.

**Pull request merged**
