### PR TITLE
removes admin newsletters and product notifications #977

### PR DESCRIPTION
**Pull request by proseLA**
if we want to incorporate a 3rd party mailing list add-on; i think it should be part of a separate PR.

### CODE REVIEW

**Comment by drbyte** [comment]
Great!

I'd suggest also removing the `newsletters` table from the zc_install/sql/mysql_zencart.sql file.

And also this line from that same file, since it drives the admin menu option which you've removed from the language file:
`('newsletters', 'BOX_TOOLS_NEWSLETTER_MANAGER', 'FILENAME_NEWSLETTERS', '', 'tools', 'Y', 5),`

As for v160 upgrade SQL, it's probably best not to delete the `newsletters` table there, since we don't want to delete peoples' data.
But I think you could safely add something like these to remove the (now broken) menu option:
```sql
delete from admin_pages where page_key = 'newsletters';
delete from admin_pages_to_profiles where page_key = 'newsletters';
```

**Comment by proseLA** [comment]
ok... i think i got that...  best.

**Comment by proseLA** [comment]
interesting that on my local box, the removal of the menu option happened without the sql deletion.

**Comment by drbyte** [comment]
That's because it found no language defines to match. 
And might have even thrown errors recorded in the logs directory.

**Comment by proseLA** [comment]
interesting.  fyi, ZC did not throw any errors in the log directory.

i was getting errors from a missing table (countries_name); which i tracked down to the 'add files' commit.  which frankly took some time...  it seems that the commit message is more important than the branch name, as after a merge, we are left with the commit message.  and i'm not sure if others v160 test stores are getting the error, or they manually added the table as i did.

**Comment by drbyte** [comment]
> interesting. fyi, ZC did not throw any errors in the log directory.

Not surprising... We try to anticipate that so errors aren't logged. 
> i was getting errors from a missing table (countries_name); which i tracked down to the 'add files' commit. which frankly took some time... it seems that the commit message is more important than the branch name, as after a merge, we are left with the commit message. and i'm not sure if others v160 test stores are getting the error, or they manually added the table as i did
> 

Ya, the dev/alpha code won't always provide a clean update path including database schema changes. Those gave to be done manually; or just reinstall regularly. ;)

**Comment by drbyte** [comment]
👍

**Comment by zcwilt** [comment]
:+1:

**Pull request merged**
