### PR TITLE
Placing a Title into ... more info and call for price

### PR DESCRIPTION
**Pull request by dbltoe**
Actually, all the call for price text and buttons refer back to the buttons created for the ... more info text

These changes add a title component to the ... more info button link.

Without them, ADA/WCAG checks list the ... more info et al links as ambiguous.

### CODE REVIEW

**Comment by dbltoe** [comment]
Who the )R%(U#)$U put the - next to the =

All fixed but the two tpl_modules_products_all_listing.php

**Comment by dbltoe** [comment]
All checked though I did notice that you can't change the template to template default in the latest 1.5.8

**Comment by dbltoe** [comment]
Any idea why this closed without a merge?

**Comment by scottcwilson** [comment]
None, but I'll reopen it.  BTW each file doesn't have to be a commit - you can change multiple files in a single commit.

**Comment by scottcwilson** [comment]
@dbltoe Can you fix these merge conflicts?

**Comment by scottcwilson** [comment]
> All checked and fixed though I did notice that you can't change the template to template default in the latest 1.5.8

No change from 1.5.7 - set it to "Classic Contemporary Green."  Uses (almost exclusively) template default files.

**Comment by dbltoe** [comment]
Is there anything else I need to do on this?

**Comment by scottcwilson** [comment]
Yes you need to resolve these conflicts.

**Comment by dbltoe** [comment]
Well, I guess I have proven my ineptitude on GitHub once again.  The fork no longer exists on my GitHub and I have no idea what conflicts exist.
😬

**Comment by dbltoe** [comment]
Fixed with #5070

**Pull request closed without merging**
