### PR TITLE
admin activity: use php echo short tags and remove superfluous semicolons

### PR DESCRIPTION
**Pull request by torvista**
using both makes the code much clearer/cleaner

### CODE REVIEW

**Comment by proseLA** [comment]
i'm not sure on the semi-colons.  it seems that the PSR does not make a comment on it.  i'm used to the semi-colons; and one could convince me otherwise i suppose.

**Comment by torvista** [comment]
I'd never heard of dropping the semicolons before, but after reading these
https://stackoverflow.com/questions/52757180/are-semicolons-in-php-optional
https://github.com/prettier/plugin-php/issues/609

and bearing in mind the idea is to make clearer code, I think it has merit when combined with the sort tag and embedded in html.
An admin decision is required, as it would need to be documented in ZC code style.

**Comment by scottcwilson** [comment]
I'm not convinced this is better.  Please don't go on a tear making this change in a bunch of places.

**Comment by lat9** [comment]
> I'm not convinced this is better. Please don't go on a tear making this change in a bunch of places.

Neither am I.  I'm all for clearer/consise code, but recognize that there are a lot of do-it-yourself store owners for which this change will *not* be clearer!  I'm guessing that the use of exactly-equal-to (`===`) and the null-coalescing (`??`) operators might throw them for a loop, much less the short-echo (`<?=`) tags.

**Comment by torvista** [comment]
So, the consensus for now is, do not use short tags or drop semicolons?
Whatever is fine by me, as long as the decision is clear for all.

**Comment by scottcwilson** [comment]
Yes, please do not use short tags.

**Pull request closed without merging**
