### PR TITLE
Fix syntax error in language file

### LINKED ISSUE #3842: lang.developers_tool_kit, PHP warning
Seeing the following with the file-set downloaded this morning:
image

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #3842

### CODE REVIEW

**Comment by scottcwilson** [comment]
To test, go to Admin > Tools > Developer's Tool Kit.   Before the fix, you will see a log as noted by Cindy.  After the fix, no log.

**Comment by drbyte** [comment]
While the fix itself is correct, I'm leaving this for @zcwilt because it may indicate a need to update the converter script.

**Comment by drbyte** [comment]
Or maybe this doesn't need to mention the specific language at all ...... cuz the only option is the current language, which is self-evident because the UI is displaying in that same language.

**Comment by scottcwilson** [comment]
I agree but I was striving to preserve the designer's intent.  We'll see what Ian says.

**Comment by zcwilt** [comment]
I do have some updates to the script that generates the lang. files, but only in the sense that it will flag when it finds content
it can't understand. Haven't tested yet.

However on a general note, would prefer over time to remove stuff like this and rely more on sprintf for interjecting 
this type of content into language strings.

Apart from that have no problems with this pr for now.

**Pull request merged**
