### PR TITLE
Default to https URLs in installer

### LINKED ISSUE #3269: installer: SSL all site?
I note that while the installer is run from https: and "Enable SSL for storefront" is marked by default, it defaults to the storefront as http, which is what is used in HTTP_CATALOG_SERVER
Clipboard01
Is that still a valid default for 2020 when all sites should be https now?
I am aware of the use of HTTP_CATALOG_SERVER/HTTPS_CATALOG_SERVER and how the subsequent discussions of the settings required for SSL are confusing to users, due to legacy code.
But maybe its better to set it all https in the installer.

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #3269

Also preserves ability for people testing in a local environment to use http without having to edit URLs.

### CODE REVIEW

**Comment by drbyte** [comment]
> Also preserves ability for people testing in a local environment to use http without having to edit URLs.

Please explain further...

**Comment by scottcwilson** [comment]
I run this procedure in MAMP all the time.  Without this change I have to edit the URLs to remove the "s" in "https" so all my URLs are http.  (It's a localhost test - no SSL)

**Comment by drbyte** [comment]
You mean when you set ENABLE_SSL to false, you still have to change the HTTPS_SERVER etc URLs to be http?  
Why?

**Comment by scottcwilson** [comment]
because otherwise it would write the https URLs to the configure file, which wouldn't work in my localhost environment.

**Comment by drbyte** [comment]
That's not what I asked. And that's not how zc_install works.

When you uncheck the "Enable SSL?" box, it sets ENABLE_SSL to false for catalog and admin, and puts http:// where it should, and https:// where it should. It does NOT put https in wrong places in the configure file.

Then when you run catalog/admin, it honors the ENABLE_SSL to determine whether to use http or https.

Why is your environment not switching properly?

**Comment by torvista** [comment]
You can have SLL on a local environment, with your own certificate. I would have thought it to be essential for realistic testing. If I can do it, it can't be so difficult!

**Comment by scottcwilson** [comment]
> Why is your environment not switching properly?

let me do more testing.  this may have been fixed many moons ago.

**Comment by scottcwilson** [comment]
LOL so I have been wasting my time removing the "s" from "https" on this screen forever. 
OK.  Do you want me to tweak this PR to fix Steve's issue?

**Comment by drbyte** [comment]
> Do you want me to tweak this PR to fix Steve's issue?

I still don't understand Steve's issue.

**Pull request closed without merging**
