### PR TITLE
Allow ship/pay/ot modules to offer their own help

### PR DESCRIPTION
**Pull request by scottcwilson**
I did a couple of examples (coupons, PayPal Standard) in this PR to show how the result would look.  I can do the others once this PR is merged. 

Here is a screenshot of the dialog produced for the help in PayPal Standard:

module_help

### CODE REVIEW

**Comment by drbyte** [comment]
Please sell me on this.

It threatens to add a ton of additional maintenance, including a lot more language definitions to be translated.

**Comment by scottcwilson** [comment]
Language file additions are super minimal.  Mostly just links to the docs site.  This is really just an extension of the normal on page help, but done per module.  If you'd prefer, I can make it ONLY a link to the docs site, but I think more flexibility is a win.

**Comment by scottcwilson** [comment]
Just to be clear: We're not offering the help on the page in admin - it's a link to the help site.

**Comment by scottcwilson** [comment]
There are no language file updates for coupons; it uses the default text.  PayPal uses the default text plus one additional sentence.  Very minimal language additions - mostly pointers to the help site.

**Pull request merged**
