### PR TITLE
Remove page-parse-time-logging

### LINKED ISSUE #2686: Admin, Configuration, Logging: Log Destination path missing slashes
ZC157 fresh install. Xampp, windows, php 7.3.5
I notice most of the path slashes are missing:
Clipboard01

This will have been populated by the installer.
I suppose its a windows thing...
Needless to say enabling the logging generates a debug on every page load.

### LINKED ISSUE #2701: PHP notice. undefined variable logger: admin...application_bottom.php
ZC157, Report All Errors->enable ignoreDups for admin.
Admin-->Logging->Log Page Parse Time set to true.
Creates a debug log on every **admin** page load.

> PHP Notice:  Undefined variable: logger in ....\zencart-157\admin1\includes\application_bottom.php on line 16

### PR DESCRIPTION
**Pull request by drbyte**
Closes #2686
Closes #2701

### CODE REVIEW

**Comment by CeonSupport** [comment]
What plugin is replacing this?  I know I have found the information useful in reviewing code operations.

**Comment by scottcwilson** [comment]
Oh sorry, I thought this had been merged already.

**Comment by drbyte** [comment]
For catalog-side one can easily hook into the `NOTIFY_FOOTER_END` observer point and have it output the diff between `PAGE_PARSE_START_TIME` and subsequent `microtime()`.

**Comment by CeonSupport** [comment]
> For catalog-side one can easily hook into the `NOTIFY_FOOTER_END` observer point and have it output the diff between `PAGE_PARSE_START_TIME` and subsequent `microtime()`.

Actually it was the `$db->queryCount()` and `$db->queryTime()` that were of interest and removed by this commit (not just the `$parse_time` stated by the thread title).

**Comment by drbyte** [comment]
Fair. 
You can echo/log those values using an observer listening to one of the hooks such as `NOTIFY_FOOTER_END`. The `$db` object is available the global scope.

**Pull request merged**
