### PR TITLE
Admin:header_navigation: php notice for $help_page undefined

### PR DESCRIPTION
**Pull request by torvista**
fixes php notice for $help_page undefined

### CODE REVIEW

**Comment by scottcwilson** [comment]
Thanks - sorry about that.

**Comment by scottcwilson** [comment]
The better fix though is to remove $help_page from admin/includes/header_navigation.php and includes/functions/functions_help.php.  The parameter is no longer needed.

**Comment by drbyte** [comment]
If it's not needed, then let's not merge this PR.

**Comment by scottcwilson** [comment]
Sorry I didn't explain that very well.  The parameter is not needed in both places and should be removed.  It's an artifact of when it was passed to be updated; now the  link is returned.

**Comment by torvista** [comment]
@scott So, you'll PR the changes to stop this error...

**Comment by scottcwilson** [comment]
Just did!  Thanks for reporting.

**Pull request closed without merging**
