### PR TITLE
ZC158: function zen_has_product_attributes, correct typo products_id

### PR DESCRIPTION
**Pull request by torvista**

### CODE REVIEW

**Comment by lat9** [comment]
Noting that the name (arggh) of the input changed from `$products_id` to `$product_id` in the migration from zc157 to zc158.

**Comment by proseLA** [comment]
if we are making notes, i would note that if this was my PR, @scottcwilson would ask me to remove all of those extra spaces on  lines that have nothing to do with this PR so that only the one line is changed; and then squash.

noting that i am coming around to his way of thinking on this issue...

**Comment by torvista** [comment]
You mean I should maintain the extraneous spaces that have been automatically removed by the IDE in accordance with the .editorconfig.
Yes, guilty, I couldn't be bothered to put them back in again. 
If the criteria for PRs is only bugfixes like this and new functionality, when does "unnecessary" code tightening happen?
Not that I consider whitespace removal an "improvement", but someone did, and why not let the IDE do it on any PR when it doesn't affect anything. The history is there.

**Comment by scottcwilson** [comment]
> Noting that the name (arggh) of the input changed from `$products_id` to `$product_id` in the migration from zc157 to zc158.

Should we fix this prior to 1.5.8 being released?

**Comment by proseLA** [comment]
> You mean I should maintain the extraneous spaces that have been automatically removed by the IDE in accordance with the .editorconfig. Yes, guilty, I couldn't be bothered to put them back in again. If the criteria for PRs is only bugfixes like this and new functionality, when does "unnecessary" code tightening happen? Not that I consider whitespace removal an "improvement", but someone did, and why not let the IDE do it on any PR when it doesn't affect anything. The history is there.

i can not really comment on that.  i try and read this:

https://docs.zen-cart.com/dev/contributing/coding_standards/

and it gets too confusing to me.  perhaps my IDE is not configured properly (what a surprise!)  i'm only commenting on what normally happens to me with my PRs, and perhaps that is my IDE config.  

> > Noting that the name (arggh) of the input changed from `$products_id` to `$product_id` in the migration from zc157 to zc158.
> 
> Should we fix this prior to 1.5.8 being released?

i'm of the opinion that we should probably use a consistent var here in this script.  but while we are here talking about `fixes`, perhaps we should add type hinting and get rid of the all of the casting to `int`.  

or is that too radical?

**Comment by scottcwilson** [comment]
@torvista I would prefer that you configure your IDE *not* to remove spaces.  You're creating extra diffs for no benefit. 
Then this all goes away.

**Comment by lat9** [comment]
> > Noting that the name (arggh) of the input changed from `$products_id` to `$product_id` in the migration from zc157 to zc158.
> 
> Should we fix this prior to 1.5.8 being released?

Nope, it was just an unnoticed change when I ported the notification from a client's zc157 installation.

**Pull request merged**
