### PR TITLE
refactoring test framework. Feature tests using symfony browserkit

### PR DESCRIPTION
**Pull request by zcwilt**
This is a major refactor of the test framework to allow Feature testing using symfony browserkit.
It also introduces the concepts of migrations and seeders (taken from Laravel)

It still needs some more work to add more tests and various helpers, especially around Admin Login

the idea here is to increase test code coverage to spot more bugs at the PR level and allow for better TDD

### CODE REVIEW

**Comment by scottcwilson** [comment]
exciting stuff!

**Comment by zcwilt** [comment]
Note: Haven't integrated with github CI yet. Will be testing that next.

**Comment by zcwilt** [comment]
So getting the functional tests running turned out to be more of 'mare' than I thought 
Need to update this so that we are seeding with demo.sql data and then build out a few more tests.

currently i'm just running against 8.0, worry that running against a matrix of php versions will be super slow.

**Comment by scottcwilson** [comment]
Can we make the checkin test only run the current PHP, but have nightly runs against older versions?

**Comment by zcwilt** [comment]
@scottcwilson yes
github actions can be set to run on a cron schedule but have never tried this and not sure how it affects passing PR's

**Comment by torvista** [comment]
I note the auto-testing done on a PR is from 7.4, but the server requirements allow 7.3
https://docs.zen-cart.com/user/first_steps/server_requirements/

**Comment by zcwilt** [comment]
We haven't tested against 7.3 since mid 2022.

**Comment by scottcwilson** [comment]
Yep, the intention of 7.3 support is just to get people past the initial install.  I really don't want anyone to spend a ton of time on it.

**Comment by zcwilt** [comment]
Moved this back to DNR for now. 
Want to add the use of custom seeders for feature tests.

**Pull request merged**
