### PR TITLE
Initial Commit for plugin infrastructure

### PR DESCRIPTION
**Pull request by zcwilt**

### CODE REVIEW

**Comment by lat9** [comment]
Is there going to be some documentation on how a plugin developer might use these interfaces?

**Comment by scottcwilson** [comment]
Yes!

**Comment by lat9** [comment]
Yes, there will be, or Yes, I agree?

**Comment by scottcwilson** [comment]
Both!  The trouble is "Speedy" @zcwilt  codes faster than I can write documentation!  So you have to be patient.

**Comment by drbyte** [comment]
It's a bit early to document this. The code is still in development, hence "Initial commit" in the title.

You'll also note that this PR includes some docs.

I envision us creating a few plugins as examples as well.

**Comment by lat9** [comment]
Yes, I was looking for .md documents rather than .html ones.  I'll also note that for an infrastructure change of this magnitude, I would have anticipated that documentation be developed (and reviewed by the community) _first_, rather than as an after-the-fact.  It's a lot easier to review the written word than written code and then everyone (developers and users) would have a common reference point if/when different interpretations arise.

**Comment by zcwilt** [comment]
I guess this is my fault. The plug-in infrastructure will eventually rely on lots of other changes to core code. An example would be how we load language definitions.  In order to develop that I needed the very basic structure that this PR gave. 

There are also a lot of other core infrastructure changes that plugins will use as well, and the intention is to do these as separate PR's and with those PR's to add to the dev docs.

Again as an example, hopefully I will have a PR shortly for language stuff and pretty much spent this morning writing developer docs for that, which hopefully we will get feedback on.

As those PR's come through the dev docs for plug-ins will be updated as well.

**Comment by zcwilt** [comment]
e.g.

https://raw.githubusercontent.com/zcwilt/zencart/v2-new-language-structure/dev_docs/_build/html/_sources/languageloading.rst.txt

**Comment by zcwilt** [comment]
I guess I should also note https://github.com/zencart/zencart/issues/2057

If you have some comment about how plug-ins etc should work, then you can do it there as well.

**Pull request merged**
