### PR TITLE
Banner Manager: correct id to match label for

### PR DESCRIPTION
**Pull request by torvista**

### CODE REVIEW

**Comment by scottcwilson** [comment]
Nice catch.  Was there a symptom or did you discover it reading code?

**Comment by torvista** [comment]
Your friend and mine the html validator, is still kicking ass.

**Comment by scottcwilson** [comment]
Very good. I vaguely recall that in some cases (checkboxes?) if those two don't match, hilarity ensures. :(

**Comment by torvista** [comment]
Maybe, if you don't go out much.

**Pull request merged**
