### PR TITLE
Allow image-only category description

### PR DESCRIPTION
**Pull request by zenexpert**
Details discussed here: https://www.zen-cart.com/showthread.php?228328-Category-description-getting-cleared

### CODE REVIEW

**Comment by scottcwilson** [comment]
I'm not wild about this. The description is supposed to be a block of text.  Could this be a plugin instead?

**Comment by zenexpert** [comment]
It's not a matter of turning it into an additional plugin. Here's a c/p from the forum:

_What I'm saying - we either need a warning in messagestack to let the store owner know that the code was stripped down, or we shouldn't strip it down. Or maybe something else, dunno. Just not a silent strip down._

There's no clear info that it SHOULD be a block of text or anything alike - imagine the frustration not knowing what it *should* be and you add 10-20 images before realizing it's not working and there's no explanation why...

**Comment by scottcwilson** [comment]
This issue has come up exactly once in the 15 years I have been doing this.  It's an edge case and a bad idea (as noted by @dbltoe on the forum).  There's already a category image if you want to display an image.  Descriptions and titles are text.

**Comment by proseLA** [comment]
i disagree.  just because you have only seen it once in 15 years does not mean it's not a problem.

it's another one of those hard coded things that ZC does that has frustrated a valued member of the community.  i think the downside of allowing 4 different tags is minimal.

and more importantly, if you strip them and NOT tell the admin they were stripped, i think that's bad communication.

**Pull request closed without merging**
