### PR TITLE
Disable Continue Button if Terms not agreed

### PR DESCRIPTION
**Pull request by brittainmark**
Disable the continue button if terms and conditions are required and have
not been checked.
Added labels to continue button and the  tick box for terms and condition.
Added JavaScript to disable and re-enable the continue button when terms and conditions box is checked.
Added change of colour to CSS for disabled button (grey).

### CODE REVIEW

**Review by lat9 — COMMENTED** [review]
Rather than 'burdening' the responsibility on the template, since site-specific templates are very common, this functionality should, IMO, be moved to `/includes/modules/pages/checkout_payment/jscript_main.php`.

The page's submit button is already _presumed_ to be wrapped in a `#paymentSubmit` block, so it can be located by the javascript/jQuery portion that enables and disables the submit button.

The conditions' checkbox is identified by its _presumed_ `#conditions` id, so the javascript could us an `on('change')` mechanism to bind to the checkbox's change event.

**Comment by brittainmark** [comment]
Thanks for the feed back @lat9 . I'll rewrite. Should I include code for one page check out like @proseLA has done with SquareWebPay?

**Comment by lat9** [comment]
> Thanks for the feed back @lat9 . I'll rewrite. Should I include code for one page check out like @proseLA has done with SquareWebPay?

I've got the associated change request noted on the OPC GitHub repository; thanks @brittainmark

**Comment by brittainmark** [comment]
replaced by #4833

**Pull request closed without merging**
