### PR TITLE
Fix ANSI mode issues

### PR DESCRIPTION
**Pull request by scottcwilson**
As reported in https://www.zen-cart.com/showthread.php?230070-Testing-v2-0-0-Upgrade-Issues-Errors-When-Loading-Order-Details

### CODE REVIEW

**Comment by lat9** [comment]
Here's a screenshot of all the hits on the `ORDER BY LPAD` usage.  You can, of course, safely ignore the hit on the `shopping_cart - Copy.php`:
image

**Comment by scottcwilson** [comment]
ok updated.

**Comment by scottcwilson** [comment]
The second argument is an integer; neither single nor double quotes are required.

**Comment by proseLA** [comment]
> The second argument is an integer; neither single nor double quotes are required.

that's really interesting.  but you are changing all of the 3rd arguments.

IMO, all of the 3rd arguments should be done in single quotes.

**Comment by scottcwilson** [comment]
Apparently counting is not a strength of mine today.  Thanks for finding this!

**Review by lat9 — CHANGES_REQUESTED** [review]
`/includes/functions/functions_products.php` (in the `zen_products_sort_order` function) needs this change as well.

**Review by lat9 — APPROVED** [review]
Thanks, @scottcwilson, I'm confident that all 'bases' are now covered.

**Comment by scottcwilson** [comment]
Did you mean to merge into master? I thought this was a bug fix.

**Comment by lat9** [comment]
Crud, I missed the `2.0.x` label.

**Comment by lat9** [comment]
Should I revert and then merge into `2.0`?

**Comment by scottcwilson** [comment]
Let's sit tight and see what @drbyte says.  There is a 100% chance this is not the only time one of us will make a mistake, and we should have a recipe for fixing it.

**Pull request merged**
