### PR TITLE
salemaker: category tree, replace hard-coded 0 with TOPMOST_CATEGORY_PARENT_ID

### PR DESCRIPTION
**Pull request by torvista**

### CODE REVIEW

**Comment by scottcwilson** [comment]
Maybe do admin/categories.php as well?

**Comment by torvista** [comment]
> Maybe do admin/categories.php as well?

Eh?

**Comment by scottcwilson** [comment]
seems to have the same issue.  see admin/categories.php line 114

**Comment by torvista** [comment]
not sure:https://github.com/zencart/zencart/issues/5162

**Pull request merged**
