### PR TITLE
Use CDN for admin bs/fa/jqui

### PR DESCRIPTION
**Pull request by drbyte**
Switch to CDN as preferred load source

### CODE REVIEW

**Comment by drbyte** [comment]
Question: how important is it to include source files for these in the distribution core?

I'm inclined to delete the self-hosted assets so we don't have to maintain them on an ongoing basis. 

Loading from CDN is simple and straightforward. Updating a version number is simpler maintenance.

Only downside is if you're offline ... but if you're offline then you're not using your live database either.
Or the rare case of a firewall blocking the CDN. But then your storefront will have similar challenges.

**Comment by barco57** [comment]
So no fallback? I am aware that rarely if ever does a CDN fail to load... how about fallback to a different CDN

**Comment by drbyte** [comment]
How do you fallback a css file load?

**Comment by barco57** [comment]
Nevermind, I am an idiot, didn't think it through all of the way

**Comment by drbyte** [comment]
Darn, I was hoping you had a solution! 😊

**Comment by torvista** [comment]
>Only downside is if you're offline ... but if you're offline then you're not using your live database either.

Personally I had for many years had to work/develop offline or with wet-piece-of-string internet connection (petrochemical desert camps/offshore) and had things in place in the code to deal with that/not cause errors/wait for timeouts. 
So while not advocating that all necessary code should be **in** the code, at least it should allow for failure gracefully.

**Comment by drbyte** [comment]
> So while not advocating that all necessary code should be **in** the code, at least it should allow for failure gracefully.

Well, having the files **in** the distro doesn't automatically "do" any sort of failover/fallback.

... unless you know of a non-intrusive way of having the browser identify that the content of a CSS file hasn't been loaded ...

**Comment by drbyte** [comment]
@Zen4All Is the `bootstrap-theme.css` file intentionally not loaded?

**Comment by Zen4All** [comment]
no, didn't know it was there

**Pull request merged**
