### PR TITLE
Restore keywords to search box

### PR DESCRIPTION
**Pull request by drbyte**
Ref #6483

### CODE REVIEW

**Comment by drbyte** [comment]
Open to discussion before merge ...

**Review by proseLA — COMMENTED** [review]
i think i left some code comments...  i'm not sure if they are showing up!

**Comment by scottcwilson** [comment]
Is this ready to merge?

**Comment by proseLA** [comment]
i'm good with whatever chris wants to do.  the code conversation and differences, as i recollect, were quite minor.

**Pull request merged**
