### PR TITLE
admin activity: add admin user filter

### PR DESCRIPTION
**Pull request by torvista**
Clipboard01

Why?
Recently I had reason to check specific user activity and this was useful.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Interesting idea, but I would think that exporting and using your spreadsheet's filtering command would be faster.  
Let's see what others think.

**Comment by torvista** [comment]
> I would think that exporting and using your spreadsheet's filtering command would be faster.
Faster than selecting a dropdown? Not at all. Remember this also applies to viewing onscreen.

**Comment by scottcwilson** [comment]
@proseLA @lat9 Are you OK with merging this PR?  Looking for a +1.

**Comment by proseLA** [comment]
without getting too deep into the weeds, in general, i have no problem with what @torvista is doing here.

i do have some changes for issues that i have found.  specifically, somewhere at the top, i would add the following line:

```
$confirmation_needed = false;
```
i would change the following lines:
https://github.com/zencart/zencart/blob/f3cb6df1c59f6a31e2cd3cfc4b32f7576b1116ad/admin/admin_activity.php#L136-L139

to:
```
                if ($records == 0) {
                    $messageStack->add(TEXT_NO_RECORDS_FOUND, 'error');
                    $action = '';
                } else { //process records
```
and i would then change these lines:
https://github.com/zencart/zencart/blob/f3cb6df1c59f6a31e2cd3cfc4b32f7576b1116ad/admin/admin_activity.php#L297-L301
to:
```
                       unset($f);
                    } // endif $save_to_file
                    zen_redirect(zen_href_link(FILENAME_ADMIN_ACTIVITY));
                } //end if $records for processing not 0
                break;
```

if you select a user that has no records, you are redirected and lose all of your post data.  i do not like that.  there is no need to redirect when no records are found.

while i am here, i would change all 33 instances of `<?php echo ` to `<?= `.  i find that format far more legible when echoing php vars within the html.

**Comment by torvista** [comment]
I think both these suggestions warrant separate PRs as they seem additional, so I can do that subsequently.

**Comment by torvista** [comment]
The two suggestions are additional but not part of this PR, as far as I can see. So this PR could be merged as is, I think?

**Comment by scottcwilson** [comment]
OK based on @proseLA 's +1 I will review and merge this PR shortly.

**Pull request merged**
