### PR TITLE
Admin: option_names_manager overhaul

### PR DESCRIPTION
**Pull request by torvista**
This was mostly done in September with a long commit history but was pre-empted by another PR.
Those changes have been mostly incorporated into this but the commit history got hosed in the interim.
So, sorry for yet another big bang.  It is a very complicated file, with a lot to test....

Fixes:
insert of new option: sql had these fields expected:products_options_images_per_row, products_options_images_style, products_options_rows as POST values, but are not set on insert: removed.
Insert of new option: the next option id to use was being defined in the form generation on the previous page, multiple users could obtain the same next_id. Moved it to immediately prior to the INSERT.
check for duplicate name: used COUNT in the sql, then ->recordcount which is always 1, so no alert. Decided to not use count as it does not count nulls.
usual html validations for unclosed tags etc. and label for not pointing at the id of a corresponding input fields.

Changes in no particular order
Additions to two functions, maintaining legacy functionality, to allow ordering and formatting/filtering of results
Improved formatting.
Greatly expanded notification messages for every type of success and fail, with corresponding changes to constants.

Global tools:
removed unecessary show/hide: tools do not run any queries until a Option Name select dropdown is used. Change of an Option name reloads the page with the dropdown results filtered.
Added sort option to dropdown.
Added full path option to dropdown.

### CODE REVIEW

**Comment by drbyte** [comment]
How solid is this? Have you tested it thoroughly? 
What's going to break when people upgrade?

**Comment by torvista** [comment]
The two functions I have modifed are only used here and in option_values and those are working as before without the extra parameters.
Nothing should break elsewhere as far as I am aware.
I need to look at the conflicts and I see there are some comments to be removed, so I'm pausing this until tomorrow.

**Comment by torvista** [comment]
Aside from a potential need to check duplicates in the products options names to values table:
https://github.com/zencart/zencart/issues/3201#issuecomment-616233416
this should ready to be beaten with a large stick by everyone.

**Comment by torvista** [comment]
I can't resolve this conflict.

**Comment by scottcwilson** [comment]
Not with that attitude you can't!

**Comment by scottcwilson** [comment]
That's the spirit!

**Comment by torvista** [comment]
I give up! It's complained three times about a conflict on different lines. On this last attempt it accepted all, except the last line, now it has the identical complaint as the first time.
So, I was right first time. I can't resolve this!

**Comment by drbyte** [comment]
I've reviewed (just the section it was showing as conflicting) and committed what I think is a fix.

However, I noticed 2 things that need attention:

1. `TEXT_OPTION_ATTIBUTE_MAX_LENGTH` - you left out the `R` in `attRibute`. Does it need fixing elsewhere too?

2. The name of the constant refers to images here, but you removed mention of images. Was that intentional? Is the constant name still appropriate?
```diff
-define('TEXT_OPTION_ATTRIBUTE_IMAGES_STYLE', 'Attribute Image Layout Style (for Checkbox/Radio Buttons only)');
+define('TEXT_OPTION_ATTRIBUTE_IMAGES_STYLE', 'Attribute Style for Radio Buttons/Checkbox: ');
```

**Comment by torvista** [comment]
More confused:
TEXT_OPTION_ATTIBUTE_MAX_LENGTH
I didn't find any occurrance of that

and my TEXT_OPTION_ATTRIBUTE_IMAGES_STYLE still mentions the images.

So, don't know and it's time for bed (said Zebedee).

**Comment by scottcwilson** [comment]
```
./admin/includes/languages/english/options_name_manager.php:define('TEXT_OPTION_ATTIBUTE_MAX_LENGTH', '<strong>NOTE: Rows, Display Size and Max Length are for Text Attributes Only:</strong><br />');
./admin/options_name_manager.php:                        <div class="col-sm-12"><?php echo TEXT_OPTION_ATTIBUTE_MAX_LENGTH; ?></div>
```

**Comment by torvista** [comment]
but they are both in the old files, not mine:
Clipboard01
Clipboard02

**Comment by scottcwilson** [comment]
If you're not updating these files, I will go ahead and fix.  Having misspelled names can cause problems for people trying to search and find things.

**Comment by torvista** [comment]
`If you're not updating these files, I will go ahead and fix.`
Eh? Are we looking at different things?
The spelling mistake is marked in the red stuff...that is being replaced by my stuff. Gone.

**Comment by scottcwilson** [comment]
LOL sorry I thought you were saying it wasn't in your update.

**Comment by drbyte** [comment]
> but they are both in the old files, not mine:

Okay. Sometimes my brain looks at merge conflicts in reverse direction. I apologize if I accidentally undid any changes you were intending in this PR when I attempted the fix of merge conflicts.

**Comment by torvista** [comment]
It got there in the end. Hope you all like it, please test!

**Comment by torvista** [comment]
suggested format for new option name, carrying on from
https://github.com/zencart/zencart/pull/3330

I've not pushed this yet:

Clipboard01

Clipboard02

**Comment by zcwilt** [comment]
Hopefully have fixed conflicts caused by merging other PR's

**Comment by scottcwilson** [comment]
Should we defer until 1.5.8?

**Comment by zcwilt** [comment]
Haha, sorry @scottcwilson 
Wanted to merge this as it affects at least 3 other PR's

**Comment by scottcwilson** [comment]
LOL OK.

**Comment by zcwilt** [comment]
maybe in the future manage these bi page changes better.

**Comment by torvista** [comment]
> maybe in the future manage these big page changes better.

This stymied me as Zen4all updated it before me, then I left it to fester for ages, then Github ignorance caused me to wipe all the commit history etc. 

I think the problem is there is too much interrelated on the one file. Very hard to manage it into separate PRs to allow easier review...especially as I continually get better ideas, but very slowly!
My development is very iterative,
and if there is a few days/week delay between PR merge/accept it's very hard to get back into it again, since it's such a long script.
I won't make the mistake with values manager!

Anyway, I hope it gets more testing now. No-one has mentioned if it is any better than it was!!!

**Comment by scottcwilson** [comment]
It's better than it was.  The filtering is very powerful. 

Now that it has been merged would you please write a bullet or two on this change and put it into #3263 for addition into the What's New file?  Thanks.

**Comment by torvista** [comment]
ok, added and PR to your branch.

**Pull request merged**
