### PR TITLE
v158: zen_image updates for accessibility and ...

### LINKED ISSUE #5063: Improve Accessibility for Sideboxes
When the sideboxes for New Products, Specials, and Featured are generated, if an items fits the qualifications, the link and information are presented in <div class="sideboxContentItem" and generate an A link using the image as the text for the link,

The image data for the Bug' Life DVD comes out to be:
`A Bug's Life Linked<br>"A Bug's Life Linked"</a>`

The system is taking the Product's Title and uses it for the alt tag, the image title, and the displayed link text underneath.

This generates an alert for Redundant Alternativ Text.  This confuses browser readers and might make the SEs lower rank for keyword stuffing.

If the link is changed to the following, all Accessibility standards would be met.

`<br>"A Bug's Life Linked"</a>`

Most all browsers see the empty alt tag as being presentational.  The newer browsers will accept the role tag.  This will result in about 35 alerts on the main page of the out-of-the-box going away.

I'm assuming the changes would be made in (e.g. Featured) at line 17 of includes/template_default/sideboxes/tpl_featured.php.

Since these are different from the items in the center boxes AND I am not knowledgeable enough to figure the code.  I enter it here.

If someone presents the proper code change, I will do the PR and hopefully not mess it up. 😄 

FYI -- It appears that the center page layout for Featured and others uses the same tpl.

### PR DESCRIPTION
**Pull request by lat9**
- Refactoring to use PSR indentation and exactly-equal-to
- Reduce number of times a file's existence is determined (performance)
- Use is_file instead of file_exists; file_exists indicates existence for directories, too
- Logic restructuring to remove redundant/duplicated checks

Fixes #5063

### CODE REVIEW

**Comment by dbltoe** [comment]
While not fully understanding the code, I can see where the items that were discussed elsewhere are better used here.  Especially the use of ratio.
👍

**Comment by brittainmark** [comment]
What happens when $width is set to a % not sure code will work correctly.

**Comment by lat9** [comment]
> What happens when $width is set to a % not sure code will work correctly.

The only time that a % width/height works is if Image Handler is installed.  The current/legacy version also casts those variables to ints:

https://github.com/zencart/zencart/blob/614b2d6f860339ed81e6e39026a89ece8b72e426/includes/functions/html_output.php#L213-L216

Although that implementation also keeps a `''` as part of the `empty` path without conversion.

**Comment by brittainmark** [comment]
Yes saw that. The reason for the question is 'HEADER_LOGO_WIDTH' => '100%'  exists in lang.header.php
I have checked, and it does not appear to be used in the main set of store files. 
However, it gives the impression that % is ok for a width. Maybe need to remove from store language files.

**Comment by lat9** [comment]
> Yes saw that. The reason for the question is 'HEADER_LOGO_WIDTH' => '100%' exists in lang.header.php I have checked, and it does not appear to be used in the main set of store files. However, it gives the impression that % is ok for a width. Maybe need to remove from store language files.

Hmm, that changed since zc157.  I'll open a separate PR to restore that to the pixel width/height of the default logo.gif.

**Pull request merged**
