### PR TITLE
output model first when sorted by model

### PR DESCRIPTION
**Pull request by proseLA**
what @torvista wants, he gets....

i think its better.

### CODE REVIEW

**Comment by torvista** [comment]
In that case, a 30-hour day please?

**Comment by scottcwilson** [comment]
Would you please do before and after screenshots so it's obvious what's happening?

**Comment by proseLA** [comment]
man, you guys are demanding!

before:
image

after:
image

**Comment by torvista** [comment]
Is the first one is not sorted by name?

I had got rid of the brackets when model was leading and ID and space, just to compress it a bit more:
image

Not that I am advocating it, doesn't matter what you do, someone will want to to change it....that was my next step, how to override the default format.

**Comment by proseLA** [comment]
> Is the first one is not sorted by name?
> 
did you really just ask that?

no.

**Comment by proseLA** [comment]
@scottcwilson i do not know how detailed you want to get.  similar to other carts, we could create an open class file for people to override defaults rather easily (ha)...  a little more work, but i can see its value.

**Comment by scottcwilson** [comment]
> @scottcwilson i do not know how detailed you want to get. similar to other carts, we could create an open class file for people to override defaults rather easily (ha)... a little more work, but i can see its value.

Was this regarding another ticket?   I'm not sure I understand what you're saying here ...

**Comment by proseLA** [comment]
> > @scottcwilson i do not know how detailed you want to get. similar to other carts, we could create an open class file for people to override defaults rather easily (ha)... a little more work, but i can see its value.
> 
> Was this regarding another ticket? I'm not sure I understand what you're saying here ...

i'm just thinking out loud.  no new ticket.  right now we have:

`class productPulldown extends pulldown`

we could have 2 separate class files, ie:

`class productPulldownBase extends pulldown`  (this is a rename of the existing `productPulldown` class.)
and
`class productPulldown extends productPulldownBase`

the 2nd one would be completely empty, and then anyone could override any element there for their own needs.  it would make upgrading easier going forward.  its a bit more infrastructure but for those people who want to modify the pulldown, it makes upgrading easier due to not changing any core file.

**Pull request merged**
