### PR TITLE
Updates for strict-types

### LINKED ISSUE #6082: functions_products: zen_get_prid(): Argument #1 ($uprid) must be of type string, int given
add 
declare(strict_types=1);
to the start of functions_products

Add a product to the cart
PHP Fatal error:  Uncaught TypeError: zen_get_prid(): Argument #1 ($uprid) must be of type string, int given, called in includes\functions\functions_products.php on line 550 and defined in \includes\functions\functions_products.php:458

I suggest adding the same (declare(strict_types=1);) to the shopping_cart class at the same time for related useages/as it is debateable exactly where fixes should be applied.

### PR DESCRIPTION
**Pull request by drbyte**
Fixes #6082

### CODE REVIEW

**Comment by torvista** [comment]
But then in strict types mode, **explode** on the next line complains when it is fed an integer...I've got functions_products and the shopping cart class using strict types mode and there are ("only") half a dozen places where casting is needed to clear all the errors (when a product is added to the cart).

**Comment by drbyte** [comment]
Right.

Remember, `coercive typing` is one of the reasons people choose PHP over other languages like Java and C that are heavily strictly-typed.

**Comment by torvista** [comment]
While I may the only one beating ZC with this stick, there are really very few places left where ZC falls foul of this/it's nearly ready for a stricter world. Be nice to clear them.

**Comment by drbyte** [comment]
Test with several non-attribute products, with fractional quantities. Errors not thrown.

You probably have some specific products that warrant testing this with, though.

**Comment by torvista** [comment]
Simple products give no errors.

Product with attributes: 
PHP Fatal error:  Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, int given in includes\classes\shopping_cart.php:316

https://github.com/zencart/zencart/blob/e6bce467a03a354704aac28ba9bb77634e73a403/includes/classes/shopping_cart.php#L316

**Comment by drbyte** [comment]
Thanks. I'll reset my demo data later and check this

**Comment by drbyte** [comment]
Lots more updates made.
There's a HUGE risk of introducing rounding errors due to the loss of precision that occurs when trying to implement strict-typing with numeric data when it could legitimately be an `integer` or a `float` interchangeably ... such as with fractional quantities and with taxes.
I really hope this didn't break anything.

**Comment by torvista** [comment]
In my limited testing, with the shopping_cart class, functions_products and functions_general_shared all using strict types, I could checkout with simple and attributed products with no rounding errors.

Only two simple errors:

https://github.com/zencart/zencart/blob/e6bce467a03a354704aac28ba9bb77634e73a403/includes/functions/functions_general_shared.php#L20

$limit being passed as string instead of int.

https://github.com/zencart/zencart/blob/e6bce467a03a354704aac28ba9bb77634e73a403/includes/functions/functions_general_shared.php#L191-L197

$key being passed to stripslashes as an int instead of a string

**Comment by drbyte** [comment]
> $key being passed to stripslashes as an int instead of a string

This is because elsewhere (some of) those values were cast to int for other reasons.

**Pull request merged**
