### PR TITLE
Allow apostrophes in search string

### PR DESCRIPTION
**Pull request by scottcwilson**
Test: Add product called "Tim's Coffee"
Search for "Tim's Coffee"

### CODE REVIEW

**Comment by lat9** [comment]
Just be careful of the Apple "Smart Quotes", e.g &lsquo; and &ldquo;.

**Comment by scottcwilson** [comment]
This is meant to handle an apostrophe which can be typed in from the keyboard.

**Comment by lat9** [comment]
> This is meant to handle an apostrophe which can be typed in from the keyboard.

Unfortunately, that "Smart Quotes" setting/feechur on Apple devices, when enabled, converts the single/double quotes to the &lsquo; and &ldquo; characters when the user presses the quote key on the keyboard.

**Comment by scottcwilson** [comment]
I have smart quotes on and tested with it.

**Pull request merged**
