### PR TITLE
reformat for eye check #5671

### PR DESCRIPTION
**Pull request by proseLA**

### CODE REVIEW

**Comment by torvista** [comment]
Have you settled on a method for formatting?

**Comment by scottcwilson** [comment]
TY @proseLA

**Comment by proseLA** [comment]
> Have you settled on a method for formatting?

@torvista i have not; and it is not really my decision to make.  

i used what i thought best.  you can find [my phpStorm config files here.](https://www.dropbox.com/s/2cqgfkvobxep7bc/phpStorm_settings.zip?dl=0)

best.

**Comment by torvista** [comment]
thanks

**Pull request merged**
