### PR TITLE
Renaming file to remove spaces from filename

### PR DESCRIPTION
**Pull request by scottcwilson**
Files with spaces are problematic for Linux/Mac users.

### CODE REVIEW

**Comment by drbyte** [comment]
Hmmmm ... `.psd` ... is that file even used?

**Comment by scottcwilson** [comment]
It's not used in the cart; I figured it was preserved as a documentation artifact.

**Comment by drbyte** [comment]
Eventually we'll probably just delete that `psd` folder.
I don't want to set a precedent that invites a million PRs to clean up the AdminLTE stuff ... cuz we're planning to "lean it out" before final release.

**Comment by drbyte** [comment]
Did you run into this because of a problem?  Or just "oh, I'm using Linux, and spaces are usually a problem, so I should fix that before it becomes a problem"?

**Comment by scottcwilson** [comment]
`find . <some pattern> `
gives me a bunch of errors every time I run it because of this file.  It's quite annoying.

**Pull request merged**
