### PR TITLE
move search to WORDS_AND_SYMBOLS_REGEX sanitize

### LINKED ISSUE #5465: Ampersand searches fail in admin
Repro:

Create a product called "M&M"
Observe that searching on the storefront will find this product.
In Admin, go to Catalog > Categories/Products and search for "M&M".
Product is not found.

### PR DESCRIPTION
**Pull request by proseLA**
fixes #5465

### CODE REVIEW

**Comment by scottcwilson** [comment]
@barco57 The salient change here is line 215 adding `search` to the list passed to `WORDS_AND_SYMBOLS_REGEX`.   Would you please test in your environment?

**Comment by scottcwilson** [comment]
Works for me in 1.5.8.  @proseLA can you squash?

**Comment by proseLA** [comment]
> @barco57 The salient change here is line 215 adding `search` to the list passed to `WORDS_AND_SYMBOLS_REGEX`. Would you please test in your environment?

there are two _salient_ changes.  they are easily seen in the [first commit.](https://github.com/zencart/zencart/pull/5466/commits/3ba6f92dac4561898e040fe6854e9859c1bbba3d)

**Comment by proseLA** [comment]
> Works for me in 1.5.8. @proseLA can you squash?

no.  it was purposely done as 2 commits.  that way when merged you can see the code correction in the first commit.  and you can see the reformat in the 2nd commit.

**Pull request merged**
