### PR TITLE
fixes #4702; missing parentheses in sql; square

### LINKED ISSUE #4702: bug in reset tokens in square
https://github.com/zencart/zencart/blob/dc22072b1a1ea66b3e4fce9efe781ca43557f5e2/includes/modules/payment/square.php#L601-L609

lines 605 and 607 need to end `')");` no `'");`

apparently no one is resetting their tokens.

### PR DESCRIPTION
**Pull request by proseLA**

### CODE REVIEW

**Comment by scottcwilson** [comment]
Thanks - I was just thinking about this one the other day.

**Comment by scottcwilson** [comment]
I think only the second line change is required though - the first and the third look wrong.  Would you please check again?

**Comment by proseLA** [comment]
not enough coffee this morning.  

i was initially correct on #4702.  two changes are required.  not four.

good catch.

best.

**Comment by scottcwilson** [comment]
Gold, Jerry, Gold!

**Pull request merged**
