### PR TITLE
remove leading and trailing spaces in title tags

### PR DESCRIPTION
**Pull request by torvista**
to lay to rest a long burning issue...
https://www.zen-cart.com/showthread.php?217229-zen_image-Why-the-extra-spaces-in-the-title-attribute

### CODE REVIEW

**Comment by drbyte** [comment]
I still don't understand why people (or "validators" even) are so bothered about this. What exactly is the technical "reason" for it being a "problem"?

Ya, we'll merge this. But will somebody please answer the "why" question with a legit practical reason?

**Comment by wiztechinc** [comment]
The main reason for me is so that when template writers check their own work, they don't have to wade through errors and warnings they didn't create. That said, that particular problem is not highlighted with the checker I use. There are plenty of other errors and warnings that appear. You can see the result on the 1.5.7 cart (as of a few days ago) here: https://validator.w3.org/nu/?doc=http%3A%2F%2Fdeliasdomains.com%2F1_5_7%2F 

I do think we need to be aware of these issues and correct them as we go along. But I do not consider this something to stress over.

**Comment by torvista** [comment]
Of course it is not a real problem, it's just not supposed to be there and serves no real purpose apart from prompting a few nit pickers to ask why it is there. So why not get rid of it.

**Comment by torvista** [comment]
>other errors and warnings that appear
already reported:
https://github.com/zencart/zencart/issues/2993

**Pull request merged**
