### PR TITLE
Fixes #35 Address codes

### LINKED ISSUE #35: Bring default country-address-format assignments up to date
Many built-in country records have a default address-format assignment of '1' which is not always correct. 

We welcome input for updates, but with your update recommendation, please provide a URL to a website which offers official confirmation of the correct format you're proposing. 

We'll happily incorporate updates which can be officially confirmed. 

Thanks!

### PR DESCRIPTION
**Pull request by brittainmark**
Brings address codes up to date. Fixes #35

**Address format changes**
modified install files and tested on server with php 8.0.14:
1 clean install with empty database and no configuration file
2 clean install with empty database and configuration file
3 clean install 1.5.7c then update to 1.5.8
4 Added Additional address format to address formats, Created order using that address format. Tested it was moved to new address id.

My sources for address formats where [informatica](https://www.informatica.com/products/data-quality/data-as-a-service/address-verification/address-formats.html) and [loqate](https://www.loqate.com/en-gb/address-verification/international-address-formats). Loqate appeared to be more recent and had more formats with postcodes.
Below is a table with the formats an example and the countries to which they are applied.

| Format | Address Format| Example  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| Countries |
|--------|----------------------|---------------|------------|
|1|$firstname $lastname$cr$streets$cr$city, $postcode$cr$statecomma$country |firstname surname<br>street address<br>addressline2<br>city, postcode<br>state, country|  Default Not used|
|2|$firstname $lastname$cr$streets$cr$city, $state    $postcode$cr$country|firstname surname<br>street address<br>addressline2<br>city, state postcode<br>country|Latvia<br>Myanmar<br>Saint Kitts and Nevis<br>Somalia<br>Trinidad and Tobago|
|3|$firstname $lastname$cr$streets$cr$city$cr $postcode - $statecomma$country|firstname surname<br>street address<br>addressline2<br>city<br>postcode - state, country|Not Used|
|4|$firstname $lastname$cr$streets$cr$city ($postcode)$cr$country|firstname surname<br>street address<br>addressline2<br>city (postcode)<br>country|Not Used|
|5|$firstname $lastname$cr$streets$cr $postcode $city$cr$country|firstname surname<br>street address<br>addressline2<br>postcode city<br>country|Åland Islands<br>Albania<br>Algeria<br>Andorra<br>Argentina<br>Armenia<br>Austria<br>Azerbaijan<br>Belgium<br>Bosnia and Herzegowina<br>Bulgaria<br>Cape Verde<br>Chile<br>Croatia<br>Cyprus<br>Czech Republic<br>Denmark<br>Dominican Republic<br>Equatorial Guinea<br>Estonia<br>Ethiopia<br>Faroe Islands<br>Finland<br>France<br>French Guiana<br>French Polynesia<br>French Southern Territories<br>Gabon<br>Georgia<br>Germany<br>Greece<br>Greenland<br>Guadeloupe<br>Guinea<br>Guinea-bissau<br>Haiti<br>Iceland<br>Israel<br>Jamaica<br>Kuwait<br>Lao People's Democratic Republic<br>Liechtenstein<br>Lithuania<br>Luxembourg<br>Macedonia, The Former Yugoslav Republic of <br>Madagascar<br>Martinique<br>Mayotte<br>Moldova<br>Monaco<br>Morocco<br>Netherlands<br>New Caledonia<br>Niger<br>Norway<br>Paraguay<br>Poland<br>Portugal<br>Réunion<br>Romania<br>San Marino<br>Senegal<br>Slovakia (Slovak Republic)<br>Slovenia<br>St. Pierre and Miquelon<br>Svalbard and Jan Mayen Islands<br>Sweden<br>Switzerland<br>Syrian Arab Republic<br>Tajikistan<br>Turkmenistan<br>Uruguay<br>Wallis and Futuna Islands<br>Palestine,  State of <br>Montenegro<br>South Sudan|
|6|$firstname $lastname$cr$streets$cr $city$cr$state$cr$postcode$cr$country|firstname surname<br>street address<br>addressline2<br>city<br>state<br>postcode<br>country|Afghanistan<br>British Indian Ocean Territory<br>Egypt<br>Falkland Islands (Malvinas)<br>Gibraltar<br>India<br>Iran (Islamic Republic of)<br>Ireland<br>Kazakhstan<br>Kenya<br>Kiribati<br>Malta<br>Montserrat<br>Pitcairn<br>Russian Federation<br>Seychelles<br>Solomon Islands<br>South Africa<br>South Georgia and the South Sandwich Islands<br>Sri Lanka<br>St. Helena<br>Swaziland<br>Togo<br>Turks and Caicos Islands<br>Tuvalu<br>Ukraine<br>United Arab Emirates<br>United Kingdom<br>Uzbekistan<br>Serbia<br>Zimbabwe<br>Guernsey<br>Isle of Man<br>Jersey|
|7|$firstname $lastname$cr$streets$cr $city $state $postcode$cr$country|firstname surname<br>street address<br>addressline2<br>city state postcode<br>country|American Samoa<br>Australia<br>Cambodia<br>Canada<br>Cayman Islands<br>China<br>Christmas Island<br>Cocos (Keeling) Islands<br>Colombia<br>Guam<br>Guyana<br>Heard and Mc Donald Islands<br>Japan<br>Korea,  Republic of <br>Marshall Islands<br>Micronesia, Federated States of <br>Norfolk Island<br>Northern Mariana Islands<br>Pakistan<br>Palau<br>Puerto Rico<br>United States<br>United States Minor Outlying Islands<br>Virgin Islands (U.S.)<br>Curaçao<br>Sint Maarten (Dutch part)|
|8|$firstname $lastname$cr$streets $cr$city$cr$country|firstname surname<br>street address<br>addressline2<br>city<br>country|Angola<br>Antigua and Barbuda<br>Aruba<br>Barbados<br>Benin<br>Bolivia<br>Botswana<br>Bouvet Island<br>Burundi<br>Cameroon<br>Central African Republic<br>Chad<br>Comoros<br>Congo<br>Côte d'Ivoire<br>Djibouti<br>Dominica<br>Eritrea<br>Fiji<br>Gambia<br>Grenada<br>Hong Kong<br>Libya<br>Macao<br>Malawi<br>Mali<br>Mauritania<br>Mauritius<br>Namibia<br>Qatar<br>Rwanda<br>Saint Lucia<br>Samoa<br>Sao Tome and Principe<br>Sierra Leone<br>Suriname<br>Tonga<br>Uganda<br>Vanuatu<br>Western Sahara<br>Yemen|
|9|$firstname $lastname$cr$streets $cr$postcode $city $state$cr$country|firstname surname<br>street address<br>addressline2<br>postcode city state<br>country|Cuba<br>Honduras<br>Italy<br>Liberia<br>Mexico<br>Tunisia<br>Turkey<br>Vatican City State (Holy See)|
|10|$firstname $lastname$cr$streets$cr $city $postcode$cr$country|firstname surname<br>street address<br>addressline2<br>city postcode<br>country|Anguilla<br>Antarctica<br>Bahamas<br>Bahrain<br>Bangladesh<br>Belize<br>Bermuda<br>Bhutan<br>Burkina Faso<br>Cook Islands<br>Timor-Leste<br>Indonesia<br>Jordan<br>Korea, Democratic People's Republic of<br>Lebanon<br>Lesotho<br>Maldives<br>Mongolia<br>Nauru<br>Nepal<br>Bonaire, Sint Eustatius and Saba <br>New Zealand<br>Niue<br>Saint Vincent and the Grenadines<br>Saudi Arabia<br>Singapore<br>Taiwan<br>Tokelau<br>Virgin Islands (British)<br>Zambia|
|11|$firstname $lastname$cr$streets$cr $city $state$cr$postcode$cr$country|firstname surname<br>street address<br>addressline2<br>city state<br>postcode<br>country|Brazil<br>Costa Rica<br>Ghana<br>Iraq<br>Thailand|
|12|$firstname $lastname$cr$streets$cr $postcode$cr$city $state$cr$country|firstname surname<br>street address<br>addressline2<br>postcode<br>city state<br>country|Ecuador<br>Nicaragua<br>Peru<br>Sudan|
|13|$firstname $lastname$cr$streets$cr $city $postcode$cr$state$cr$country|firstname surname<br>street address<br>addressline2<br>city postcode<br>state<br>country|Nigeria|
|14|$firstname $lastname$cr$streets $cr$postcode $city$cr$state$cr$country|firstname surname<br>street address<br>addressline2<br>postcode city<br>state<br>country|Belarus<br>El Salvador<br>Guatemala<br>Kyrgyzstan<br>Malaysia<br>Mozambique<br>Panama<br>Tanzania, United Republic of |
|15|$firstname $lastname$cr$streets$cr $postcode$cr$city$cr$state$cr$country|firstname surname<br>street address<br>addressline2<br>postcode<br>city<br>state<br>country|Oman|
|16|$firstname $lastname$cr$streets$cr $city $postcode $state$cr$country|firstname surname<br>street address<br>addressline2<br>city postcode state<br>country|Papua New Guinea<br>Venezuela|
|17|$firstname $lastname$cr$streets$cr $city$cr$postcode $state$cr$country|firstname surname<br>street address<br>addressline2<br>city<br>postcode state<br>country|Philippines|
|18|$firstname $lastname$cr$streets$cr $city$cr$state $postcode$cr$country|firstname surname<br>street address<br>addressline2<br>city<br>state postcode<br>country|Brunei Darussalam<br>Viet Nam|
|19|$firstname $lastname$cr$city$cr$streets$cr $postcode$cr$country|firstname surname<br>city<br>street address<br>addressline2<br>postcode<br>country|Hungary|
|20|$firstname $lastname$cr$streets$cr $postcode $city ($state)$cr$country|firstname surname<br>street address<br>addressline2<br>postcode city (state)<br>country|Spain|

### CODE REVIEW

**Comment by scottcwilson** [comment]
This looks good - just one question: In the EXTREMELY UNLIKELY event that someone has already added entries above 7 to the address_format table, should we begin at (say) 108 instead of 8?  I'm not strong on this, just wanted to throw it out.  @lat9 thoughts?

**Comment by brittainmark** [comment]
For info, the only way to add to the address formats is via SQL. Will change if you think necessary or could add a check or change existing to 100 range.
```
UPDATE address_format SET address_format_id = address_format_id +100  WHERE address_format_id > 7;
UPDATE countries SET address_format_id = address_format_id +100  WHERE address_format_id > 7;
```
do above first update.

Another point. address_format_id  is set to auto increment. Don't know if above will cause problems.

Just out of interest, is this why we do not add new countries automatically? The same method could be used if it does not cause issue with auto increment.

**Comment by scottcwilson** [comment]
> Just out of interest, is this why we do not add new countries automatically?  

We do, but we don't set the countries_id field.  (New countries don't come along very often.  We did it in 1.5.5).

**Comment by scottcwilson** [comment]
> could add a check or change existing to 100 range.... 

No, I am suggesting changing the new ones being added - instead of adding 8, 9, 10 ... add 108, 109, 110.

**Comment by brittainmark** [comment]
> No, I am suggesting changing the new ones being added - instead of adding 8, 9, 10 ... add 108, 109, 110.

Yes Understood that. Was proposing an alternative. Probably would be better to move any above 7 to 17+

```
UPDATE address_format SET address_format_id = address_format_id + 9  WHERE address_format_id > 7;
UPDATE countries SET address_format_id = address_format_id + 9  WHERE address_format_id > 7;
```
If we do that, then we do not need to think we have to add in the range 200 if it happens again. By doing this, we move other people's additions outside the core range and can add more in future without fragmenting the range each time.

**Comment by scottcwilson** [comment]
Right but then we'd also have to update the address_format_ids in the orders table.  
Your way might be better once this is done - need to think about this some more.

**Comment by brittainmark** [comment]
> Right but then we'd also have to update the address_format_ids in the orders table.

As I have modified some existing formats (1-7) to new formats, should I have left all the original formats and added new ones for the changed formats? So move to a new set starting at 8 leaving the origional 1-7 in place and allocating new numbers to all countries. If doing that then starting at 100 might be a good idea. Happy to make the change as it will not be too dificult to add 100 to my existing changes.

OR

I could identify the use of address_format_id in all tables and change as needed.

**Comment by scottcwilson** [comment]
Sit tight for now.  What you have is very close, we just have to figure out how to deal with the oddball cases.

**Comment by scottcwilson** [comment]
OK.  What if we leave as is but add a pre-install check for address_format_ids in range 8-16 and fail if they exist.  In the failure message, point them to https://docs.zen-cart.com/user/upgrading/address_format_id 

I will author this page and give instructions on how to update hand-added data.  

Also are you sure we need the changes to includes/functions/functions_addresses.php?

**Comment by brittainmark** [comment]
### Changes to includes/functions/functions_addresses.php 
**Lines  312-316**
lastnameupper is a requirement for French addresses, the surname should be uppercase.
statebracket is the official Spanish address format, if the state is present it should be in brackets. I know @torvista did not think it was necessary, but the documentation suggests that this is the correct format. 

**Other changes**
The rest of the change is making addresses title case if they are not entered in upper case. People tend to be lazy and enter their addresses in lowercase I thought it would be nicer to display them in Title case

Your call if you want me to revert. Will have to decide what to do with French and Spanish addresses.

### address_format_id greater than 8 existing:

The Sql to move any addresses in the range 8-16 is relatively simple.
```
UPDATE address_format SET address_format_id = address_format_id + 9  WHERE address_format_id > 7;
UPDATE countries SET address_format_id = address_format_id + 9  WHERE address_format_id > 7;
UPDATE orders SET customers_address_format_id = customers_address_format_id + 9 WHERE customers_address_format_id  > 7;
UPDATE orders SET  delivery_address_format_id = delivery_address_format_id + 9 WHERE delivery_address_format_id > 7;
UPDATE orders SET  billing_address_format_id = billing_address_format_id + 9 WHERE billing_address_format_id > 7;
```

Just needs inserting before the address codes are updated in  zc_install/sql/updates/mysql_upgrade_zencart_158.sql  line 131. This just moves any  existing address formats outside the range we are using. Save you a lot of effort (could add something to the update documentation to let people know what is happening).

**Comment by scottcwilson** [comment]
I love your SQL suggestion - let's do that. 

For the changes to includes/functions/functions_addresses.php - let's leave this out for now and make it a plugin or add it to the documentation.   We could even add this sort of thing to a language pack in the future. 

Should be good to go after this.

**Comment by brittainmark** [comment]
Sorry for being pedantic! Do you mean leave all the changes out in which case what do you want to do with Spanish and French addresses.
OR
Just leave out the title case?

**Comment by scottcwilson** [comment]
Leave all the changes out.   No changes to includes/functions/functions_addresses.php.

**Comment by brittainmark** [comment]
The more I think about this the more potential problems I see.
If someone has added an address format and moved a country to that address then when we have finished the country code will be wrong.

I suggest that I re work this including the SQL changes to ensure that people keep their changes. This would mean onl;y updating countries where the format matches the default format.

Additionally if we want to keep the original address formats for historic entries, that I keep the origional 7 codes and add new ones starting at 8 with sql to move any existing codes after 7.

If you do not want any changes to includes/functions/functions_addresses.php then spain is the same as format 3 now and I will replace &lastnameupper with &lastname for france addresses 

Can probably have it done by the end of the week.

Assuming you ok with this

I asume I need to rebase to v158 in git
git checkout
git rebase -i v158

    change all but the first "pick" to "f" (for fix).
    git commit --amend
    git push -f

or would it be easier to close this pull request and i'll create a new one with the new code.

**Comment by scottcwilson** [comment]
> Rebase or new branch 

your call

> I suggest that I re work this including the SQL changes to ensure that people keep their changes. This would mean 
> only updating countries where the format matches the default format.

OK

> If you do not want any changes to includes/functions/functions_addresses.php...

correct - no changes to this file please.

**Comment by brittainmark** [comment]
Have updated it. Think I may have something wrong as
`## Remove remnants of tell a friend`
Appears to be missing. If it should be there I'll put in back in.

**Comment by brittainmark** [comment]
Have restored the missing tell a friend delete statement. I think it is ready now.

**Comment by brittainmark** [comment]
Is this going into 1.5.8? do you want me to create/update documentation?

**Comment by torvista** [comment]
Bit late to the party, but as far as here in Spain goes, I've never received a letter with the province in brackets as per format 20.

These examples all coincide with the postal code preceding the city on the same line, and the province on a new line.
https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/espEn.pdf
https://es.wikipedia.org/wiki/Direcci%C3%B3n_postal#Espa%C3%B1a
https://www.loqate.com/en-gb/address-verification/international-address-formats

and this poor example
https://www.informatica.com/products/data-quality/data-as-a-service/address-verification/address-formats.html?code=ESP

which I think only has the province in brackets to indicate "if necessary"...since some provinces have the same name as the city such as Leon/Madrid/Toledo and others, so the province name of Leon/Madrid/Toledo etc. is superfluous.

As the address formats stand today, Spain fits format 14, so 20 could be dropped.

**Comment by brittainmark** [comment]
Given the issues with post since the UK left the EU. I prefer to stick with what [Royal mail tells me.]
(https://www.royalmail.com/sending/international/country-guides/spain)

**Remember to use the correct address format** 
Put the postcode, town, and province (in brackets) on one line.
Please write 'SPAIN' in capital letters on the last line of the address.
Example:

Sra Ana Jimenez 
Mimbreras 4 
03201 ELCHE (Alicante) 
SPAIN

I have had items returned because the address was in the wrong format.

**Comment by torvista** [comment]
Well, I've said my piece for the record! There are now enough formats to please almost everyone, your effort is appreciated.

**Pull request merged**
