### PR TITLE
admin, categories: add missing constant definitions

### PR DESCRIPTION
**Pull request by torvista**

### CODE REVIEW

**Comment by zcwilt** [comment]
Hi @torvista 
I've marked this on hold as I am currently close to doing a PR for language loading (arrays) 
Do not close as it's a reminder to integrate into my PR.
Thanks

**Comment by torvista** [comment]
If I want to improve these error handling messages that adds variables to the messages and modifies categories.php, how should I do that, PR-wise? Bearing in mind this PR as is now, is applicable to 157 now as a bugfix. But with further modification, it becomes a two-file change....

**Comment by drbyte** [comment]
Since this is a bugfix for 1.5.7, and zcwilt is refactoring language things in 1.5.8, please do a separate PR to the 1.5.7 branch for it.
I would have pulled it over myself but you split it into multiple commits instead of amend-and-force-pushing-it so that it was a single clean commit.

**Comment by drbyte** [comment]
> If I want to improve these error handling messages that adds variables to the messages and modifies categories.php, how should I do that, PR-wise?

Since that's completely separate from the bugfix, it should be a standalone PR.

**Comment by drbyte** [comment]
Closed by #3633

**Pull request closed without merging**
