### PR TITLE
headless api

### PR DESCRIPTION
**Pull request by zcwilt**

### CODE REVIEW

**Comment by drbyte** [comment]
Was this intentional?
Screen Shot 2024-01-19 at 8 22 38 PM

**Comment by zcwilt** [comment]
yes.  previous code only really used the Laravel/capsule database stuff.

This pulls in the whole Laravel backend to allow us to leverage routes/views/filament etc

**Comment by drbyte** [comment]
Should we upgrade it to v9 again?

**Comment by zcwilt** [comment]
@drbyte yeah we could do
only requires php8.0 and the upgrade guide seems ok 
I'll look to do this once I've finished some work on the cart classes, which is a dependancy for this

**Pull request closed without merging**
