### PR TITLE
Refactor display logs HTML5

### PR DESCRIPTION
**Pull request by brittainmark**
Move existing style to style sheet and added to it.

### CODE REVIEW

**Comment by scottcwilson** [comment]
@lat9 Please review and approve at your convenience.

**Comment by lat9** [comment]
Color me confused.  I thought that the idea of the plugin structuring was to provide a versioned (er) version of the updates.  This is updating v3.0.0 in-place.

**Comment by brittainmark** [comment]
Yes, as I said, I did not know what to do and Scott said he would sort it, Or, so I assumed!  See #5011 comments for details. If someone tells me what to do, I'll do it. But I don't know what if anything should be done with install etc. If you want it resubmitted as 3.0,1 I'll do it, but I suspect it will not be correct.

**Comment by scottcwilson** [comment]
I had forgotten that this moved into the core.  Please update the version number; a new one is needed.

**Comment by brittainmark** [comment]
I can do that, do I just include the changed files?

**Comment by scottcwilson** [comment]
no it's a full set each time.

**Comment by brittainmark** [comment]
OK. Does that mean that in install file will need rewriting? 
What is the process for update? Should the old installation be removed  (all variables removed from db) then the  new one installed? 
Does the installation process run the installation from version 3.0.0 then the installation from 3.0.1?

Additionally, what should I change in the manifest?

Is there any documentation to say how the process works?

**Comment by brittainmark** [comment]
I assume I am the first person to attempt to upgrade a plugin. copied all files and get white screen when i try to upgrade.
log file.
```
[24-Jul-2022 11:17:55 Europe/London] Request URI: /Test158/YOURADMIN/index.php?cmd=plugin_manager&page=1&colKey=DisplayLogs&action=doUpgrade, IP address: 127.0.0.1
#1  Zencart\ViewBuilders\PluginManagerController->processActionDoUpgrade() called at [/home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ViewBuilders/BaseController.php:37]
#2  Zencart\ViewBuilders\BaseController->processRequest() called at [/home/lotus/public_html/innerlightcrystals/Test158/YOURADMIN/plugin_manager.php:94]
#3  require(/home/lotus/public_html/innerlightcrystals/Test158/YOURADMIN/plugin_manager.php) called at [/home/lotus/public_html/innerlightcrystals/Test158/YOURADMIN/index.php:11]
--> PHP Warning: Undefined property: Zencart\ViewBuilders\PluginManagerController::$currentRow in /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ViewBuilders/PluginManagerController.php on line 277.

[24-Jul-2022 11:17:56 Europe/London] Request URI: /Test158/YOURADMIN/index.php?cmd=plugin_manager&page=1&colKey=DisplayLogs&action=doUpgrade, IP address: 127.0.0.1
#1  Zencart\ViewBuilders\PluginManagerController->processActionDoUpgrade() called at [/home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ViewBuilders/BaseController.php:37]
#2  Zencart\ViewBuilders\BaseController->processRequest() called at [/home/lotus/public_html/innerlightcrystals/Test158/YOURADMIN/plugin_manager.php:94]
#3  require(/home/lotus/public_html/innerlightcrystals/Test158/YOURADMIN/plugin_manager.php) called at [/home/lotus/public_html/innerlightcrystals/Test158/YOURADMIN/index.php:11]
--> PHP Warning: Attempt to read property "unique_key" on null in /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ViewBuilders/PluginManagerController.php on line 277.

[24-Jul-2022 11:17:55 Europe/London] PHP Fatal error:  Uncaught Zencart\Exceptions\PluginInstallerException: NO PLUGIN VERSION DIRECTORY in /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/PluginSupport/InstallerFactory.php:30
Stack trace:
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ViewBuilders/PluginManagerController.php(277): Zencart\PluginSupport\InstallerFactory->make()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ViewBuilders/BaseController.php(37): Zencart\ViewBuilders\PluginManagerController->processActionDoUpgrade()
#2 /home/lotus/public_html/innerlightcrystals/Test158/YOURADMIN/plugin_manager.php(94): Zencart\ViewBuilders\BaseController->processRequest()
#3 /home/lotus/public_html/innerlightcrystals/Test158/YOURADMIN/index.php(11): require('...')
#4 {main}
  thrown in /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/PluginSupport/InstallerFactory.php on line 30

[24-Jul-2022 11:17:56 Europe/London] Request URI: /Test158/YOURADMIN/index.php?cmd=plugin_manager&page=1&colKey=DisplayLogs&action=doUpgrade, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught Zencart\Exceptions\PluginInstallerException: NO PLUGIN VERSION DIRECTORY in /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/PluginSupport/InstallerFactory.php:30
Stack trace:
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ViewBuilders/PluginManagerController.php(277): Zencart\PluginSupport\InstallerFactory->make()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ViewBuilders/BaseController.php(37): Zencart\ViewBuilders\PluginManagerController->processActionDoUpgrade()
#2 /home/lotus/public_html/innerlightcrystals/Test158/YOURADMIN/plugin_manager.php(94): Zencart\ViewBuilders\BaseController->processRequest()
#3 /home/lotus/public_html/innerlightcrystals/Test158/YOURADMIN/index.php(11): require('...')
#4 {main}
  thrown in /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/PluginSupport/InstallerFactory.php on line 30.
```
Will attempt to debug!

**Comment by lat9** [comment]
Thanks for this, @brittainmark.  I believe, as you've indicated, that you are wading into previously untested waters!  Your findings and the steps that you use will help others in the future.

**Comment by brittainmark** [comment]
OK I have it working. What should I put in the manifest. Currently looks like this:
```
return [
    'pluginVersion' => 'v3.0.1',
    'pluginName' => 'Display logs',
    'pluginDescription' => 'Display and manage Zen Cart log files.',
    'pluginAuthor' => 'Vinos de Frutas Tropicales (lat9)',
    'pluginId' => 1583, // ID from Zen Cart forum
    'zcVersions' => ['v158'],
    'changelog' => '', // online URL (eg github release tag page, or changelog file there) or local filename only, ie: changelog.txt (in same dir as this manifest file)
    'github_repo' => '', // url
    'pluginGroups' => [],
];
```

**Comment by brittainmark** [comment]
OK I think I have it now. This needs #5046 
I tried the update process on 1.5.7, and it did not work. So I have set the manifest to 1.5.8 only. I have not updated anything else except the version number, as I don't know what you want changed.

**Comment by lat9** [comment]
> OK I have it working. What should I put in the manifest. Currently looks like this:
> 
> ```
> return [
>     'pluginVersion' => 'v3.0.1',
>     'pluginName' => 'Display logs',
>     'pluginDescription' => 'Display and manage Zen Cart log files.',
>     'pluginAuthor' => 'Vinos de Frutas Tropicales (lat9)',
>     'pluginId' => 1583, // ID from Zen Cart forum
>     'zcVersions' => ['v158'],
>     'changelog' => '', // online URL (eg github release tag page, or changelog file there) or local filename only, ie: changelog.txt (in same dir as this manifest file)
>     'github_repo' => '', // url
>     'pluginGroups' => [],
> ];
> ```

I'll suggest changing the plugin author to give yourself credit for all the work you've done in ironing-out the plugin-update process!

**Comment by brittainmark** [comment]
Thanks, but not worth another commit for that.

**Comment by scottcwilson** [comment]
> This needs #5046

just merged.

**Comment by scottcwilson** [comment]
@brittainmark Can you squash and we'll get this merged?

**Comment by brittainmark** [comment]
Squashed

**Pull request merged**
