### PR TITLE
Mobile model display on orders screen needs line break

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
Hmmm ... Changing to `visible-xs` may do the job fine too. I thought you wanted it on the same line, hence using `-inline`

**Comment by scottcwilson** [comment]
I could have sworn it was on a new line when I initially tested this change.  Anyhow it looks better on a new line.

**Comment by drbyte** [comment]
Image 2020-05-18 at 4 03 31 PM
Image 2020-05-18 at 4 02 55 PM
Image 2020-05-18 at 4 02 09 PM

**Comment by scottcwilson** [comment]
Door number 2.

**Comment by drbyte** [comment]
Did you wanna force-push an update?

**Pull request merged**
