### PR TITLE
admin_actity: revert empty to zen_not_null

### PR DESCRIPTION
**Pull request by torvista**
fixes: https://github.com/zencart/zencart/issues/4848

### CODE REVIEW

**Comment by torvista** [comment]
That must be a record!

**Comment by scottcwilson** [comment]
Right place right time.

**Comment by lat9** [comment]
@torvista, what was the issue being solved here?

**Comment by torvista** [comment]
referenced in first post.

**Comment by lat9** [comment]
Thanks, Steve, my apologies; I appear to be losing (what's left of) my mind.

**Comment by torvista** [comment]
> I appear to be losing (what's left of) my mind

Not a problem, you still appear to have plenty to spare.

**Pull request merged**
