### PR TITLE
fixes #3425 pass current language to ajax helper

### LINKED ISSUE #3425: Installer: when using non en_US language, popup texts still use en_US

### PR DESCRIPTION
**Pull request by zcwilt**

### CODE REVIEW

**Comment by torvista** [comment]
I find the second page reverts back to en_us after es_es selected on the first page.
Changing it manually to es_es does subsequently render the comments in spanish.

**Comment by zcwilt** [comment]
hmm. I thought we had fixed the url helper for that a while ago.
Will take a look.

**Comment by zcwilt** [comment]
Ok. Missed some conversions of $lng to $installer_lng

**Comment by torvista** [comment]
that seems ok. 
Aside, this constant needs updating
'TEXT_HELP_TITLE_DEMODATA' => '%%TEXT_DATABASE_SETUP_LOAD_DEMO%%',

**Comment by zcwilt** [comment]
@torvista thanks for testing this, and catching the oopsies.

**Comment by torvista** [comment]
Hope all this language stuff has some payback....

**Pull request merged**
