### PR TITLE
V156 admin facelift

### PR DESCRIPTION
**Pull request by Zen4All**
This update may be a good intermediate between the 1.5.x series and 1.6

These that are included right now are the first. I am working on the rest.

---
This change is [Reviewable](https://reviewable.io/reviews/zencart/zencart/1550)

### CODE REVIEW

**Comment by drbyte** [comment]
This is looking great!   

How ready do you feel this is for review+merge?

**Comment by Zen4All** [comment]
I think I am done for now. The most important pages have been done

**Comment by drbyte** [comment]
What do you think about changing the "Update" button in Attributes Controller to read "Edit"? (see image)

cloudapp annotation 2017-12-15 at 6 34 10 pm png

**Comment by Zen4All** [comment]
I have no objection to that. Most of the buttons have the default text, that also were present in the original page. I'll make a commit later today.

**Comment by drbyte** [comment]
Thanks. 
Found another issue. Do you recall running into this when working on the EZ-Pages UI?

cloudapp annotation 2017-12-19 at 2 21 50 pm png

**Comment by Zen4All** [comment]
I didn't see that, but will have a look on my test site.

**Comment by drbyte** [comment]
Thanks for all your work on this!

**Pull request merged**
