### PR TITLE
Updating paragraph referring to doc site

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by judygunderson** [comment]
http://docs.zen-cart.com/Developer_Documentation/1.5.5 is correct link - there is no v before the 1.5.5

**Comment by scottcwilson** [comment]
Judy, that part has been deleted (the block in red on the left is removed, the block in green on the right is added.

**Comment by judygunderson** [comment]
HA!  I am a moron and had just woken up and had no coffee!  Sorry about that!

**Comment by zcwilt** [comment]
@judygunderson :+1:  for more coffee

**Comment by drbyte** [comment]
Do you mind turning `docs.zen-cart.com` back into a clickable link?

**Comment by scottcwilson** [comment]
Good idea.  Done.

**Pull request merged**
