### PR TITLE
Include dependent submodules into core

### PR DESCRIPTION
**Pull request by drbyte**
These mature modules rarely change, and including them in core makes things simpler for everyone.

NOTE: Aura\Di requires PHP 5.5 minimum, so raising ZC minimum from 5.4.2 to 5.5.0

### CODE REVIEW

**Comment by scottcwilson** [comment]
Once this is merged, I will update the documentation on docs.zen-cart.com.

**Comment by zcwilt** [comment]
Doing a manual merge onto v160 
I get 

    error: The following untracked working tree files would be overwritten by merge:
    includes/library/aura/web/.gitignore
    includes/library/aura/web/.scrutinizer.yml
    includes/library/aura/web/.travis.yml
    includes/library/aura/web/CHANGES.md
    includes/library/aura/web/LICENSE
    includes/library/aura/web/README-REQUEST.md
    includes/library/aura/web/README-RESPONSE.md
    includes/library/aura/web/README.md
    includes/library/aura/web/autoload.php
    includes/library/aura/web/composer.json
    includes/library/aura/web/config/Common.php
    includes/library/aura/web/src/Exception.php
    includes/library/aura/web/src/Exception/InvalidComponent.php
    includes/library/aura/web/src/Exception/InvalidStatusCode.php
    includes/library/aura/web/src/Exception/InvalidVersion.php
    includes/library/aura/web/src/Request.php
    includes/library/aura/web/src/Request/Client.php
    includes/library/aura/web/src/Request/Content.php
    includes/library/aura/web/src/Request/Files.php
    includes/library/aura/web/src/Request/Globals.php
    includes/library/aura/web/src/Request/Headers.php
    includes/library/aura/web/src/Request/Method.php
    includes/library/aura/web/src/Request/Params.php
    includes/library/aura/web/src/Request/Url.php
    includes/library/aura/web/src/Request/Values.php
    includes/library/aura/web/src/Response.php
    includes/library/aura/web/src/Response/Cache.php
    includes/library/aura/web/src/Response/Content.php
    includes/library/aura/web/src/Response/Cookies.php
    includes/library/aura/web/src/Response/Headers.php
    includes/library/aura/web/src/Response/Redirect.php
    includes/library/aura/web/src/Response/Status.php
    includes/library/aura/web/src/ResponseSender.php
    includes/library/aura/web/src/WebFactory.php
    Please move or remove them before you can merge.


strange that it is only aura/web

**Comment by zcwilt** [comment]
Ok. 

I think I know what is happening here.
In a global .git sense aura/web is untracked as it was managed by submodules. Other submodules have had their directories changed so there is no clash 
e.g.   +define('URL_AURADI', 'aura/di/src/');
would suggest changing the path for aura we as well 
maybe to aura/webRequest/

**Comment by drbyte** [comment]
No, changing the path is not recommended. The others were changed because I changed them to match their names as Composer treats them. This way to update them is as simple as a `composer require foo/foobar --prefer-dist` and then move the files into the `library` folder. 

The message you got was simply a result of using submodules previously. Simple solution: delete those folders from within `library` and do a fresh checkout/merge.

**Comment by scottcwilson** [comment]
So the recommended approach is 

rm -rf includes/library/aura/web

?

**Comment by drbyte** [comment]
I think one can safely do the following:

```
rm -rf includes/library/
```

And then when merging it will repopulate the directory with anything that's missing. 

(Or, you could just delete everything in there except the zencart folder, particularly if you're working on customizations or additions to the files in there.)

**Comment by zcwilt** [comment]
:+1:

**Pull request merged**
