### PR TITLE
change <br /> to <br>

### PR DESCRIPTION
**Pull request by torvista**
and correct 
`<br/>` missing space

Emails are still using  `<br />` although they probably can be changed too?

### CODE REVIEW

**Comment by scottcwilson** [comment]
Please squash.

**Comment by torvista** [comment]
Could I include the installer/admin constant description texts in this?

**Comment by scottcwilson** [comment]
sure

**Review by proseLA — CHANGES_REQUESTED** [review]
please do NOT change a minimized javascript library.  you want to work on updating this library to the latest version, great.  but changing `jquery.flot.pie.min.js` in this PR is short-sighted at best.

**Comment by proseLA** [comment]
please do not merge this PR.  changing vendor source files as well?  changing commented out lines?

this PR, while good intentioned, needs additional testing.  i am not sure what we gain.  and it creates a bunch of extra work for store owners when upgrading for no apparent reason.

we should not be manually updating other libraries or vendor files to suit a html validation scheme to resolve errors.

**Comment by scottcwilson** [comment]
Agreed, we will not be changing admin/includes/javascript/flot/jquery.flot.pie.min.js or any other vendor file. 
See code review comment above.

Changing language files is fine.

**Comment by torvista** [comment]
The changes to vendor files were a bleary-eyed mistake, apologies.

Changes  to comments, pointless sure, just part of an easy search and replace so future global code searches would result in actual code and user additions only. Just trying to get a 100% score for whatever aspect of minor code consistency.

I think Upgrade Hell is already on the cards for anyone thinking of doing a merge-update into their existing site instead of a new install and adding db + mods, but I don't have the demands on me of doing that work for others, so up to others to make that decision.
There are so many file changes already that perhaps now is the best time to make multiple minor/non-functionality file changes and assume people will only file-compare for adding their mods, not globally.

Additionally I would have thought that now (a version change) would be the right time to introduce any future-necessary breaking changes.

**Comment by proseLA** [comment]
again, i respectfully disagree with many points. 
> The changes to vendor files were a bleary-eyed mistake, apologies.
>
accepted.  
> Changes to comments, pointless sure, just part of an easy search and replace so future global code searches would result in actual code and user additions only. Just trying to get a 100% score for whatever aspect of minor code consistency.

again, i disagree that a 100% score is goal worthy.  that said, changing commented out code does NOTHING to achieve that goal.

i'm just not sure you realize that your 'easy search and replace' makes it more difficult for people like myself.  i can get behind thoughtful changes, but not this one.

here's a thought: why are there commented out echo statements in the middle of the code?  are they illustrative of anything?  do they help someone decipher the code?  get rid of them.  i'm all for comments; but not debug statements for someone digging in.  they make little sense to be there.  perhaps when the repo was created 10 years ago, but now?
> 
> I think Upgrade Hell is already on the cards for anyone thinking of doing a merge-update into their existing site instead of a new install and adding db + mods, but I don't have the demands on me of doing that work for others, so up to others to make that decision. There are so many file changes already that perhaps now is the best time to make multiple minor/non-functionality file changes and assume people will only file-compare for adding their mods, not globally.

this reasoning does not fly with me.  it's already hard. so let's make it harder?
> 
> Additionally I would have thought that now (a version change) would be the right time to introduce any future-necessary breaking changes.

future necessary breaking changes?  at the pace this repo goes?  

let's look here:

https://stackoverflow.com/questions/1946426/html-5-is-it-br-br-or-br

the question received a higher rating than the answer!

and in case you do not want to go through it all:

image

again, this PR does not address and bugs in ZC nor does it provide any additional functionality.  i think the goal is not worthy, and it creates, IMO, an additional burden on store owners and developers for no good reason.

**Comment by scottcwilson** [comment]
> Just trying to get a 100% score for whatever aspect of minor code consistency.

There's a checkbox for that test.  Uncheck it.  It's not worth doing a ton of work and introducing a lot of changes for.  Yes let's clean up the language files but let's not go crazy. 

> Additionally I would have thought that now (a version change) would be the right time to introduce any future-necessary breaking changes.

For language files ok but not for other stuff. 

At this point when we're trying to get 1.5.8 to alpha, I really want people to focus on *fixing bugs*, not getting their IDE to green.

**Comment by scottcwilson** [comment]
> here's a thought: why are there commented out echo statements in the middle of the code? are they illustrative of anything? do they help someone decipher the code? get rid of them. i'm all for comments; but not debug statements for someone digging in. they make little sense to be there. perhaps when the repo was created 10 years ago, but now?

The ones that remain are still there because Chris wouldn't let me get rid of them.  You'll notice a huge reduction from (say) 1.5.4 to now, but some of them he wanted to keep.

**Comment by torvista** [comment]
I guess this draws my attention due to the lack of bugs!
All constructive comments thanks.

**Pull request closed without merging**
