### PR TITLE
Removes duplicate key

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by zcwilt** [comment]
:+1: 
Also not sure why it's using email-address instead of email_address

**Comment by drbyte** [comment]
👍

**Comment by scottcwilson** [comment]
Chris, in case you did want the change from email-address to email_address made, it looks like these are the files: 

./library/zencart/CheckoutFlow/src/AccountFormValidator.php
./library/zencart/CheckoutFlow/src/flowSteps/EmailOnly.php
./library/zencart/CheckoutFlow/src/flowSteps/Guest.php
./templates/template_default/templates/tpl_checkout_guest_account_collect_default.php
./templates/template_default/templates/tpl_checkout_guest_emailonly_account_collect_default.php

**Comment by drbyte** [comment]
I'll defer to @zcwilt, since that was his comment and initially his code.

**Comment by scottcwilson** [comment]
Ack - I misread, sorry about that Ian.

**Pull request merged**
