### PR TITLE
zc157: Ask-a-Question, correct PHP Notices when no 'pid' supplied ...

### PR DESCRIPTION
**Pull request by lat9**
- If no $_GET['pid'], redirect to the site's main page.  Otherwise, various PHP notices are thrown by the template since the `$product_details` isn't set.
- Simplification of antispam conditional
- Pre-fill customer information only if logged in and (added) not in guest checkout.

### CODE REVIEW

**Comment by mc12345678** [comment]
Curious, why not send to `contact_us` instead of the main page if pid is not provided? Perhaps with consideration of whether the `contact_us` page is activated or not? And/or consideration that the original Ask-a-question plugin used `products_id` as the parameter which was modified to `pid` when incorporated into ZC?

**Comment by lat9** [comment]
If the pid's not provided, then someone's modifying the browser address-bar to try to fuss with the site.  Whatever page is redirected to makes no difference to me, it's just important to not pass through to the template since no information will be gathered.

I've no idea why the zc-incorporation of the plugin version chose to use `pid` instead of `products_id`, but my feeling is that now that Zen Cart's placed a stake-in-the-sand that the name-change should stay.

**Comment by drbyte** [comment]
> I've no idea why the zc-incorporation of the plugin version chose to use `pid` instead of `products_id`,

That was to reduce the URL length

**Comment by drbyte** [comment]
> Curious, why not send to `contact_us` instead of the main page if pid is not provided?

That could be a good option. 
A PR exploring that approach is welcome.

**Pull request merged**
