### PR TITLE
Adjust added product to max of max and units

### PR DESCRIPTION
**Pull request by mc12345678**
When adding a product to the cart, where the addition of the item results in more product in the cart than allowed, the resulting quantity was set to the maximum quantity in stock followed by the maximum quantity allowed for the product and/or mix of attributes. The originally calculated maximum may not align with units where this commit corrects the maximum to account for the product's units.  This takes out one factor of a customers concern about what it takes to not exceed the maximum and still meet the units.  It will though likely lead to confusion about why they can not add more especially if there is some sort of indication of what the maximum quantity of product is that is in stock when units are a factor.  

This modification applies only to adding product to the cart, a separate commit is required to address other aspects such as updating the cart or other such `action` sections. Ultimately this prevents adding a quantity that violates the units when attempting to add the maximum allowed/available quantity.

Intended to address one of many aspects of #3342, specifically when initially adding a quantity to the cart that leads to exceeding the maximum quantity supported by the product configuration.

Looking for review/testing of this before merge and also looking for suggestions of "messages" to be presented.

### CODE REVIEW

**Comment by mc12345678** [comment]
Having submitted this PR "moments" before 3607, should I rebase this?

**Comment by drbyte** [comment]
> Having submitted this PR "moments" before 3607, should I rebase this?

Yes. Specifically, this PR is for a new feature (or improvement of sorts) and not a fix for a showstopper bug in v157, so it should be in the new v158 branch.

**Comment by drbyte** [comment]
Since these 3 code blocks are effectively identical, probably best to extract them to a separate method (function in this class), and just pass it the necessary parameters it requires, so it can return the updated $new_qty.

Then again, the request for suggested message responses reminds me that for this situation there's no way to know for certain if any of this is even relevant for a given store. 
This makes me inclined to suggest that these code blocks be replaced with just a single Notifier hook and let the storeowner write their own custom code to handle it (or you could move this logic to an observer and package it as a plugin), instead of having this logic in core code.

**Comment by scottcwilson** [comment]
@mc12345678 Would you please get this updated so we can merge?

**Pull request closed without merging**
