### PR TITLE
Correct document products' editing

### LINKED ISSUE #2572: document_general/_product: Invalid HTML and PHP Notices
Each of the `document_general` and `document_product` types' `preview_info.php` is generating invalid HTML due to the placement of the `</form>` tag.

In addition, saving a `document_general` product throws a slew of PHP Notices (see below) due to database fields that aren't supported by the product type:

```
[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: products_quantity in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 24.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: products_model in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 26.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: products_price in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 27.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: products_weight in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 29.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: products_virtual in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 31.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: products_tax_class_id in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 32.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: manufacturers_id in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 33.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: products_priced_by_attribute in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 36.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: product_is_free in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 37.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: product_is_call in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 38.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: products_quantity_mixed in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 39.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: product_is_always_free_shipping in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 40.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: products_qty_box_status in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 41.

[14-Jul-2019 09:05:47 America/New_York] Request URI: /zc156posm/gRoan-Dsw-Habit/product.php?cPath=17&action=insert_product, IP address: ::1
#1  require(C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php) called at [C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\product.php:34]
--> PHP Notice: Undefined index: products_quantity_order_max in C:\xampp\htdocs\zc156posm\gRoan-Dsw-Habit\includes\modules\update_product.php on line 42.
```

PR forthcoming.

### PR DESCRIPTION
**Pull request by lat9**
Fixes #2572

### CODE REVIEW

**Comment by mc12345678** [comment]
Not directed at you as a contributor to correcting this issue. The below is more of a general discussion/statement. 

And yet the option to add the product type to the catalog remains in the product type selection menu.

Still not sure why the remaining code for the product type doesn't include the ability to have/collect the information when the add-to-cart is enabled but hide it when add-to-cart is disabled and just leave the default upon install to not be able to add-to-cart.

**Comment by mc12345678** [comment]
While part of this correction addresses the `preview_info.php` for just the `document_general` and `document_product` product types, it appears that the `preview_info.php` file for other product types needs to be similarly adjusted as well. 

I just loaded pid=170 (document_general) with the proposed code modification to `preview_info.php` and had no html validation issue after the modification.  I then loaded pid=27 (product) without this modification and had an issue identified with the closing tag for the `form`. When I then applied the `preview_info.php` modification to the product's `preview_info.php` file the html validation issue went away.

I also then tested each with the `read=only` parameter on the URI with no issues either.

**Comment by drbyte** [comment]
> it appears that the `preview_info.php` file for other product types needs to be similarly adjusted as well.

Yes, things should be kept in sync

**Comment by lat9** [comment]
FWIW, I'm not seeing the validation issue on the "Products-General" type products.

**Pull request merged**
