### PR TITLE
v2 fix fatal error: remove call to missing function

### PR DESCRIPTION
**Pull request by torvista**
fatal error on option values, option names, attributes controller

### CODE REVIEW

**Comment by lat9** [comment]
Was that `zen_black_line` function _really_ removed?  That will wreck havoc with a fair number of plugins, I think.

**Comment by scottcwilson** [comment]
This was supposed to be a V2 change.  

Steve, this change REALLY isn't needed, the current develop branch is going to be orphaned and kept for historical purposes only.  You don't need to pursue this.

**Comment by lat9** [comment]
My bad; I see that the function's still present in the zc157 branch.

**Comment by torvista** [comment]
I understand this branch is to be retired off, and will only be for reference, but this is the only thing that actually stops it from working. I certainly don't intend to do anything else.

**Comment by drbyte** [comment]
Closing.
@zcwilt feel free to reopen and merge if you wish.

**Pull request closed without merging**
