### PR TITLE
Add semicolon to includes/classes/payment.php javascript

### PR DESCRIPTION
**Pull request by mc12345678**
Line is missing a closing semi-colon.

### CODE REVIEW

**Comment by drbyte** [comment]
Is there a specific error this is causing?

JavaScript is different in that it often treats an end-of-line the same as PHP would treat a semicolon, so isn't always strictly required. 

But, if there's a problem happening without the semicolon I'd be interested in the details.

**Comment by mc12345678** [comment]
Will take a little doing to validate is/was a problem causing an issue. Was found when working on the PayPal incontext improvement. Is already incorporated in 1.6.0, but will need to see if it is an issue with the same applied in 1.5.5 as is (missing the end semi-colon).

**Comment by drbyte** [comment]
👍

**Comment by zcwilt** [comment]
:+1:

**Pull request merged**
