### PR TITLE
 Enhancement: Featured Categories #6247 

### PR DESCRIPTION
**Pull request by TMCSherpa**
It's mostly made from featured (products) files that have been reworked for use with categories and it works the same way. Everything is turned on by default (category sidebox and the index page is set to group 5)

### CODE REVIEW

**Comment by TMCSherpa** [comment]
Are you sure your test scripts are working? I get the same errors locally on a stock version of zencart.

**Comment by zcwilt** [comment]
Couple of notes.

If you want to see the logs behind why the tests are failing see 

https://github.com/zencart/zencart/actions/runs/10275975225?pr=6633

At the bottom of this page you can download the artifact file which contains error logs.

The reason the tests are failing is that your FeaturedCategory.sql file is never loaded by the tests system, and would also never be loaded in a Zen Cart install.

**Comment by scottcwilson** [comment]
@TMCSherpa Are you updating the dates in the file headers by hand?  Please don't do that.  The dates will get set correctly when the next official build is run.

**Comment by TMCSherpa** [comment]
I'll put it back. Let me fix the SQL stuff and resubmit

**Pull request closed without merging**
