### PR TITLE
Missing Music links

### LINKED ISSUE #5147: Copy Music Product Causes Partial White Screen
**Describe the bug**
when you try to copy a music product, the side box for the copy is not displayed.

**Version**
Zen Cart version: 1.5.8
PHP version: 8.0

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to 'admin>categories and products> Mixed Product Types '
2. Click on 'copy' for Sample of Product Music Type 
3. New screen is displayed missing the copy side box

**Expected behavior**
copy side box should be displayed

**Debug/Error Logs**
none produced

**Additional context**
issue is caused by admin/includes/modules/products_music/copy_product.php being present and having no code.

### LINKED ISSUE #5151: Update Product Music Caused Partial White Screen
Describe the bug
when you try to update a music product, a partial white screen is displayed

Version
Zen Cart version: 1.5.8
PHP version: 8.0

To Reproduce
Steps to reproduce/demonstrate the behavior:

 1.   Go to 'admin>categories and products> Mixed Product Types '
 1.   Click on 'edit' for Sample of Product Music Type
 2. Click on Preview
3.  Click on Update
 1.  New screen is displayed missing the main content

Expected behavior
product should be updated and screen to showing products in category should be displayed

Debug/Error Logs
none produced

Additional context
issue is caused by admin/includes/modules/products_music/update_product.php being present and having no code.

### PR DESCRIPTION
**Pull request by brittainmark**
Fix #5147 
Fix #5151
Add link to default handler

Either merge this change of delete:
- copy_product.php
-  copy_product_confirm.php
-  update_product.php 
- delete_product_confirm.php 

from admin/includes/modules/product_music

### CODE REVIEW

**Comment by scottcwilson** [comment]
Cindy is familiar with the music product.

**Comment by lat9** [comment]
The various stubs in `/includes/modules/product_music` will need to be renamed to have a `_unused` name suffix; otherwise the `auto.ProductMusicObserver.php` will duplicate the processing.  For instance, `collect_info.php` should be renamed to `collect_info_unused.php`.

**Comment by brittainmark** [comment]
Do I also need to change preview_info.php and preview_info_metatags as these were also changed in #5073

**Comment by brittainmark** [comment]
@lat9 collect_info was not changed in #5073 
do you want me to do them all? or shall i close this pull request and let you create a new one as required?

**Comment by lat9** [comment]
> @lat9 collect_info was not changed in #5073 do you want me to do them all? or shall i close this pull request and let you create a new one as required?

Some of the modules had to bring in the base processing, while some needed (e.g. collect_info.php) to be 'their own' modules.  If you close this one, I'll create a PR that simply renames those that are now handled by that observer.

**Comment by brittainmark** [comment]
no problem.

**Pull request closed without merging**
