### PR TITLE
Admin categories/products listing, display Status ... always

### PR DESCRIPTION
**Pull request by lat9**
... as identified in [this](https://www.zen-cart.com/showthread.php?226934-Status-button-not-showing-on-mobile&p=1370451) Zen Cart posting.

Suggest back-porting to zc157.

### CODE REVIEW

**Comment by scottcwilson** [comment]
What if we do this for small (tablets) only and keep the code to hide on xs (phone) devices?

**Comment by lat9** [comment]
> 
> 
> What if we do this for small (tablets) only and keep the code to hide on xs (phone) devices?

How about we ask on that forum-posting?  I believe that the initial report was for a phone.

**Comment by wiztechinc** [comment]
If I was to use my phone , I would want the quickest way to do something. That status button should be visible at all times in my humble opinion.

**Comment by torvista** [comment]
I believe that if someone is in the Admin, its for doing admin things, so all functions should be available.
If it is not pretty/things do not fit well/perfectly...so what.

How many complaints are on the forum about the admin not looking pretty enough, as opposed to "help..the buttons have gone!".

**Comment by drbyte** [comment]
> > What if we do this for small (tablets) only and keep the code to hide on xs (phone) devices?
> 
> How about we ask on that forum-posting? I believe that the initial report was for a phone.

Looks like there's no response to the question posed back on the forum.

I'll merge it, but we'll probably alter the change again later during 1.5.8

**Pull request merged**
