### PR TITLE
Admin define TEXT_IMAGE_NONEXISTENT missing in product.php

### PR DESCRIPTION
**Pull request by scottcwilson**
The products page in Admin->Catalog->Categories products needs this
define.

### CODE REVIEW

**Comment by drbyte** [comment]
For v156, okay.
For v2 we should consolidate this define into one place.

**Comment by scottcwilson** [comment]
@drbyte Do you want a wholesale de-duplication of admin defines in v2?  Or should I just handle this one?

**Comment by drbyte** [comment]
Just this one for now. If you want to create an Issue exposing the scope of duplication that currently exists in v2, we can talk there about which things to retain duplicates for (and why), etc.

**Comment by drbyte** [comment]
Given that there are 2 strings used in the duplicates for this current define, let's settle on one string, not multiple defines.
This seems to be the most common: 
`define('TEXT_IMAGE_NONEXISTENT', 'IMAGE DOES NOT EXIST');`

**Pull request merged**
