### PR TITLE
Correct 'table' shipping module PHP Warnings when rates are based on a percentage

### PR DESCRIPTION
**Pull request by lat9**
As reported in [this](https://www.zen-cart.com/showthread.php?230325-2-01-log-file-question&p=1403269) Zen Cart forum posting.

### CODE REVIEW

**Comment by scottcwilson** [comment]
@lat9 Doesn't `zones` also need this fix?

**Comment by scottcwilson** [comment]
Maybe low order fee too?

**Comment by lat9** [comment]
I don't know; if you're seeing such an issue, please fix it.  I just corrected what was reported on the forums.

**Comment by drbyte** [comment]
Done in b9ea5a8

**Pull request merged**
