### PR TITLE
Language inclusion requires slash before filename

### PR DESCRIPTION
**Pull request by scottcwilson**
Recommended for backport to 1.5.6

### CODE REVIEW

**Comment by scottcwilson** [comment]
Right now, order processing stops cold because of this issue.  My fix resolves that.  Yes I agree it would be even better to use proper template handling to fix this but that's not what 1.5.5-1.5.6 do - they just pull the file from the default language location.   Making this inclusion template sensitive would be a great 1.5.7 enhancement, but let's fix the main problem first right now.

**Comment by mc12345678** [comment]
Ummm, it wouldn't be a 1.5.7 "enhancement", it would be a restoration to operation as provided in 1.5.6 and 1.5.6a that was removed in 1.5.6b.
Zen Cart 1.5.6 original code:
````php
          // require the language file
          global $language_page_directory, $template_dir;
          if (!isset($language_page_directory)) $language_page_directory = DIR_WS_LANGUAGES . $_SESSION['language'] . '/';
          if (file_exists($language_page_directory . $template_dir . '/create_account.php')) {
            $template_dir_select = $template_dir . '/';
          } else {
            $template_dir_select = '';
          }
          require($language_page_directory . $template_dir_select . '/create_account.php');
````

**Comment by scottcwilson** [comment]
Yep you're right. Updated to include / in directory specifier.

**Comment by scottcwilson** [comment]
Recommended for backport INSTEAD OF #2442.

**Pull request merged**
