### PR TITLE
prevent empty ezpages links list from throwing warnings in PHP 7.2+

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
Clarification: you're just adding this for "completeness", not because it's actually still needed right?

Ref previous commit: https://github.com/zencart/zencart/commit/d8e60d70fd1f2a06171cea25192386f630f6edfa

**Comment by scottcwilson** [comment]
No, it's needed.  I got logs without it.

**Comment by drbyte** [comment]
Hmm, maybe it needs to be initialized as a double-nested array, given the context.  Argh.

Can you test the following adjustment to your PR?  Instead of `!empty && sizeof > 0`, just `!empty()` should suffice, since `empty()` correctly treats a "sizeof == 0" as empty.

**Comment by scottcwilson** [comment]
Yep - that works.

**Pull request merged**
