### PR TITLE
Cast float values before INSERT statement, just as ints are casted

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
Perhaps good for specificity, but @zcwilt isn't this redundant?

**Comment by drbyte** [comment]
Also, should be applied to other product types as well

**Comment by scottcwilson** [comment]
Yes - missed the music one.  That's the only other one.

**Comment by drbyte** [comment]
> What about casting to the other data types associated such as discussed at [13d204f#r41423083](https://github.com/zencart/zencart/commit/13d204fb44fdc06d42bbdba2323b8db2ced52d68#r41423083)

@zcwilt  ?

**Review by zcwilt — APPROVED** [review]

**Pull request merged**
