### PR TITLE
Remove php7 syntax

### LINKED ISSUE #3275: Remove PHP7+ syntax?
We are saying 1.5.7 can be used under PHP 5.6, but there are a couple of PHP7+ syntax statements.

admin/includes/functions/general.php line 2964 (zen_get_master_categories_pulldown declaration uses int hint).
admin/categories.php line 395 uses [] list unpacking.

### PR DESCRIPTION
**Pull request by torvista**
remove list unpacking from categories.php
closes #3275

### CODE REVIEW

**Comment by scottcwilson** [comment]
Steve, do you need to reset your fork so that you're current with 1.5.7?  It looks like you have somehow diverged so you have this large number of commits.

**Comment by torvista** [comment]
I dunno, this stuff comes from regularly merging zencart/v157 into my fork v157. Not sure what to do about this.

**Comment by scottcwilson** [comment]
branch

**Comment by scottcwilson** [comment]
That's what you want - get even with v157 then you'll have smaller merges.

**Comment by torvista** [comment]
I can't figure out how to get that "even": between rebase / fforward / merge on my local branch v157 then push to my origin, it always ends up with more commits on mine, from the updates.

**Comment by scottcwilson** [comment]
I wish I was confident in my ability to do this.

It's going to be SOMETHING LIKE: 

git fetch origin
git reset --hard origin/v157
git push --force

If you search StackOverflow for your symptoms, I'll bet you'll find an expert answer.

**Comment by drbyte** [comment]
I use Sourcetree for it, but I think the command-line equivalent is something like:
- `git checkout v157` to select my local v157 branch
- `git pull zencart v157 -r -v` (where "zencart" is the "remote" name I gave to the github repo, and "v157" is the branch I'm pulling from)

@scottcwilson Isn't this stuff all in the Dev Docs?

**Comment by scottcwilson** [comment]
This is kind of a weird case so the dev docs wouldn't address it.  This should really never happen, unless of course you're tired, distracted or multitasking. :)

**Comment by drbyte** [comment]
... or the local branch is in an odd state and needs a hard reset ... or delete the local repo and re-clone it

**Comment by torvista** [comment]
Done it.
GitKraken
Checkout remote upstream v157, to overwrite local v157.
Local now shows the extra/unwanted commits existing on the origin/v157 fork.
Push to origin: asks if you want to Force Push, accept. Done.

**Comment by zcwilt** [comment]
I do things slightly differently
upstream remote points to zencart/zencart 
origin points to zcwilt/zencart  (my fork)

so to update my v157 branch
git checkout v157
git fetch upstream v157
git merge upstream/v157 

create a feature branch

git checkout -b feature-branch 
do some work

if I need to update my feature branch with pr's that have been merged 
then first make sure all is commited
git checkout v157
git fetch upstream v157
git merge upstream/v157 
git checkout feature-branch 
git merge v157

within the feature branch
git push origin feature-branch
to get it to fork ready for PR

within the feature branch can also do 
git rebase -i v157  
if I want to squash up commits.

**Pull request closed without merging**
