### PR TITLE
Reference correct file.

### PR DESCRIPTION
**Pull request by mc12345678**

### CODE REVIEW

**Comment by scottcwilson** [comment]
The file https://www.zen-cart.com/docs/whatsnew_1.5.7.html needs to be re-deployed to the docs folder - the link is still wrong.

**Comment by mc12345678** [comment]
> The file https://www.zen-cart.com/docs/whatsnew_1.5.7.html needs to be re-deployed to the docs folder - the link is still wrong.
Huh? 1.5.7 doesn't align with the filenaming of other such documents where they are identified with dashes instead of periods. Yes it seems that there are additional changes that have been made that need to be captured in an updated version of the "what's changed" document. So what is the above saying?

**Comment by drbyte** [comment]
@mc12345678 Scott was just reporting that the changes to the .html file that were merged on github hadn't been deployed to the Zen Cart forum server yet.

I've just done that re-deployment of the file in the last 15 minutes. The links should now be working fine.

**Comment by mc12345678** [comment]
Thanks all. That is the kind of explanation I was trying to understand... 

Got it, mental note/communication to others in the know. :)

**Comment by scottcwilson** [comment]
Thanks guys.  This one is critical for upgraders, so I wanted to be sure it was working.

**Pull request merged**
