### PR TITLE
 zc_install - db install errors don't halt installer #528 

### LINKED ISSUE #528: zc_install - db install errors don't halt installer
In `zc_install`, when db errors occur during db setup (while it's executing various SQL scripts), the error message pops quickly and then proceeds to next page suddenly.

### PR DESCRIPTION
**Pull request by ebcode**
This fix causes the installer to abort if there is an SQL error during install.

Fixes #528

### CODE REVIEW

**Comment by drbyte** [comment]
👍 

Note: I added "Fixes #528" in the text of your Pull Request description, so that the #528 issue ticket will be automatically closed when this PR is merged.

**Comment by zcwilt** [comment]
:+1:

**Comment by ebcode** [comment]
Thanks, DrByte.  

Just let me know if there's anything you'd like me to change.  It occured to me that the line die('!') in  class.zcDatabaseInstaller.php could be replaced with something more explicit.

**Comment by drbyte** [comment]
> It occured to me that the line die('!') in class.zcDatabaseInstaller.php could be replaced with something more explicit.

True but it wouldn't display anywhere.
I suppose one could trigger a more detailed log message. But usually at this point something should already have been logged.

The code you submitted has now been merged, and is now part of v1.6.0.
Additional changes would have to be made via a new Pull Request (read the Contributing docs to learn how to update your local git from the github zencart copy, so that you have the latest to work with before starting any new PRs)

**Pull request merged**
