### PR TITLE
Cast $_SESSION[''languages_id] to an integer

### PR DESCRIPTION
**Pull request by Zen4All**
Since $_SESSION[''languages_id] can only be an integer, why not type cast it as one on creation.

---
This change is [Reviewable](https://reviewable.io/reviews/zencart/zencart/2877)

### CODE REVIEW

**Comment by drbyte** [comment]
In theory it should already be of the `integer` type because that's how it's stored in the db.
However, being explicit with this, particularly in the context of setting other related variables, reduces cognitive load and even helps IDEs. So I'm good with it.

**Comment by drbyte** [comment]
@Zen4All we stopped using Reviewable awhile back. Are you actively using it? Or is it just firing on your PRs because it's "leftover"?
If you're actively using it, that's fine. If not, feel free to unlink it from your repos.

**Comment by Zen4All** [comment]
> In theory it should already be of the `integer` type because that's how it's stored in the db.
> However, being explicit with this, particularly in the context of setting other related variables, reduces cognitive load and even helps IDEs. So I'm good with it.

Looking in the session data, it was set as a string,

**Comment by Zen4All** [comment]
> @Zen4All we stopped using Reviewable awhile back. Are you actively using it? Or is it just firing on your PRs because it's "leftover"?
> If you're actively using it, that's fine. If not, feel free to unlink it from your repos.

I have no idea, I do not use it. I'll see if I am linked somehow

**Pull request merged**
