### PR TITLE
get_uprid: Check for empty string is needed

### LINKED ISSUE #5452: zen_get_uprid returns a mixed (int|string) value, not a string
Having just spent the last hour trying to figure out why my code wasn't working ... a non-attributed product, when added to the cart, results in an (int) value being returned for an 'id' element of the `$_SESSION['cart']->get_products()` returned array.

Since its results can't be counted on as a string, as it's been that way forever, perhaps it's best to just update the function's definition to indicate that it returns `mixed`.

### PR DESCRIPTION
**Pull request by lat9**
Fixes #5452 (again)

### CODE REVIEW

**Comment by mc12345678** [comment]
So, as before, where is the description about why an already hashed value is to get hashed again? 

If one wants to intentionally rehash the value, shouldn't they have their own means to introduce the prid without the already existing `:`? In that way they have their own means to evaluate equivalency?

**Comment by lat9** [comment]
> So, as before, where is the description about why an already hashed value is to get hashed again?
> 
> If one wants to intentionally rehash the value, shouldn't they have their own means to introduce the prid without the already existing `:`? In that way they have their own means to evaluate equivalency?

If you'll note in the existing function that the string-checking clause would never have been reached.

The original check was for (a) not an array, (b) not empty and (c) not a string containing ':'.  Since a string containing ':' is not an array, that clause would never be executed and the code would (as now) go down the path where the input value is simply cast to a string and returned.

**Comment by mc12345678** [comment]
> > So, as before, where is the description about why an already hashed value is to get hashed again?
> > If one wants to intentionally rehash the value, shouldn't they have their own means to introduce the prid without the already existing `:`? In that way they have their own means to evaluate equivalency?
> 
> If you'll note in the existing function that the string-checking clause would never have been reached.
> 
> The original check was for (a) not an array, (b) not empty and (c) not a string containing ':'. Since a string containing ':' is not an array, that clause would never be executed and the code would (as now) go down the path where the input value is simply cast to a string and returned.

And you should note that the first two checks were against `$params`, the third check was against `$prid`. So, if `$params` was provided as an array having at least one element then the third item ***would*** have been encountered and processing stopped. The two changes proposed this far to make this function "simpler" still don't explain why that third check was removed.

**Comment by lat9** [comment]
Updated with commentary.

**Comment by lat9** [comment]
@mc12345678, what say ye?  Did I _finally_ get this right?  Thanks for keeping an eye out!

**Comment by mc12345678** [comment]
> @mc12345678, what say ye? Did I _finally_ get this right? Thanks for keeping an eye out!

Still considering the effects of the test `!== false`. 

Previously the "`$prid`" could begin with `:` such as removing the beginning integer part of the value and then feeding it into the function to get rehashed. An effort that seems controlled and purposeful. 

By eliminating that feature, the resulting hash will not be possible without revising the core code to restore that feature. 

Trying to see if that has been accidentally happening. e.g. that `$prid` may have been empty resulting in the hash beginning with `:` and not beginning with `0` or some other number. 

I mean, alternatively, if going to change the output of the function given equivalent input and no declared problem of the original output, shouldn't a new function be created? 

Another aspect that am investigating is related to the discussion about how strings are no longer treated as arrays. The implication of that concept is the perception that `is_array` of a string would have returned `true` in older php versions. The PHP library doesn't reflect a change in operation of that function for that purpose. But trying to run some tests to see if this function is now missing a conversion to retain operation.

**Comment by lat9** [comment]
The previous implementation used `strstr($prid, ':')` which would return `false` if there was no ':' in the submitted $prid or the substring of the submitted string starting at the ':' otherwise.  If any ':' was found in the $prid (at _any_ position), that portion of the clause would be 'truthy'.

As such, using the more performant `strpos($prid, ':') !== false` provides the same functionality.

**Comment by lat9** [comment]
@mc12345678, again waiting for your response.  This needs to be 'put to bed'.

**Pull request merged**
