### PR TITLE
Installer: separate files for language info data

### PR DESCRIPTION
**Pull request by zcwilt**
Use separate files for language info data to allow for easier adding of new languages

### CODE REVIEW

**Comment by zcwilt** [comment]
Note: 

The language info file need only be named `lng_info*.php` The actual file name is not used in code.

**Comment by torvista** [comment]
This isn't working for me (no langauge dropdown).
This is not returning the array.
$languagesInstalled = $languageManager->getLanguagesInstalled();

**Comment by torvista** [comment]
With the array added, the dropdown displays.
```
            $this->languagesInstalled = array_merge($this->languagesInstalled, $infoData);
        }
        return $this->languagesInstalled;
    }

```
But I can't get past the System Setup page (Continue has no effect).

**Comment by torvista** [comment]
In the next couple of days I should have the installer text for spanish back from being reviewed.
Is the intention to include installer texts in the distribution or with the language pack?

**Pull request merged**
