### PR TITLE
Add category description to notifier

### LINKED ISSUE #6467: index/category listing, final notifier for categories_description correct?
https://github.com/zencart/zencart/blob/198b15002b53a534fc9fbd3907415f4612ded6a7/includes/modules/pages/index/main_template_vars.php#L230-L235

I was looking at modifying the categories description and see this notifier is after the template is loaded/after the category description is used.

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #6467

### CODE REVIEW

**Comment by torvista** [comment]
Should not also $current_categories_description be removed from
$zco_notifier->notify('NOTIFY_HEADER_END_INDEX_MAIN_TEMPLATE_VARS', NULL, $current_categories_description);
since it has no effect if modified?

**Comment by scottcwilson** [comment]
No.  We want to avoid not-upwardly-compatible changes to notifers.

**Comment by torvista** [comment]
Understood as a general rule, but given a previous comment to make the function of a notifier self-explanatory, leaving this here implies it can be changed, when it can't, so it is misleading.

**Comment by scottcwilson** [comment]
It *can* be changed.  The change just won't show up in the template.  It could be used somewhere else, who knows.

**Comment by drbyte** [comment]
I wonder if the placement of the original notifier is the real problem here.
Yes, our standard practice is to leave most final notifier calls at the bottom of these header_php and main_template_vars files .... but in this sort of case where tpl_page_body is called manually (as is the case in all main_template_vars files), there's little point in the notifier hook coming after it. 
I haven't looked at the overall code-base to see how drastic this sort of pattern correction might be.

**Comment by scottcwilson** [comment]
Let's not overcorrect a non-problem based on a speculation.  The original issue is resolved.  Unless there's an actual problem with the last notifier, this should be sufficient.

**Pull request merged**
