### PR TITLE
Fix use of reserved words in query

### PR DESCRIPTION
**Pull request by scottcwilson**
Current query causes a SQL notice.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Here's the log:

[15-Apr-2020 16:16:52 America/New_York] Request URI: /gh_demo_157/admin/, IP address: ::1
#1  trigger_error() called at [/Users/scott/Sites/gh_demo_157/includes/classes/db/mysql/query_factory.php:171]
#2  queryFactory->show_error() called at [/Users/scott/Sites/gh_demo_157/includes/classes/db/mysql/query_factory.php:143]
#3  queryFactory->set_error() called at [/Users/scott/Sites/gh_demo_157/includes/classes/db/mysql/query_factory.php:227]
#4  queryFactory->Execute() called at [/Users/scott/Sites/gh_demo_157/admin/index_dashboard.php:529]
#5  require(/Users/scott/Sites/gh_demo_157/admin/index_dashboard.php) called at [/Users/scott/Sites/gh_demo_157/admin/home.php:26]
#6  require(/Users/scott/Sites/gh_demo_157/admin/home.php) called at [/Users/scott/Sites/gh_demo_157/admin/index.php:11]
--> PHP Fatal error: 1064:You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'option, opa.products_options_values AS value 
                      FROM orders' at line 1 :: SELECT op.products_quantity AS qty, op.products_name AS name, op.products_model AS model, opa.products_options AS option, opa.products_options_values AS value 
                      FROM orders_products op 
                      LEFT OUTER JOIN orders_products_attributes opa ON op.orders_products_id=opa.orders_products_id
                      WHERE op.orders_id = 1 ==> (as called by) /Users/scott/Sites/gh_demo_157/admin/index_dashboard.php on line 529 <== in /Users/scott/Sites/gh_demo_157/includes/classes/db/mysql/query_factory.php on line 171.

**Comment by drbyte** [comment]
let's call it `product_option` and `product_value`
and do the same adjustment in the `/admin/orders.php` file

**Comment by scottcwilson** [comment]
Please note that the products ordered bubble doesn't work yet either.

**Comment by drbyte** [comment]
> Please note that the products ordered bubble doesn't work yet either.

How do you mean?

**Comment by scottcwilson** [comment]
you can't click on it - it doesn't seem to do anything.  Also if you open up Chrome Inspect you'll see a jQuery error.

**Comment by scottcwilson** [comment]
Screen Shot 2020-04-15 at 4 50 03 PM

**Comment by scottcwilson** [comment]
go ahead and merge this fix though to get rid of the crashes on admin home and orders.  Then we'll worry about the next thing.

**Comment by drbyte** [comment]
Strange. It worked fine when I committed it.
Maybe it's the updated jQuery version.

The SQL errors are a limitation of MySQL that's not happening in MariaDB.

**Pull request merged**
