### PR TITLE
product_reviews_write header_php

### PR DESCRIPTION
**Pull request by mc12345678**
Initially began with correction to the check of a customer being logged in (strict processing) that led to other review considerations:
require of file not to use parentheses.
Potential of the products_id not being fed to access the page.
Refactoring for code alignment.
Remove else statements where the else action is simple. (assign a default value then modify if conditions warrant an alternate result).
Add notifiers to leverage options available.

### CODE REVIEW

**Comment by lat9** [comment]
The change on line 18 will allow guest-customers to write reviews; it that behavioral change intended?

**Comment by drbyte** [comment]
> The change on line 18 will allow guest-customers to write reviews; it that behavioral change intended?

Hmmm, probably not.

**Comment by mc12345678** [comment]
Wouldn't the notifier/observer allow control of that aspect where the plugin providing guest checkout would control the situation?

**Comment by lat9** [comment]
Nope, at least for One-Page-Checkout, the `zen_in_guest_checkout` simply identifies whether or not the customer is currently checking out as a guest.

**Comment by mc12345678** [comment]
So then what's the issue? The change offered the possibility of guest like software to permit writing reviews, but if there was no such software then the user would have to be logged in to write a review. Afterall, a review could be inserted into the checkout process following the use of One-Page-Checkout...

**Comment by lat9** [comment]
The OPC plugin offers two controls, one for pages allowed post-checkout and another for pages that are disallowed during guest-checkout.  Your addition of having the `product_reviews_write` page check for `in_guest_checkout` will make it so that current users of OPC that have allowed reviews for guests will have that functionality broken (since in-guest-checkout will be active on entry).

**Comment by lat9** [comment]
In short, I'm asking that the `zen_in_guest_checkout()` portion of the comparison be removed, to provide downward-compatible operation.

**Comment by drbyte** [comment]
That makes sense. Reviews aren't written "during checkout" anyway (er, reputable ones anyway).

**Comment by mc12345678** [comment]
Matter of perspective, *product* being reviewed, and what aspect of review is being sought. Besides that all could be done with just `zen_is_logged_in` instead of having/using two separate functions, so still not an issue for someone that wants to offer the additional capability.

**Pull request merged**
