### PR TITLE
Multi Language Country Names

### PR DESCRIPTION
**Pull request by Zen4All**
This was already implemented into ZC1.6, so I thought it would be a good idea to put it in ZC1.5.7 too.

---
This change is [Reviewable](https://reviewable.io/reviews/zencart/zencart/2789)

### CODE REVIEW

**Comment by lat9** [comment]
I'll note that this change, like the Multi-lingual EZ-Pages change to zc156, has the possibility of wrecking havoc with various plugins that (currently) pull the `countries::countries_name` directly from the database &mdash; One-Page Checkout and Edit Orders as examples.

I'm not suggesting that the change not be made, but I believe that changes like this need to be posted on the Zen Cart forums so that plugin 'owners' have a change to make modifications prior to zc157's release.

**Comment by lat9** [comment]
Are the `zones` going to be multi-lingual as well?

**Comment by Zen4All** [comment]
Was planning on doing the zones in a separate PR

**Comment by lat9** [comment]
Thanks, @Zen4All, that makes sense.

**Comment by drbyte** [comment]
The SQL for installing country names needs refactoring too, since it now involves 2 tables.

**Comment by Zen4All** [comment]
@drbyte The Zen Cart 1.6.0 installation contains three extra countries, What to do with those? (Saint-Barthélemy, Congo - Kinshasa, St. Martin)

**Comment by drbyte** [comment]
> @drbyte The Zen Cart 1.6.0 installation contains three extra countries, What to do with those? (Saint-Barthélemy, Congo - Kinshasa, St. Martin)

They should be included (assuming they're still relevant).

**Comment by drbyte** [comment]
I'm not loving the complexity this adds to everything. Hence the delay in merging.

**Comment by Zen4All** [comment]
No rush.
It is basically the same thing as added to 1.6.0, and the separate mod released for previous ZC versions.

**Comment by drbyte** [comment]
Given that "country" names, and their translations, are a "relatively" static set of data, would it make sense to have all that data housed in a text/json file (or PHP array), and skip all the db stuff altogether?

The master list of Zones would be covered too. (Store-specific geo-zones, which l link to shipping/taxes/payment-modules/etc would still need to be in DB, but don't require multilang support.)

Kinda goes back to #35 ... but fed from a static source (perhaps managed by a composer package).

**Comment by Zen4All** [comment]
That's fine with me

**Comment by torvista** [comment]
> Given that "country" names, and their translations, are a "relatively" static set of data, would it make sense to have all that data housed in a text/json file (or PHP array), and skip all the db stuff altogether?

Yes. Given my experience with Dolibarr. Or there will constant tinkering required. Having it external pushes it to the language pack.
Countries should be referenced to their ISO codes. IMHO.
Their provinces/districts whether geographical/political/historical/postal are a world of pain....not possible to always use iso codes.

**Comment by zcwilt** [comment]
Closing for now. Pull requests with `Status - On Hold' will be revisited after 157 release.

**Pull request closed without merging**
