### PR TITLE
add products options pulldown #4549

### PR DESCRIPTION
**Pull request by proseLA**
#4549 

in my limited experience, i have always felt this page is a little overwhelming.  i'm not sure if this makes it even more so.

in any event, you can see the process of creating a pulldown and how it could work.  the keyword searching does work for the pulldown.

### CODE REVIEW

**Comment by proseLA** [comment]
@scottcwilson i'm ready to close this PR unless you feel like you want it.  i have changes i would like to make to the method `addSearchKeywordForm` that make it more readily usable for other users/developers that decide to extend the abstract pulldown class (or use the existing two that already extend it).

**Comment by scottcwilson** [comment]
Sorry for the delay - I will take care of it this week.

**Comment by scottcwilson** [comment]
I don't get it.  You have added a search box to Admin > Catalog > Option Value Manager that reduces the number of items displayed in the Select Option Value to filter dropdown.   Can you provide more details about scenarios where this is helpful? 

I think Select Option Value to filter (added in 157) is enough, no?  When I wrote up #4549 I think I was looking at an old site and getting aggravated.

**Comment by torvista** [comment]
So this search in Values Manager, is actually filtering on Names.
Sure, not necessary if there are few names as the current dropdown filter suffices. 
But evidently there are site with many names, so if it is done and working, why not include it?

**Pull request merged**
