### PR TITLE
Fix direct inclusion of language files

### PR DESCRIPTION
**Pull request by scottcwilson**
Completion of work required by issue #4595; continues work started in PR #4583.

### CODE REVIEW

**Comment by torvista** [comment]
Also
https://github.com/zencart/zencart/blob/d5b78c13f4273757ac7ac47889f2b4a8aa311d2a/admin/orders.php#L514

**Comment by torvista** [comment]
and when the line in orders.php is updated, although the order details display correctly, there is a debug

> --> PHP Warning: Undefined variable $module_file in ...zencart-158\includes\functions\functions_files.php on line 72.

https://github.com/zencart/zencart/blob/d5b78c13f4273757ac7ac47889f2b4a8aa311d2a/includes/functions/functions_files.php#L72
I suspect the second instance of $module_file should be $lang_file.

**Comment by scottcwilson** [comment]
admin/orders.php issues fixed.

**Comment by torvista** [comment]
ok

**Pull request merged**
