### PR TITLE
Move fix from #1925/#1927 into v2

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by scottcwilson** [comment]
How do I run the unit tests?

**Comment by zcwilt** [comment]
It's the use of zen_field_length that is causing the problem, as that tries to access global $db
which isn't set in the tests. would need to do a simple mock here.

**Comment by zcwilt** [comment]
@scottcwilson  re tests
in the root of where you have files checked out on your computer you would need to do
``composer update``, assuming you have composer installed
then you should just be able to run 
``composer tests``

**Comment by scottcwilson** [comment]
Hmmm... in AdminLoggingTest.php line 110 I added 

`
        global $db;
        $db = $this->getMockBuilder('queryFactory')->getMock();
`

but get the same failure.

**Pull request merged**
