### PR TITLE
v158: Correcting various PHP Warnings/errors when "credit covers"

### LINKED ISSUE #4952: v158: Fatal error during checkout when paying fully with Gift Certificate
Load up a customer account with sufficient Gift Certificates/Vouchers to fully pay for an order.

Place one or more items into the cart and go to checkout.  On the `checkout_payment` page, enter the full order value in the "Use Gift Certificate" value input (or whatever it's called).

Upon pressing the continue button, you're met with a blank page, with resultant logs similar to the following
```
[30-Jun-2022 14:27:54 America/New_York] Request URI: /zc158/index.php?main_page=checkout_confirmation, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php(96): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined variable $payment_modules in C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php on line 96.

[30-Jun-2022 14:27:54 America/New_York] Request URI: /zc158/index.php?main_page=checkout_confirmation, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php(96): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Warning: Attempt to read property "modules" on null in C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php on line 96.

[30-Jun-2022 14:27:54 America/New_York] Request URI: /zc158/index.php?main_page=checkout_confirmation, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php(157): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined variable $ in C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php on line 157.

[30-Jun-2022 14:27:54 America/New_York] PHP Fatal error:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php:157
Stack trace:
#0 C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php(157): method_exists(NULL, 'alterShippingEd...')
#1 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
#2 {main}
  thrown in C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php on line 157

[30-Jun-2022 14:27:54 America/New_York] Request URI: /zc158/index.php?main_page=checkout_confirmation, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php:157
Stack trace:
#0 C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php(157): method_exists(NULL, 'alterShippingEd...')
#1 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
#2 {main}
  thrown in C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php on line 157.
```

### PR DESCRIPTION
**Pull request by lat9**
Fixes #4952

### CODE REVIEW

**Comment by torvista** [comment]
This appears to have broken the payment process...payment page to confirmation page gets redirected back to payment with an error to select a payment method.

**Comment by lat9** [comment]
> This appears to have broken the payment process...payment page to confirmation page gets redirected back to payment with an error to select a payment method.

I'm not seeing that on a vanilla zc158/responsive template test site.

**Comment by lat9** [comment]
I am, however, seeing a couple of PHP warnings that were not previously (er) covered:
```
[03-Jul-2022 10:16:06 America/New_York] Request URI: /zc158/index.php?main_page=checkout_confirmation, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\classes\order_total.php(185): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\pages\checkout_confirmation\header_php.php(72): order_total->pre_confirmation_check()
#2 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined array key "payment" in C:\xampp\htdocs\zc158\includes\classes\order_total.php on line 185.
```
and
```
[03-Jul-2022 10:16:21 America/New_York] Request URI: /zc158/index.php?main_page=checkout_process, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\classes\order.php(1259): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\checkout_process.php(110): order->send_order_email()
#2 C:\xampp\htdocs\zc158\includes\modules\pages\checkout_process\header_php.php(14): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined global variable $ in C:\xampp\htdocs\zc158\includes\classes\order.php on line 1259.
```
@torvista, are you using responsive_classic or some other template?  The `checkout_confirmation` page's `header_php.php` was significantly changed to gather defaults for various processing flags and values so that templates can just render the page without knowing the processing details.

**Comment by torvista** [comment]
I'm using the Github repository directly. Responsive classic. Strict reporting.
If I checkout the prior commit to this: ok.
If I checkout this commit: I don't get past the payment page, it gets redirected back with this error

>  Please select a payment method for your order.

and this debug.

> [03-Jul-2022 15:33:45 UTC] Request URI: /zencart/index.php?main_page=checkout_confirmation, IP address: 127.0.0.1
> #1  require(\includes\modules\pages\checkout_confirmation\header_php.php) called at [D:\GitHub\zencart\index.php:35]
> --> PHP Warning: Undefined variable $moneyorder in \includes\modules\pages\checkout_confirmation\header_php.php on line 87.

moneyorder is the only payment module enabled.

**Comment by lat9** [comment]
Does the 'customer' have a GC balance?

**Comment by lat9** [comment]
Never mind, I see the issue now.  Missed that path in my validation, since I was focusing on the credit-covers portion.

**Pull request merged**
