### PR TITLE
v158: Remove duplicate language file loads, performance improvement.

### PR DESCRIPTION
**Pull request by lat9**
... as seen in this load of the `create_account` page:
image

### CODE REVIEW

**Comment by scottcwilson** [comment]
The file matching for the array style language files had a bug - it didn't require an additional character after the page name for extra files in loadLanguageForView().  See if includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php has the same issue.

**Comment by lat9** [comment]
> The file matching for the array style language files had a bug - it didn't require an additional character after the page name for extra files in loadLanguageForView(). See if includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php has the same issue.

I don't understand the comment, please elaborate.

**Comment by scottcwilson** [comment]
Remove lang.create_account.php and copy in the old create_account.php.  (Not a template override, the base file.). Be sure it's not tried twice on includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php line 49 

Then do same check for template override on line 43. 

I suspect the listFilesFromDirectory calls should use `'(.+)\.php$~i'` not `'(.*)\.php$~i'`.

**Comment by scottcwilson** [comment]
Kick back to me if too confusing.

**Pull request merged**
