### PR TITLE
Function re-uses loop variables for inner and outer loop

### PR DESCRIPTION
**Pull request by scottcwilson**
- inner loop at line 282 - use different variables than are used on line 81.
- same at line 364 vs line 81.
This is not a true bug but someone could accidentally create one by not
being aware of the reuse.

### CODE REVIEW

**Comment by drbyte** [comment]
Ya, the re-use is harmless in this case, since `$key` from line 81 is never used anywhere later.

So, a simpler fix would be to just change line 81 and change `$key => $value` to just `$value`

**Comment by scottcwilson** [comment]
That makes no sense. You are still leaving one potential bug in place.  I have spent HOURS debugging issues with this very same root cause.

**Comment by drbyte** [comment]
I must not be understanding what you mean then. 

From what I can see:
- `$key` on 81 isn't being used purposefully anywhere, so is irrelevant. Dropping it from 81 adds some safety by removing ambiguity.
- `$key` on 282 is likewise not used; changing `$key => $val` to `$attachment` (and on subsequent lines) adds the safety by removing ambiguity. (I didn't suggest this one earlier, but should have.)
- the loop on 364 is really tiny, and perfectly suited for using `$key=>$val` ... and since $key and $val are no longer used above, there's no clash.

Or am I missing what you're trying to say?

**Comment by scottcwilson** [comment]
Oh I see - your comment earlier was not to use `$attachment` but just `$value`. 

screen shot 2016-09-04 at 2 51 19 am

So I'm ok with the line 282 change but can we keep my change to line 364, since this preserves the uniqueness of variables across the outer loop?  PR Updated.

**Comment by drbyte** [comment]
> but can we keep my change to line 364, since this preserves the uniqueness of variables across the outer loop? 

I had also meant to change line 81 (the outer loop) so that there would be no clash at 364

```diff
-     foreach(explode(',',$to_address) as $key=>$value) {
+     foreach(explode(',',$to_address) as $value) {
```

**Comment by scottcwilson** [comment]
Got it - thanks for clarifying.

**Comment by drbyte** [comment]
👍

**Comment by zcwilt** [comment]
:+1:

**Pull request merged**
