### PR TITLE
Enable site-specific admin .css customizations

### LINKED ISSUE #5583: Admin:  No way for a site to provide overall styling customizations
While the `/admin/includes/admin_html_head.php` provides a means to provide page-by-page styling overrides, there's no way for a site (without carving up 'core' `.css` files) to provide overall styling changes for their admin.

I propose that the above module look for `/admin/includes/css/site-specific-stylesheet.css` and, if present, include that just after the main `stylesheet.css` is loaded.

### PR DESCRIPTION
**Pull request by lat9**
Fixes #5583

### CODE REVIEW

**Comment by scottcwilson** [comment]
Love it!  But should we not provide a dist-includes/css/site-specific-stylesheet.css as we did in other cases?

**Comment by torvista** [comment]
I would suggest the use-case for this would be users not liking something. That "something" could be in various css, depending on the page/mods etc., so I would have it as the last-loaded css.

**Comment by lat9** [comment]
> Love it! But should we not provide an `admin/includes/css/dist-site-specific-stylesheet.css` as we did in other cases?

... and, perhaps, changing it to have a `.php` extension, so that the styling could have programmatic modifications?

**Comment by scottcwilson** [comment]
Good idea.

**Comment by scottcwilson** [comment]
Good point.  I will create a stub: 

https://docs.zen-cart.com/user/customizing/admin_customizing/

**Comment by lat9** [comment]
Document link added to commentary.

**Comment by scottcwilson** [comment]
Docs updated.  Thanks for doing this.

**Pull request merged**
