### PR TITLE
v158: Adding `zen_define_default`.

### LINKED ISSUE #4825: New function to set a define's default if not already defined
this section of code is something new in v158 in that we are checking if the config key is already defined:

https://github.com/zencart/zencart/blob/5ab07980bdd846ce174ad976456686a339ecf1f5/laravel/app/Models/Configuration.php#L29-L31

looking in v157, we see we do not have that check:

https://github.com/zencart/zencart/blob/742b837868a2b128df96b6635c413c8187972679/includes/init_includes/init_db_config_read.php#L23-L27

in seeing all of the php 8.0 notices for already defined constants, i think it would behoove us to provide an early loading function to do this.  ie, something like:

```
        function defineIfNot(string $name, string $definition)
        {
            if (!defined($name)) {
                define($name, $definition);
            }
        }
```
i see potential for plenty of uses as store owners move to php 8.0 and are inundated with log files.

thoughts?

noted, that i have the declared variable arguments as both strings and in some instances integer is required.  also noting that i WOULD love to refactor all of those boolean strings into actual booleans... and noting that will never happen.  a coder can dream...

### PR DESCRIPTION
**Pull request by lat9**
Fixes #4825

### CODE REVIEW

**Comment by scottcwilson** [comment]
@lat9 @proseLA Would you please write up a trivial use case for me to show in the documentation?

**Comment by lat9** [comment]
> @lat9 @proseLA Would you please write up a trivial use case for me to show in the documentation?

It's used in /admin/application_bootstrap.php on line#145 to set the default definition of `DIR_WS_TEMPLATES` to `DIR_WS_INCLUDES . 'templates/'`:
```
zen_define_default('DIR_WS_TEMPLATES', DIR_WS_INCLUDES . 'templates/');
```

**Comment by lat9** [comment]
It's just a readability 'helper', a one-liner function instead of
```
if (!defined('DIR_WS_TEMPLATES')) {
    define('DIR_WS_TEMPLATES', DIR_WS_INCLUDES . 'templates/');
}
```

**Comment by scottcwilson** [comment]
OK it looks fine but why a new function file? Wouldn't it fit into an existing file?

**Pull request merged**
