### PR TITLE
deduction is  needed by local sales tax mod

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by lat9** [comment]
I've got no clients that use that mod, in what manner does the "Local Sales Tax" _need_ access to that value?

**Comment by scottcwilson** [comment]
I reduce the tax by the amount of tax that would have been charged on the discount.  (So the local tax is charged on the subtotal less discounts.)

**Comment by lat9** [comment]
Noting that this change should also be applied to the 2.0.x branch; that variable's defined as `protected` there, too.

**Comment by scottcwilson** [comment]
Yep, sorry, fat fingered the destination.

**Comment by lat9** [comment]
One more (I promise!) comment: This change is required due to the changes introduced [here](https://github.com/zencart/zencart/commit/c8ca5b03f856e70b3922f82e15f1c065e56a7894) to pre-define all class variables in zc158.

**Comment by scottcwilson** [comment]
Yes!  The specification of visibility is a new thing and we're figuring it out as we go.

**Pull request merged**
