### PR TITLE
Upgrade Jquery to 3.5.0

### PR DESCRIPTION
**Pull request by Zen4All**
Since the front end is updated, the back-end should be as well

### CODE REVIEW

**Comment by scottcwilson** [comment]
Admin was backed down to 3.4.1. https://github.com/zencart/zencart/commit/9dcef7f4149a9a1509d594acd88f09e57fcb1901

**Comment by scottcwilson** [comment]
Should we defer this for now?  Would templates that use Bootstrap be harmed by this change?

**Comment by drbyte** [comment]
Templates?

**Comment by wiztechinc** [comment]
staying with the most recent version of jquery always impacts templates. I just recently found a image pop up that can use 3.4.  If anyone has done anything different than the responsive, it's always going to be an issue when updating.

**Comment by drbyte** [comment]
@Zen4All when they release 3.5.1 and it's confirmed to work with BS 3, please either update this PR (amend it and force-push) or open a new one.
Thanks!

**Comment by Zen4All** [comment]
Closing this or, and will make a new one in the future.

**Comment by Zen4All** [comment]
Jquery 3.5.1 is released. Will do some testing today

**Pull request closed without merging**
