### PR TITLE
Make admin HTML5 compliant

### PR DESCRIPTION
**Pull request by brittainmark**
I have reworked admin to be html5 compliant and fixed a number of errors
in the code. see below for details.

# general changes:
correct labels to point at id
add table role="listbox"
change/add tr onclick role to "option" and add aria_selected
Change name to id in a tag
remove width and replace with css from \<table>, \<tr>, \<th>,\< td>
replace \<tt> tag  with \<span class="tt">
replace align with css "text-..." in table elements
changed doctype
remove valign from table elements and replace with css where necessary
remove \<button> tag from inside <\a> tags and add css as appropriate

#  specific changes
## admin/coupon_admin.php
fix missing closing tags
fix php warning missing array element 'uid'
move hidden form fields out of table element

## admin/coupon_admin_export.php
add parameters to redirect to prevent php undefined variables
removed extra table tr td with no closing elements
remove incorrect colspan

## admin/coupon_restrict.php
Added column headings to prevent html error table column not used.

## admin/customer_groups.php
added missing spaces before class

## admin/developers_tool_kit.php
created function to output page head so always written first
added action to variables to make unique
added htmlspecialchars so output does not contain html tags
added additional css

## admin/featured.php
added missing space before class

## admin/group_pricing.php
added missing space before class

## admin/gv_mail.php
corrected position of \</form>

## admin/gv_sent.php
changed !isset to empty to remove php warning

## admin/includes/functions/general.php
use new zen_make_id function to create valid id. correct issue with
spaces in id.

## admin/includes/functions/html_output.php
Change zen_image width and height to be style
Change zen_black_line to use $width instead of style in $parameter
Change zen_draw_seperator to use new zen_draw_image
Change zen_draw_input_field to add id = to name if no id present in $parameters
Change zen_draw_password_field to replace autocomplete with 'off' if in $parameters and $autocomplete is false
Change zen_draw_checkbox_field to add id = to name if no id present in $parameters
Change zen_draw_textarea_field to use style if $width is not numeric and default to 100%
Change zen_draw_pull_down_menu to add id = to name if no id present in $parameters
Change zen_draw_label to not output 'for' if $for is empty
Change zen_draw_date_selector to add id = to name if no id present in $parameters
Added new function zen_make_id to make a valid id field

## admin/includes/modules/copy_product.php
Change to use new zen_image format

## admin/includes/modules/.../collect_info.php
correct inputtype to inputmode

## admin/includes/modules/.../collect_info_metatags.php
change div to fieldset and labes to legend for html5 compliance
added missing space before class

## admin/includes/modules/product_music/copy_product.php
Change to use new zen_image format

## admin/mail.php
add calling parameters so user details are not forgotten on change of editor
add missing \</form> and \</div>

## admin/media_manager.php
remove mouseover and mouse out as javascript rowOutEffect not loaded (also only worked on ever other row if manually loaded)
rewrote action edit to create valid html for form 
added missing &page to buttons
checked empty $product_array to prevent php missing variable warning

## admin/media_types.php
remove ->fields to correct media_type

## admin/music_genre.php
set $_GET['mID'] when not set to prevent all rows being shown as selected

## admin/option_name.php
change column spacing use css and adjust colspan
add table to hold form info
move \</form> to correct location

## admin/options_values_manager.php
add css column widths
add table to hold form data
always output heading to prevent Html unneeded columns error
remove unnecessary colspan
rework dropdown fields to create individual id's. Note require future
rework to id's can be removed from $parameters

## admin/orders.php
change to use new zen_image instead of style in parameters

## admin/popup_image.php
change doctype and remove Netscape from resize

## admin/salemaker.php
remove spiffyCal and use html input type date
move draw form so sits correctly in divs
add alt to images

## admin/salemaker_popup.php
add missing space

## admin/server_info.php
clean up html from phpinfo (note there is still a missing \<td>)
add htmlspecialchars to output database values

## admin/sqlpatch.php
use admin_html_head.php instead of manual loading

## admin/stats_customers_referrals.php
add missing \</button> tag

# created new css files
admin/includes/css/coupon_admin_export.css
admin/includes/css/media_manager.css

### CODE REVIEW

**Comment by torvista** [comment]
Well that's a lot of effort you have put in, I hope you don't get discouraged when someone starts complaining about too much stuff in one PR.
However it **is** too much stuff in one PR. It discourages peer review as no-one has the time to check all those files one by one for different changes, and you have mixed simple html changes with some code modifications and code additions which really should be separate PRs so they can be reviewed/argued about separately too.
Modifications to **multiple** files should really be the exact same modification.
Even multiple modifications to a **single** file seem to be frowned on, unless they are all no-brainers that do not effect functionality.
In the past I've been scolded for modifying files that were not ostensibly broken in any way/not correcting a specific issue, but that seem to have been relaxed recently with PRs for just formatting.
The more minor the PR, the more chance it gets reviewed and merged immediately and does not linger in limbo forever, which is what you want.

**Comment by brittainmark** [comment]
NO completely understand. I thought that his was what was wanted after the request for a pr for html5 #5011 for the default template. It's so easy to assume and get it wrong.
How would you suggest I split it down. 
While the current code it works, a lot of it is not valid html5. Producing errors when puth through the w3c nu validator.

I  could start with html_output.php as I think that is key.
Then break it down in to the same type of changes like adding role to table and changing row to option.
Add missing spaces before class etc.
Is that the approach you suggest. 

Also, as I have all the changes I assume you also do not want 40 pr's now, 
As I think that would be about the required number.

As for a justification. I think It would reflect better on zen cart if it was as html 5 compliant as possible.

**Comment by brittainmark** [comment]
Can you mark this as do not merge! But keep it, as it is a useful check for me while splitting into smaller pieces.

**Comment by torvista** [comment]
I think you can mark it as draft, which prevents merging.

**Comment by brittainmark** [comment]
Not sure I have that ability. Still learning GitHub. Any pointers as to how?

**Comment by torvista** [comment]
Clipboard01

**Comment by brittainmark** [comment]
thanks, @torvista spent 10 mins looking for that

**Comment by scottcwilson** [comment]
Does it make sense to close this one since there are so many merge conflicts?  PRs with huge numbers of files are really hard to digest.

**Pull request closed without merging**
