### PR TITLE
Exit foreach upon result found

### PR DESCRIPTION
**Pull request by mc12345678**
While looking over code, came across this loop where a value is
set and it appears that there is no further need to loop.
This breaks out of the foreach upon result discovery.

### CODE REVIEW

**Comment by drbyte** [comment]
If we're gonna touch this function, perhaps the use of `$retVal` can be deleted, and just return true as soon as a match is found?

**Comment by mc12345678** [comment]
Had considered it, but didn't want to grossly change it if someone had some reason to override/modify...  That said, I'll propose it anyways, there appear to be many that are at least looking over these and providing some sort of comment. :)

**Comment by drbyte** [comment]
Don't need to check EOF. The foreach immediately aborts if it's empty.

**Comment by mc12345678** [comment]
Thought I remembered seeing/finding a situation where `false` would get returned instead of an empty array so went overboard with validation... :) Corrected by force pushing that particular commit.

**Pull request merged**
