### PR TITLE
Update mysql_zencart.sql

### PR DESCRIPTION
**Pull request by dbltoe**
Changing the title of this wide banner may increase exposure to certified services and increase affiliate returns.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Not a bad idea but why not do `zc_install/sql/updates/mysql_upgrade_zencart_158.sql` as well?

**Comment by dbltoe** [comment]
Good Point

**Comment by scottcwilson** [comment]
Correct.  Add an update.  
When we update the create script, it's good to also put an update into the current database upgrade script.

**Comment by scottcwilson** [comment]
See #4927 for upgrade script change.

**Comment by scottcwilson** [comment]
This is fine but next time please put both in the same PR, then it's obvious that you have done both.

**Comment by dbltoe** [comment]
Well, this grasshopper has yet to figure out the process of combining or I would have.

Will try to find time to figure it out.

**Pull request merged**
