### PR TITLE
Review pages should not pull a substring of review text

### PR DESCRIPTION
**Pull request by scottcwilson**
... not arbitrary hardcoded number.

### CODE REVIEW

**Comment by lat9** [comment]
Er, the `MAX_PREVIEW` constant has absolutely nothing to do with reviews.

**Comment by scottcwilson** [comment]
Look at the review template files: 

includes/templates/responsive_classic/templates/tpl_reviews_default.php
includes/templates/responsive_classic/templates/tpl_product_reviews_default.php
includes/templates/template_default/templates/tpl_reviews_default.php
includes/templates/template_default/templates/tpl_product_reviews_default.php

They all reference that constant.  We should respect this when retrieving the data.

**Comment by scottcwilson** [comment]
I am open to removing the `left` call entirely from the query and allowing the template to decide how much to show if you think that's a better solution.

**Review by brittainmark — APPROVED** [review]
good spot!

**Comment by lat9** [comment]
> Look at the review template files:
> 
> includes/templates/responsive_classic/templates/tpl_reviews_default.php includes/templates/responsive_classic/templates/tpl_product_reviews_default.php includes/templates/template_default/templates/tpl_reviews_default.php includes/templates/template_default/templates/tpl_product_reviews_default.php
> 
> They all reference that constant. We should respect this when retrieving the data.

All those template-references use `zen_trunc_string`, e.g.
```php
zen_trunc_string(nl2br(zen_output_string_protected(stripslashes($reviews->fields['reviews_text']))), MAX_PREVIEW);
```

... and that function's a bit smarter than just a 'truncate-after-some-number-of-characters' like the SQL query's going to be.  I'd almost be more comfortable losing the text-related limitation in the SQL query instead.

**Comment by scottcwilson** [comment]
I think you're right.  Why do it twice!  Let's let the template decide.   Coming right up.

**Comment by lat9** [comment]
Were you going to change that query to use a JOIN as @brittainmark suggested?

**Comment by scottcwilson** [comment]
I'd like to just make this one small change now and wrap this up.

**Comment by lat9** [comment]
Should we create a to-do list?  There have been a couple other changes that would be 'good' that have also been shelved.

**Comment by scottcwilson** [comment]
A todo list is always a good idea to get a shared understanding.

**Pull request merged**
