### PR TITLE
admin, orders: fix for adding string to number

### PR DESCRIPTION
**Pull request by torvista**
whitespace too.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Can you be more specific about what this fixes?

**Comment by torvista** [comment]
This should be a sum.
zen_date_diff is a float, DOWNLOAD_MAX_DAYS is a string.

**Comment by mc12345678** [comment]
FYI, have a similar issue with: https://github.com/zencart/zencart/blob/b0b560f603f3b04d3efc3409a36805b7bac7c6aa/admin/orders.php#L199

Database result comes back as a string, date difference is numeric. 

Considering what is addressed through the concern of this PR, similar code uses should be evaluated. I found this by looking at how `products_attributes_maxdays` is used. I did the search in Github which means the results are limited and there may be other places to consider. A search in the Developers Tool Kit would be more exhaustive.

**Comment by mc12345678** [comment]
What's the reasoning behind using `intval` instead of casting with `(int)`?

**Comment by torvista** [comment]
After reading a bit more, none.

**Pull request merged**
