### PR TITLE
Fix PHP Array Warning

### PR DESCRIPTION
**Pull request by jaywilliams**
PHP Warning: Invalid argument supplied for foreach() in /admin/includes/header.php on line 77.

### CODE REVIEW

**Comment by drbyte** [comment]
Odd.

`file()` always returns an array of the file contents. 
Unless the file doesn't exist ... but we're only running that section of code if we first confirm the file exists.

So ... that begs the question: what circumstance caused it to not return an array? ie: how can we re-trigger the problem?

I don't think casting this to an array is the best solution: I'd rather get to the real root cause.

You could remove the `@` from `@file()` to get more specific details, if you're not sure what was originally actually causing the problem. In fact, I'd like to see the output that generates.

**Comment by jaywilliams** [comment]
On my install, the file _did_ exist, so it passed the `file_exists()` check, but the permissions were set which didn't allow reading by the PHP process (600), this caused `file()` to return *FALSE*, which PHP doesn't want to iterate over.

**Comment by drbyte** [comment]
Okay, fair. 

Why are permissions set to `600`? That doesn't seem like a normal workflow. Is this something you've been doing regularly? If so, why? It would seem that doing that to most files would cripple a typical PHP application.
Seeking to understand how this situation came to be, to understand how "common" this is (never saw this reported by other ZC users before, but older PHP versions weren't always so verbose either), in order to ensure the best fix is implemented.

**Comment by jaywilliams** [comment]
I don't think it's very common, I simply extracted the latest release zip file from the ZenCart website, so it would have whatever default permissions were set, but I figured it may be worth correcting. Either way I corrected it on my end, as I don't like seeing regular warning/errors if I can fix them.

**Pull request merged**
