### PR TITLE
Correct sanitization of UPLOAD_FILENAME_EXTENSIONS

### PR DESCRIPTION
**Pull request by lat9**
... as introduced in #2471 and reported [here](https://www.zen-cart.com/showthread.php?225748-File-Upload-Attribute-not-working-in-v1-5-6c&p=1360358#post1360358) on the Zen Cart forums.

### CODE REVIEW

**Comment by lat9** [comment]
Backport suggested.

**Comment by mc12345678** [comment]
What about the associated val_function and error message that now also is wrong and will try to force the entry/change of that option to be an integer?

**Comment by lat9** [comment]
Nice catch!  Are you going to submit a follow-on PR?

**Comment by mc12345678** [comment]
Can, though thought it would be more complete by being a part of this pull (understanding that it is now incorporated and closed).

**Comment by lat9** [comment]
... and I've deleted my branch, so go for it!

**Comment by mc12345678** [comment]
Looks like some "logic" was considered in setting up the val_functions for items in min/max as provided in PR #2267.  Ie. Non-numeric values were skipped, at least this one was.  So, there is no correction needed as a result of the change in this PR.  If anything a final resolution would be needed to provide some level of sanitization other than the default.

Thanks for entertaining. :)

**Pull request merged**
