### PR TITLE
Auto detect text files and perform LF normalization

### PR DESCRIPTION
**Pull request by Zen4All**
This will update edited files to lf line endings.

---
This change is [Reviewable](https://reviewable.io/reviews/zencart/zencart/2363)

### CODE REVIEW

**Comment by drbyte** [comment]
not at this time

**Comment by Zen4All** [comment]
You can leave it open and merge it at a later time. This was not specifically meant for 1.5.6.

**Comment by drbyte** [comment]
Ya, may re-open for merging in a future release.

I do like the idea. Just trying to balance the timing vs upgrade pain.

**Comment by Zen4All** [comment]
👍

**Pull request closed without merging**
