### PR TITLE
Coupon Popup link on checkout success page does not work

### PR DESCRIPTION
**Pull request by scottcwilson**
Missing javascript.  Checkout with a coupon and you'll see the link on the checkout success page gives a JS error.

### CODE REVIEW

**Comment by drbyte** [comment]
Should we just be stripping out the link instead?

**Comment by scottcwilson** [comment]
I'd say leave it - could be useful, plus older templates will have this.

**Comment by drbyte** [comment]
Did I miss seeing reports of this being a problem in 1.5.6 ?

**Comment by scottcwilson** [comment]
I don't know if it was an issue in 1.5.6.  I just found this in today's 1.5.7 testing when I updated my store.

**Comment by drbyte** [comment]
Should this invoke the entire popup? Or just provide an empty JS function to avoid the error?
Also, why the commented-out-code?

**Comment by scottcwilson** [comment]
The commented out code should be fixed - I think I may have just pulled this file from a prior release.  
I prefer to do the full popup so people can use this function, which is likely in a number of templates.

**Comment by scottcwilson** [comment]
The commented out code should be fixed - I think I may have just pulled this file from a prior release.  
I prefer to do the full popup so people can use this function, which is likely in a number of templates.

**Pull request merged**
