### PR TITLE
PHP8.2 Define Parameters papyal_curl

### PR DESCRIPTION
**Pull request by brittainmark**
Set to public
-  $_endpoints
-  $_logDir
-  $_logLevel
-  $_mode
-  $_trxtype
-  $lastParamList

Set to protected
-  $_curlOptions
-  $_partner
-  $_pwd
-  $_server
-  $_signature
-  $_user
-  $_vendor
-  $_version
-  $lastHeaders
-  $values

Defined as protected
-  $outputDestination;

**NB.** This class has a function setParam($name, $value) which is not used that will cause undefined warnings if it is use for any parameters not in list above

### CODE REVIEW

**Comment by scottcwilson** [comment]
@brittainmark How close are you to completing?  We'd like to have a release build ready soon.

**Comment by brittainmark** [comment]
@scottcwilson this is what is left to do
includes/modules/payment/paypal.php:
includes/modules/payment/paypaldp.php:
includes/modules/payment/paypaldp.php:
includes/modules/payment/paypalwpp.php:
includes/modules/payment/square_support/ZenCartConnectCreatePaymentRequest.php:
zc_install/includes/classes/class.systemChecker.php:
zc_install/includes/classes/class.zcConfigureFileReader.php:
zc_install/includes/classes/class.zcConfigureFileWriter.php:
zc_install/includes/classes/class.zcDatabaseInstaller.php:
zc_install/includes/classes/class.zcRegistry.php:
zc_install/includes/classes/LanguageManager.php:
and 
includes/modules/payment/square.php if you want to get rid of the admin warnings. This is the old module.

I can get them done quickly if you are happy for me not to test them!
paypalwpp is still reliant on @lat9 I think there are still some outstanding issued raised by @torvista

**Comment by torvista** [comment]
> paypalwpp is still reliant on @lat9 I think there are still some outstanding issued raised by @torvista

I have some snippets in my production paypalwpp added to prevent occasional (rare) debug logs due to missing data not returned by paypal. Since they do not affect processing I think it would be prudent to add them now as they are the result of a production site.

**Comment by scottcwilson** [comment]
If we could get them wrapped up this week I'd love to get a candidate release build done on 10/16.

**Pull request merged**
