### PR TITLE
Improve appearance of configuration group 6

### PR DESCRIPTION
**Pull request by scottcwilson**
These values are really hard to understand out of content - adding prefixes showing where they came from.  Inspired by thinking about #3293.

### CODE REVIEW

**Comment by drbyte** [comment]
- not sure I like calling this "page 6". Page? Maybe "configuration group"
- not sure I want to do this at all
- got a screenshot of before/after?

**Comment by scottcwilson** [comment]
See screenies: 

before
after

**Comment by scottcwilson** [comment]
I wouldn't say it "encourages" the use of the page - I'd say it makes the page more comprehensible to anyone who wants to use it.   It would definitely be a good idea if you want to move forward on Steve's suggestion in #3293.

**Comment by torvista** [comment]
I think the fact that these constants get displayed at all is just incidental. They are not really for human consumption....if some are/are of use, they should be on another user-accessible page. Otherwise, I don't think anyone would expect to them be prettified at all.
In my opinion, of course!

**Comment by Zen4All** [comment]
I think group 6 should only be available for people who really know what they are doing.
I have not looked at the new code, but I have no clue what you are trying to display/explain in the second image.

**Comment by scottcwilson** [comment]
It just expands the configuration title string to give it some context.  Instead of saying "Tax Class" it shows that this is the Tax Class for the Per Item shipping method, for example.

**Comment by Zen4All** [comment]
OK, thanks for the explanaition :relaxed:

**Comment by drbyte** [comment]
Sentiment appreciated, but I'm not sure I want this. Closing for now.

**Pull request closed without merging**
