### PR TITLE
Add lazy loading (new feature in Chrome)

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
Given that I've seen some glitches with this done elsewhere (in apps even simpler than the extra markup handling that Zen Cart offers), I'd like to ensure some thorough testing has been done across various browsers, to ensure that in a Zen Cart setup this doesn't cause any unexpected outcomes.

**Comment by scottcwilson** [comment]
Sounds good.  We can also sit tight for a while - this is brand new.

**Comment by barco57** [comment]
I can say it does seem premature as even with chrome this is hidden behind a flag
https://caniuse.com/#feat=loading-lazy-attr

**Comment by drbyte** [comment]
Closing for now. We can reopen it when the feature is more widely embraced.

**Pull request closed without merging**
