### PR TITLE
v158: Order w/ attributes, coerce possibly `null` values to empty string

### LINKED ISSUE #4968: PHP Deprecation during checkout with attributed products, due to `NULL` fields
A PHP Deprecated log is created during storefront processing when an order is placed for an attributed product that doesn't have any quantity-discounts applied (think the demo product "A Bug's Life "Multi Pak" Special 2003 Collectors Edition"), since `products_attributes::attributes_qty_prices` and `products_attributes::attributes_qty_prices_onetime` are (by default) NULL:
```
[01-Jul-2022 10:35:14 America/New_York] Request URI: /zc158/index.php?main_page=checkout_process, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php(175): mysqli_real_escape_string()
#2 C:\xampp\htdocs\zc158\includes\functions\database.php(104): queryFactory->prepare_input()
#3 C:\xampp\htdocs\zc158\includes\classes\order.php(1079): zen_db_perform()
#4 C:\xampp\htdocs\zc158\includes\modules\checkout_process.php(99): order->create_add_products()
#5 C:\xampp\htdocs\zc158\includes\modules\pages\checkout_process\header_php.php(14): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: mysqli_real_escape_string(): Passing null to parameter #2 ($string) of type string is deprecated in C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php on line 175.
```

Separating out from #4963.

### PR DESCRIPTION
**Pull request by lat9**
Fixes #4968

### CODE REVIEW

**Comment by scottcwilson** [comment]
Good thinking but one question: should this be done above line 1068 so it sticks out more?

**Comment by lat9** [comment]
> Good thinking but one question: should this be done above line 1068 so it sticks out more?

I'm not sure what you're requesting.  Perhaps adding a comment to lines 1068 and 1069 to indicate that the fields might be `null` when copied?

**Comment by scottcwilson** [comment]
```
// Watch out for potentially null fields
$attributes_qty_prices = ($attributes_values->fields['attributes_qty_prices'] ?? '');
$attributes_qty_prices_onetime = ($attributes_values->fields['attributes_qty_prices_onetime'] ?? '');

$sql_data_array = [ 
... 

   $attributes_values->fields['attributes_qty_prices'] => $attributes_qty_prices,  
   'attributes_qty_prices_onetime' => $attributes_qty_prices_onetime, 


```

**Comment by scottcwilson** [comment]
This kind of thing is done, for example, in admin/includes/modules/update_product.php line 27

**Comment by scottcwilson** [comment]
You could even update in place: 

```
$attributes_values->fields['attributes_qty_prices'] = ($attributes_values->fields['attributes_qty_prices'] ?? '');
$attributes_values->fields['attributes_qty_prices_onetime'] = ($attributes_values->fields['attributes_qty_prices_onetime'] ?? '');

```

**Comment by scottcwilson** [comment]
I just find having logic within an array declaration makes it that much harder to read.

**Comment by scottcwilson** [comment]
That comment block is great too - thanks for doing that.

**Pull request merged**
