### PR TITLE
Change Load Point to 200

### PR DESCRIPTION
**Pull request by brittainmark**
To conform with the latest load point recommendation, move the load point to 200. 
Change array to []

### CODE REVIEW

**Comment by lat9** [comment]
What's the problem being solved here?

**Comment by brittainmark** [comment]
The module was used as an example for the documentation. I was bringing it in line with the desire for observers to start at 200 not 190. Don't think required any more as the docs have been changed to us a fictious example.

**Comment by lat9** [comment]
I'll note, too, that the load point for an observer depends (er) on what it's observing.  For instance, if an observer is watching for additions/removals from the cart, it should load prior to load-point 140 (where `init_cart_handler.php`) does that processing.

**Comment by scottcwilson** [comment]
I will add this guidance.  Thanks for mentioning it.

**Comment by scottcwilson** [comment]
It's already there.
https://docs.zen-cart.com/dev/code/notifiers/#choosing-when-to-load-an-observer

**Comment by lat9** [comment]
> It's already there. https://docs.zen-cart.com/dev/code/notifiers/#choosing-when-to-load-an-observer

Well ... there's a heading with one sentence.  An example (like above) would provide a tad more help.

**Comment by scottcwilson** [comment]
Cindy, can you give me a good example from one of your plugins to use on 
https://docs.zen-cart.com/dev/code/notifiers/#choosing-when-to-load-an-observer

Actually same request for 
https://docs.zen-cart.com/dev/code/notifiers/#manually-loaded-observers

**Comment by lat9** [comment]
Sure, give me a day or so and I'll hunt something up

**Pull request closed without merging**
