### PR TITLE
Issue 5823 dep consolidation

### PR DESCRIPTION
**Pull request by neekfenwick**
Suggested change to remove obsolete `admin/includes/stylesheet.css`, which has been replaced by `admin_html_head.php` and its specific `<link>` elements including `admin/includes/css/stylesheet.css`.

Also it seems the old `admin/includes/menu.js` and `menu.css` are obsolete, with the JS completely removed and CSS moved to `admin/includes/css/menu.css`, so I've removed the old files too.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Re: removing `admin/includes/stylesheet.css`, `admin/includes/menu.js` and `admin/menu.css`: 
Please don't do this.  This would break older plugins that haven't been updated.  
Perhaps an update to these files with a comment at the top saying DEPRECATED or something like that to make it super obvious. 

Re: Modlist changes: 
Please back these changes out.  We don't want to change old versions.  I will replace with an update that removes references to the old files. 
I will update ModList so that it no longer uses these files. 

Re: changes to `salemaker_info.php` and `salemaker_popup.php`
This is good - we want this.

**Comment by neekfenwick** [comment]
@scottcwilson I've reverted the commit that touched modlist stuff (sorry if I got a bit carried away, I didn't know what those not_for_release files are all about).  Other changes left alone as requested 👍

**Comment by drbyte** [comment]
Do you mind posting before-and-after screenshots of those affected salemaker pages?

**Comment by scottcwilson** [comment]
Shouldn't be a visible difference but always good to check.

**Comment by scottcwilson** [comment]
@neekfenwick please squash this PR.

**Comment by drbyte** [comment]
> Shouldn't be a visible difference but always good to check.

Agreed. I think there was a technical reason why I didn't do this to those files originally. Maybe it was just to avoid the overhead of loading all the extra unneeded stuff on those pages. But admittedly those pages are rarely used so probably not a big deal. I'm just concerned that the popup may render wrong. Like: it shouldn't have the nav menu in it, etc.

**Comment by scottcwilson** [comment]
Could be.  I remember this was done in chunks across multiple releases, and I just figured folks ran out of time.

**Comment by lat9** [comment]
> Re: removing `admin/includes/stylesheet.css`, `admin/includes/menu.js` and `admin/menu.css`: ~Please don't do this. This would break older plugins that haven't been updated.~ Meh. Screw it. Do it. We'll update the documentation to guide people through this.

There should be an announcement on both zen-cart.com and here in the repository that this change is upcoming in 1.5.8b to give plugin developers and site-maintainers a heads-up.

**Comment by scottcwilson** [comment]
> There should be an announcement ...

Yes, I will do so as soon as this PR is merged.

**Comment by torvista** [comment]
Is there not a "Breaking Changes" section in the Release notes?
That's the Get-out-of-jail-free card to allow doing whatever the hell is necessary to move things forward.

**Comment by lat9** [comment]
> Is there not a "Breaking Changes" section in the Release notes? That's the Get-out-of-jail-free card to allow doing whatever the hell is necessary to move things forward.

There is, but if we _know_ that a breaking change is coming that heads-up gives people some breathing room to make their changes instead of going into "Oh Sh!t" mode.

**Comment by scottcwilson** [comment]
I promise I will overcommunicate this.

**Comment by neekfenwick** [comment]
> Do you mind posting before-and-after screenshots of those affected salemaker pages?

@drbyte The two modified files were:
- `salemaker_popup.php` opens a new window from the 'More info' link on salemaker details page.
- `salemaker_info.php` opens from the 'Click here for help with Salemaker' link at the top of the page (TEXT_SALEMAKER_POPUP).

The names are pretty confusing :) There's no visible difference after the change, it's just housekeeping.

Popup before:
230605-before-popup
Popup after:
230605-after-popup
Info before:
230605-before-info
Info after:
230605-after-info

**Comment by neekfenwick** [comment]
> @neekfenwick please squash this PR.

Sorry, what does this mean? Abandon the PR?

**Comment by drbyte** [comment]
> you may mean to squash the commits into one so there's a single commit to review. I've already pushed, and would have to force push which is generally a bad idea. Please confirm

Yes, squash into one commit and force-push that commit. Since it's going to your own branch in your own repo, it doesn't mess with the main branch at all, and in fact keeps it cleaner ... When working on a PR it's fine (even preferred) to force-push squashed commits so that the final repository workflow contains only canonical commits for said PR's.  (Sometimes of course a PR makes sense to have multiple commits in it when they're canonically related to certain things done ... such as reformatting of a file in one commit, and then making changes to it in another commit)

**Comment by drbyte** [comment]
> The names are pretty confusing :) There's no visible difference after the change, it's just housekeeping.

Agreed. Thanks for the screenshots.

**Comment by neekfenwick** [comment]
@drbyte Squashed into one commit and pushed as requested.

**Comment by scottcwilson** [comment]
> I still don't get what purpose the squash provides ...

If you don't squash, you wind up with multiple commits to a file for a single change.  This can be confusing to people trying to figure out what changes a file has undergone.   In particular, it makes incomplete (or even wrong) changes look like they have been accepted.

**Comment by neekfenwick** [comment]
> If you don't squash, you wind up with multiple commits to a file for a single change.

@scottcwilson I agree having every commit from a feature branch merged onto the main branch is bad, but that's not inevitable.

A squash merge i.e. `git merge --squash feature_branch` will squash all commits from the branch without the feature branch being affected.  Looks like github supports this workflow: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits

You've been doing this long enough to know this, so what am I missing? :)

**Comment by scottcwilson** [comment]
Yes, I can squash when I commit too, but this keeps the webpage in squash mode, and I have to remember to switch it back the next time I merge.  (And I have to wait for a merge, I can't just change it in isolation.) It's better if contributors do it themselves.

**Comment by scottcwilson** [comment]
@drbyte @lat9 Please approve/merge when you're satisfied.

**Comment by scottcwilson** [comment]
My todo items after this is merged: I will add a link to this doc page:
https://docs.zen-cart.com/dev/plugins/admin_head_content/

to the following places: 

- [] Plugin forum
- [] Release Specific Upgrade Considerations
- [] Release Notes

**Comment by scottcwilson** [comment]
Trivial follow on work: remove the `init()` references from 

`admin/attributes_controller.php`
`admin/downloads_manager.php`
`admin/index_setup_wizard.php`

(first two are just comments but might as well get rid of them all to prevent misreading and confusing)

**Comment by scottcwilson** [comment]
Please note this change was backed out by #6214.

**Comment by drbyte** [comment]
Er, well, only **partially** backed out.

**Pull request merged**
