### PR TITLE
products image efficency

### PR DESCRIPTION
**Pull request by brittainmark**
If there is no product image then there will not be any additional images. Therefore why process the additional image code.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Do we need similar checks in template_default?

**Comment by brittainmark** [comment]
Not sure if it's worth it. The additional images are loaded in a different place in the template, not straight after the main image (which has the if statement already there). If you want, I will add another check to the default template to bring it in line. 
Glad you asked, as I found 2 I had missed.

**Comment by scottcwilson** [comment]
Please squash and I will merge.

**Comment by brittainmark** [comment]
squashed as requested

**Pull request merged**
