### PR TITLE
Add a notifier to the footer of the admin.

### PR DESCRIPTION
**Pull request by mc12345678**

### CODE REVIEW

**Comment by drbyte** [comment]
What's the use-case for this?
What's the business problem this is solving?

**Comment by mc12345678** [comment]
Has been a direction to be added for the plugin User Tracking to identify flow within the admin area.  Acts similar to the notifier on the catalog side that was added to the main_page.  Admin side does not appear to have such a similar/consistent "trigger point".  

Would simplify installation if no file needed to be modified for full usage on a default/version fully compatible installation.

**Comment by lat9** [comment]
I could use it also for Super Globals, although I'd prefer the notification to be after the `<footer></footer>`.

**Comment by mc12345678** [comment]
I'm impartial to the location within the file, looking for relative consistent inclusion and expectation that the notifier would fire (even if observer load points have to be adjusted).

**Comment by drbyte** [comment]
Alright, ya, move it below the footer.

**Pull request merged**
