### PR TITLE
Prevent Product Qty Maximum instructions from wrapping

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
For things like this could you start providing before-and-after screenshots?

Also, these changes should be applied to all product-types.

**Comment by scottcwilson** [comment]
How about we get rid of the other product types so we don't have to keep maintaining code that almost no one uses?

**Comment by wiztechinc** [comment]
> How about we get rid of the other product types so we don't have to keep maintaining code that almost no one uses?

I’m game, even if you are joking!

**Comment by drbyte** [comment]
> How about we get rid of the other product types so we don't have to keep maintaining code that almost no one uses?

Eventually.

Until then it's best to keep them in sync.

Let's not hijack the topic at hand.

**Pull request closed without merging**
