### PR TITLE
Admin: category image changes

### PR DESCRIPTION
**Pull request by torvista**
Bugfix: from prior PR. When no image is defined, no option is presented to delete it so the POST img_delete is not created/passed and a warning is triggered on the preview page.
After reviewing the three options in the image section (delete /upoad new / use existing), I decided to simplify it, rather than just added isset.

The manual filename entry uses the selected subdirectory, which was not evident (not to me anyway), and no check was made on the filename existing: added check and corresponding messagestack texts.

The image shown on the page was at full size: added parameters to zen_info_image to allow use of responsive class.
Added file info (path, sizes, weight) to image info.
Clipboard01

### CODE REVIEW

**Comment by drbyte** [comment]
This appears to remove the ability to enter `none` in order to delete the image. 
Is that intentional?

**Comment by torvista** [comment]
I was not sure what the none was about, is that documented somewhere / is it necessary when there is a radio button to remove the image?

**Comment by drbyte** [comment]
I've never thought of it as an undocumented feature, but we've always supported this `none` option (pretty much) everywhere we support image edits.
You raise a fair point. Do you think we should remove the `none` feature for everyone?

**Comment by torvista** [comment]
Well, obviously I won't miss what I never knew about...but for other users??

**Comment by wiztechinc** [comment]
I certainly didn't know about it. Using the radio button only deletes it from the database - not actually deletes the image itself. So when you enter none, it's the same function as the radio button and does not actually delete the image? If so, why in the world was there even a reason to be able to also enter none?  I did find this documented the estart manual but I never used that thing to learn from in the first place. It also states it doesn't work in IE which is obviously outdated.  So streamline that code!

**Comment by barco57** [comment]
> but we've always supported this none option (pretty much) everywhere we support image edits.

I had no idea

**Comment by drbyte** [comment]
Interesting.

**Pull request merged**
