### PR TITLE
Add images/uploads/ to .gitignore

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by lat9** [comment]
Er, isn't there a special .htaccess in /images/uploads?  Won't that .gitignore prohibit its inclusion in the release?

**Comment by scottcwilson** [comment]
Files which are already checked in are ok.

**Comment by lat9** [comment]
... and there will never be a reason to update that .htaccess?

**Comment by scottcwilson** [comment]
Files which are checked in can be updated.  There's no problem.

**Comment by drbyte** [comment]
Hmmm. I was a bit fast on the trigger when merging this.

Generally the best practice is to put a .gitignore file inside the directory you want to exclude files from, and inside that .gitignore simply tell it to keep itself but exclude everything else.
```text
*
!.gitignore
```
I'll move it over.

**Pull request merged**
