### PR TITLE
TABLE_DASHBOARD_WIDGETS_GROUPS also does not need a languages id column

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
👍

**Comment by zcwilt** [comment]
:+1:

**Comment by barco57** [comment]
language_id Primary Key still needs to be removed on the table schema. Currently, an install stops at that point with a database problem.

```
DROP TABLE IF EXISTS dashboard_widgets_groups;
CREATE TABLE IF NOT EXISTS dashboard_widgets_groups (
  widget_group varchar(64) NOT NULL,
  widget_group_name varchar(255) NOT NULL,
  PRIMARY KEY (widget_group,language_id)
) ENGINE=MyISAM;
```

**Comment by scottcwilson** [comment]
Thanks @barco57.  PR #1252 submitted.

**Pull request merged**
