### PR TITLE
Restore off-page get forms

### LINKED ISSUE #3922: $_GET method of admin's zen_draw_form does not support action page other than self
https://github.com/zencart/zencart/blob/b3ed7bc02a0d4fbad68e7a2f086b79d05d5ee33a/admin/includes/functions/html_output.php#L245-L247

(Feel free to revise the title to something that might sound "better").

Basically, if I am on page X in the admin and setup a form using `zen_draw_form` where the form uses `get` parameters instead of `post` parameters, if the action page is not page X, then only page X gets loaded/reloaded when the associated submit button is pressed.  This is instead of loading the alternate page (say page Y) passing along the data that was to appear on the link address...

This was "discovered" through a problem with [Additional Product Images](https://www.zen-cart.com/downloads.php?do=file&id=1063) with a solution posted here: https://www.zen-cart.com/showthread.php?149805-Additional-Product-Images-addon&p=1372382#post1372382

Obviously another way "around" this is to have the current page "process" the self request and then take additional action which really would likely be that the code of the alternate page would be brought into the code of the one file or everything to be modified to use posting instead of getting data...

Note the "use" and results of this style of coding in the following ZC core admin files and note that a 'correction' to how `admin/includes/functions/html_output.php` operates would mean that the following may need adjustment:
https://github.com/zencart/zencart/blob/b3ed7bc02a0d4fbad68e7a2f086b79d05d5ee33a/admin/attributes_controller.php#L775
https://github.com/zencart/zencart/blob/b3ed7bc02a0d4fbad68e7a2f086b79d05d5ee33a/admin/products_price_manager.php#L291

These locations may "search" just fine; however, they do not move to that associated page.  Of course I have found similar "issues" with other code (non-ZC core code) that is currently present, but I haven't used/tried the features that would have revealed this problem.

I'm not sure that I follow why the referenced html_output code section was added, but...

FWIW, I have also looked into the potential use of `' get'` (adding a space either before or after the word) to prevent the use of the above code as the form's method will be properly populated, but this results in the admin's index page being loaded upon attempting to submit the form.

### LINKED ISSUE #5454: Can no longer create an admin form that targets a different page with GET request
**Is your feature request related to a problem? Please describe.**
In past Zen Cart releases I've had a form on our admin dashboard that lets us quickly type an order ID and be taken to the Orders page editing that order, i.e.:

```
<?php echo zen_draw_form('orders', FILENAME_ORDERS, '', 'get'); ?>
<input type="hidden" name="action" value="edit">
  <label>Order ID: <input name="oID" type="number"></label>
</form>
```

However, the latest `zen_draw_form()` insists on writing a hidden `input` with `name="cmd"` and `value` taken from the current requests's `$_GET['cmd']`.  The resulting HTML is:

```
<form name="orders" action="https://dev.site/my-admin/index.php?cmd=orders" method="get">
  <input type="hidden" name="cmd" value="home">
  <input type="hidden" name="action" value="edit">
  <label>Order ID: <input name="oID" type="number"></label>
</form>
```

The cmd=orders in the action is overridden by the hidden field's value, and submitting the form takes you to the `home` target instead of `orders`.

It seems that the way `zen_href_link()` and `zen_draw_form()` work in the latest release conflict with each other, because they both try to insert a `cmd` parameter into the request, the one generated by `zen_href_link` in this case is overridden and ignored.

**Describe the solution you'd like**
Ability to generate a form with customised `cmd` value different to the current page.

I wonder what the team think with their deeper knowledge of why and how this feature came about?

### PR DESCRIPTION
**Pull request by mc12345678**
Fixes #5454 and fixes #3922.

### CODE REVIEW

**Comment by proseLA** [comment]
i like (and use) my[ javascript solution](https://github.com/zencart/zencart/issues/5454#issuecomment-1348750544)

**Comment by mc12345678** [comment]
> i like (and use) my[ javascript solution](https://github.com/zencart/zencart/issues/5454#issuecomment-1348750544)

Which ***requires*** javascript to be enabled and the page to pass html validation to function out-of-the-box. Sure, could work, but why must core code be bypassed in this way to work?

**Comment by proseLA** [comment]
if someone is running zen-cart v157 or higher without javascript, i have no answers for you. 

i also think valid html (to a point) is a worthy goal. 

as we are talking about the admin side, i find this to be an elegant solution for those who want to modify their admin experience. 

i'm not a fan of further obfuscation of these html functions. but that's just me.

**Comment by scottcwilson** [comment]
Superceded by #5568.

**Pull request closed without merging**
