### PR TITLE
zen_get_master_categories_pulldown: allow show full path

### PR DESCRIPTION
**Pull request by torvista**
default: shows the single category name
Clipboard01

added optional parameter to show the full category path
Clipboard02

### CODE REVIEW

**Comment by lankeeyankee** [comment]
Where would you put the switch to turn fullpath on and off? As a checkbox on each page where the master category list is displayed or as a config setting? I like this idea.

**Comment by torvista** [comment]
you could do both....what does the panel think?

**Comment by drbyte** [comment]
Do we really need any switches? ie: How about just using the long form all the time?

Will that slow the pages down unnecessarily?
Will it clutter the display painfully?

**Comment by lankeeyankee** [comment]
I personally would like a per-page checkbox to enable it. Usually I would not want to use this, I tried the changes and when there are deep subcats the dropdown is extremely wide, almost full page width on a 1920 display. So I would want it as a way of clarifying/resolving questions of where the product is located when it's not immediately clear, like in Steve's example. I see it as a helpful tool to use when needed, not on by default. I did not notice any performance issues but I'm on a ripping dedicated server.

**Comment by drbyte** [comment]
Well, if we make the checkbox "in-page", then it could/would be ajax-driven, meaning the dropdown could be empty until needed, meaning the initial page-load would be faster (particularly for sites with lots of categories, meaning it has to dump a ton of HTML into the page on load). So, if one wanted to change from the default of short to long they could check the box and then the dropdown would update.

**Comment by torvista** [comment]
...that's exactly what I would like to have, but I'm not up to speed on ajax...so need an example/someone else do do it.

**Pull request merged**
