### PR TITLE
paypaywpp: initial IDE inspections/PSR-12

### PR DESCRIPTION
**Pull request by torvista**
replace isset with ??
short array syntax
use short form of type keywords
add parameter list (empty) to new classes
return types
some else if to elseif

**no logic changes.**

(Adding public visibility to functions changes whole file layout, so better as a separate PR).

### CODE REVIEW

**Review by brittainmark — COMMENTED** [review]
There may be other places that you could change and if (!isset($var)) {
$var=value; }

This is just an observation up to you if you want to make the changes.

**Comment by torvista** [comment]
On the first pass I try to offer only as much stuff as possibly that can be easily visually checked/non-contentious to get it out of the way quickly before adding stuff that requires some attention/more time.
This is a big file with multiple things to fettle with...

**Comment by brittainmark** [comment]
Fine with me.

**Comment by torvista** [comment]
I've been using it for some time.

**Comment by torvista** [comment]
Is this waiting for something?

**Pull request closed without merging**
