### PR TITLE
Make Ask a Question a button in Responsive Classic

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by zcwilt** [comment]
given long term we want to stop using zen_image_button is this pr necessary.

**Comment by scottcwilson** [comment]
Responsive classic uses CSS buttons so I would say yes.

**Comment by drbyte** [comment]
Is there a reason this wasn't also done in template_default?

**Comment by scottcwilson** [comment]
Just to show two possible variants.

**Comment by drbyte** [comment]
Fair. 

If someone turns off the CSS buttons then they'll get broken-image errors in the HTML because the image file doesn't physically exist, right?

**Comment by scottcwilson** [comment]
No the image does exist.  It's just ugly. :) 

includes/templates/template_default/buttons/english/button_ask_a_question.gif

**Comment by drbyte** [comment]
Hmmm ... Ian and I both looked and came up empty. But I just looked again, and there it is. One of those days :)

**Pull request merged**
