### PR TITLE
fix top part of admin page - #1914

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by Zen4All** [comment]
Just did a fresh install, and am gitting this error
```
[22-Dec-2018 15:30:58 Europe/Amsterdam] Request URI: /MY_ADMIN/index.php?cmd=downloads_manager, IP address: 
#1  require_once(/home/public_html/MY_ADMIN/includes/template/common/tplHtmlHead.php) called at [/public_html/MY_ADMIN/downloads_manager.php:11]
#2  require(/public_html/MY_ADMIN/downloads_manager.php) called at [/public_html/MY_ADMIN/index.php:35]

[22-Dec-2018 15:30:58 Europe/Amsterdam] PHP Warning:  Invalid argument supplied for foreach() in /public_html/MY_ADMIN/includes/template/common/tplHtmlHead.php on line 17
```

**Comment by drbyte** [comment]
Me too. 
Actually, on all of these "top part" converted pages this is failing.

**Comment by scottcwilson** [comment]
Checking ...

**Comment by scottcwilson** [comment]
OK I made these changes to pages which had already been converted - that was the error.

**Pull request merged**
