### PR TITLE
Add information on SQL Patches to the admin activity log

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
How do we strip logging of sensitive data?

**Comment by scottcwilson** [comment]
Can you give me an example of when this would occur?

**Comment by drbyte** [comment]
- updating a customer's personal information, whether in customer or order tables
- inserting configuration keys that contain module credentials for external services

**Comment by scottcwilson** [comment]
OK but this data is already in clear text in the database.  Why would it be worse in the log?

**Comment by drbyte** [comment]
> Why would it be worse in the log?

Because log files can be downloaded and stored separately. The rule is to never log sensitive stuff.

**Comment by drbyte** [comment]
You didn't explain your "why" for doing this PR. 

I assume you wanted some sort of audit trail of which patches you'd run?

**Comment by scottcwilson** [comment]
> Because log files can be downloaded and stored separately. The rule is to never log sensitive stuff.

If you *type it into the box* in Install MySQL Patches, it gets logged.  This just gives uploading a file the same behavior.

**Pull request merged**
