### PR TITLE
Experimental/full laravel

### PR DESCRIPTION
**Pull request by zcwilt**

### CODE REVIEW

**Comment by zcwilt** [comment]
This is a rebuild of a previous full Laravel integration 

It removes some stuff around filament/headless api and just concentrates on the Laravel integration

The previous integration had some issues regarding error handling/logging which are now better integrated, but need more testing where Zen Cart overrides the standard logging.

**Comment by torvista** [comment]
Just a head's up that I tried yesterdays integration and got stuck by this:
https://github.com/lat9/product_pagination/issues/28

Otherwise ok.

**Comment by zcwilt** [comment]
@torvista Thanks. @lat9 did pass on that error to me. 

I will take a look and see if there is a test I can add for that, If not test manually.

For now the Laravel stuff will remain as experimental until 

A) the ZC200 branch has is stable and released
B) test coverage on the experimental stuff is better

**Comment by torvista** [comment]
I was wondering if it was easier to just include that paging functionality in core, and was planning to start a discussion on it, maybe Laravel can offer it?

**Pull request closed without merging**
