### PR TITLE
Add a define page for search results

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
I'm not a fan of adding more "define pages".

I'd be content to see the addition of a language constant which accomplishes the same messaging.

**Comment by scottcwilson** [comment]
The advantage of a define page is that it is editable by the end user and doesn't require a developer to help.

**Comment by scottcwilson** [comment]
See update to #3914 as a way to move forward on define pages.

**Comment by drbyte** [comment]
Update: Not gonna do this in 1.5.8.

I'd accept a language define (perhaps the generic `TEXT_INFORMATION` one?) with some universal default text. 

Perhaps that default should be something like "We're happy to help you find what you're looking for. _Contact Us_ for additional help." 
(The previously-proposed "Not finding what you're after..." text will show even BEFORE they try to do any search if they land on the search page via a link, so it's a slightly negative message before they even start, hence the suggestion for "We're happy to help...")

**Pull request closed without merging**
