### PR TITLE
fix sql on zen_products_lookup

### PR DESCRIPTION
**Pull request by proseLA**
addresses #4147

### CODE REVIEW

**Comment by drbyte** [comment]
The better fix is to change "USING" to "ON".
Syntax is:
"USING (field)" where field-name matches between tables. Handy when only one field is joined.
or 
"ON (t1.fieldname=t2.fieldname AND othercondition)"

**Comment by proseLA** [comment]
why is `ON` better than `USING` in this situation?  is there a performance hit or a different result set?

i'm curious.

**Comment by drbyte** [comment]
Slight performance gain by having the AND condition for language linked to the JOIN on the table where the language field is present.

```
SELECT products_id AS lookup_field
FROM " . TABLE_PRODUCTS . " p
INNER JOIN " . TABLE_PRODUCTS_DESCRIPTION . " pd USING (products_id) 
WHERE  p.products_id = " . (int)$product_id . " AND pd.language_id = " . (int)$language;
```
Here the join brings back all product descriptions for the `products_id`, including records for all languages.
Then later the WHERE clause filters out the extras.

```
SELECT products_id AS lookup_field
FROM " . TABLE_PRODUCTS . " p
INNER JOIN " . TABLE_PRODUCTS_DESCRIPTION . " pd ON (pd.products_id = p.products_id AND pd.language_id = " . (int)$language .")
WHERE  p.products_id = " . (int)$product_id;
```
Here the join brings back only the product description records matching both `products_id` and `language_id`, which means the filtering is done earlier in the process.

Depending on the dataset this could be significantly faster.

**Comment by proseLA** [comment]
thanks.

**Comment by drbyte** [comment]
I should add: we make two common exceptions to this practice.

1. Sometimes we leave the second condition in a WHERE clause if that WHERE clause is likely to get appended-to with some AND statements in subsequent code. This makes it simpler to let the code concatenate more AND statements without having to guess whether WHERE clause already exists.

2. Sometimes we use `ON(t1.field=t2.field)` instead of `USING(field)` if subsequent code is likely to inject more tables into the join, which could confuse the query optimizer about what table the `field` should join on. Adding the specificity allows surrounding code to be slightly more fluid. While the ON syntax is more verbose, the specificity prevents ambiguity.

**Pull request closed without merging**
