### PR TITLE
Check needs to be inverted

### LINKED ISSUE #3543: Can't add/update product with new product.php
Was having problems with alpha and thought it might be the DB.  Meanwhile, beta arrives.
Load beta and demo with nothing else.
Go to Categories/Products
Click on hardware, then CDROM Drives.
Click New Product.
When info is added click Preview
Blank form and error.
adminProduct

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #3543

### CODE REVIEW

**Comment by zcwilt** [comment]
Still not convinced this is correct. 
If I got to the new product page, don't fill in any entries and immediately hit preview, then I will get the warning message which is confusing in what it is warning about.

**Comment by scottcwilson** [comment]
When I edit product 21 in the test data set with this fix, I don't get the issue.
What product are you editing?  Or are you doing a new product?

**Comment by zcwilt** [comment]
New Product

**Comment by zcwilt** [comment]
Just to clarify, there's nothing inherently wrong in warning that say the name entry is empty, although we never did it before. It's just then that the message displayed is ambiguous.

**Comment by scottcwilson** [comment]
It looks ok to me - it says your data is empty.  Which it is!

**Comment by zcwilt** [comment]
Yes, but also says that you may have a problem with bowser or internet.

**Comment by scottcwilson** [comment]
Which you may! :)
What do we need to do to wrap this up - do you want me to remove that language?

**Comment by zcwilt** [comment]
I'm probably being too anal.

**Pull request merged**
