### PR TITLE
Document overriding of show_ settings

### PR DESCRIPTION
**Pull request by scottcwilson**
As discussed in #4688, document how to override switches for displaying various things in `invoice.php` and `packingslip.php`, as was done in `orders.php`.

### CODE REVIEW

**Comment by lat9** [comment]
#4771 adds /admin/includes/extra_datafiles/dist-site_specific_admin_overrides.php, which is where these 'soft' configuration settings can find a home.

**Comment by scottcwilson** [comment]
Comments now refer to (help on) site-specific overrides file.

**Comment by lat9** [comment]
@scottcwilson, could you add those settings (commented-out) to the `/admin/includes/extra_datafiles/dist-site_specific_admin_overrides.php`?  Please keep the 'soft' configuration settings in alphabetic order so that ... as the number of settings grows ... an individual setting is easy to find.

**Comment by scottcwilson** [comment]
Will do but this is an old PR that pre-dates that file - please go ahead and merge it so I don't have to update this old branch.

**Comment by scottcwilson** [comment]
Done in #4784

**Pull request merged**
