### PR TITLE
Add lat9's Report All Errors mod

### LINKED ISSUE #2460: Request: Integrate Report All Errors as a core feature
This is tremendously useful for developers.  Alternately, instead of integrating the entire module, perhaps it could be integrated without configuration, and triggered when STRICT_ERROR_REPORTING was set.

### PR DESCRIPTION
**Pull request by scottcwilson**
Implements / Closes #2460

### CODE REVIEW

**Comment by scottcwilson** [comment]
Got carried away in cleanup.

**Comment by scottcwilson** [comment]
Got carried away in cleanup.

**Comment by drbyte** [comment]
Hmmm ... now I seem to be getting "no" logs, even when setting to 'Yes'...

**Comment by scottcwilson** [comment]
I get 

--> PHP Notice: Constant TEXT_GV_REDEEM already defined in /Users/scott/Sites/gh_demo_157/admin/includes/languages/english.php on line 87. 

so that's one.

**Comment by zcwilt** [comment]
I get the same as @scottcwilson for admin

**Comment by zcwilt** [comment]
Also getting language define errors from catalog as well

**Pull request merged**
