### PR TITLE
Enable a plugin to add additional search fields ...

### PR DESCRIPTION
**Pull request by lat9**
... to the admin's category/product listing.

### CODE REVIEW

**Comment by proseLA** [comment]
who is loving the `zen_build_keyword_search_function`?

i'm unsure whether you want to check if the return value is an array prior to doing an array merge.

**Comment by lat9** [comment]
> who is loving the `zen_build_keyword_search_function`?
> 
> i'm unsure whether you want to check if the return value is an array prior to doing an array merge.

The thing with that function is that it's used _everywhere_, so you need  to check where you are when you receive any function-based notification.

The 'return value' is initialized to an array; if an observer has changed it to another data type, it should be "punished" with an error log.

**Comment by scottcwilson** [comment]
LOL "punished."

**Comment by scottcwilson** [comment]
Thanks @lat9 and @proseLA !

**Pull request merged**
