### PR TITLE
Admin countries, correct missing page= on pages other than first

### PR DESCRIPTION
**Pull request by lat9**
... as reported in [this](https://www.zen-cart.com/showthread.php?229309-Admin-Locations-Taxes-Countries-cannot-edit-country-not-on-first-page) Zen Cart forum bug-report.

### CODE REVIEW

**Comment by proseLA** [comment]
i think this fixes the problem...  however, any mis-constructed url still causes an error, ie:

admin/index.php?cmd=countries&cID=170

is that something that we should address?

**Comment by scottcwilson** [comment]
@proseLA can you be more specific?  I'm not tracking. 

If I go to Admin > Locations > Countries and select "Antarctica" the URL is 

http://localhost:8888/gh_demo_158/admin/index.php?cmd=countries&page=A&cID=8

If I diddle the URL to remove the page parameter

http://localhost:8888/gh_demo_158/admin/index.php?cmd=countries&cID=8

I still works with no log under PHP 8.1.

**Comment by lat9** [comment]
@scottcwilson, try that on one of the non `page=A` countries.  I'm still coffeeing up, but I'm guessing that that's the issue that @proseLA refers to.

**Comment by proseLA** [comment]
> @proseLA can you be more specific? I'm not tracking.
> 

http://localhost:8888/gh_demo_158/admin/index.php?cmd=countries&cID=170

**Comment by proseLA** [comment]
@lat9 well done!

**Pull request merged**
