### PR TITLE
Fix GV_NAME define

### PR DESCRIPTION
**Pull request by scottcwilson**
See https://www.zen-cart.com/showthread.php?224966-GV_NAME-GV_NAMES-defined-too-late for an explanation.

### CODE REVIEW

**Comment by proseLA** [comment]
3 of the files have closing php tags at the end of the file.  might as well remove them while u r here....

**Comment by scottcwilson** [comment]
I'd rather not make changes like this in a dot release.  If there's a 1.5.7, we can do it there.

**Comment by lat9** [comment]
You realize that migrating those constants out of the main language file could break existing admin-level plugins that expect those definitions to be preexisting, right?

**Comment by scottcwilson** [comment]
Agreed.  Let's pull the file into english.php if it hasn't already been done.

**Pull request merged**
