### PR TITLE
[v156] Port v160 Nginx Setup Config

### PR DESCRIPTION
**Pull request by dakanji**
Port Nginx Install Config Setup from v160

### CODE REVIEW

**Comment by drbyte** [comment]
Mind squashing these commits into one?

**Comment by dakanji** [comment]
Not sure how it works doing this after already pushed. Always get muddled up. Happy to have a go though.

**Comment by drbyte** [comment]
No worries.

Squashing requires:
- interactive rebase, where you tell it to squash commits into previous commits (squash is the action listed)  -- you have to tell it which commit to rebase onto, which is basically your first commit of the series.
- then a force-push to the github repo

Interactive rebase can be done fairly easily using whatever your favorite git tool is, whether command-line or GUI.
Here are some articles explaining it:
https://davidwalsh.name/squash-commits-git
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by dakanji** [comment]
I can do the squashing. Just thought I wasn't supposed to do this if already pushed out. Will have a go.

**Comment by drbyte** [comment]
Ya, force-push shouldn't be used when pushing to a primary branch that others pull from.

But since a PR is a private branch in your own repo, it's the perfect way to clean things up for the PR.

**Comment by dakanji** [comment]
Hope that works!

**Comment by drbyte** [comment]
Hm, nope. 
All the commits listed in this PR should disappear, and one new one added at the bottom. And the commits-count will reduce to 1.

**Comment by dakanji** [comment]
Gone off the rails. Will just delete PR and do a fresh one

**Pull request closed without merging**
