### PR TITLE
Remove the admin demo functionallity

### PR DESCRIPTION
**Pull request by Zen4All**
Officially the zen_admin_demo function has been deprecated years ago, and was planned to be removed in 2.0
This PR removes it for 1.5.7

---
This change is [Reviewable](https://reviewable.io/reviews/zencart/zencart/2515)

### CODE REVIEW

**Comment by scottcwilson** [comment]
I wish we weren't doing this.  I use this functionality to build admin demos. :(

**Comment by Zen4All** [comment]
@scottcwilson Maybe continue it as a separate add on? I think the you and I ,and a very small group of developers are actually using this.

**Comment by drbyte** [comment]
Unfortunately this is hard to move to an addon.

It begs of a full per-action-permission authorization infrastructure.

I too would like to see the demo-specific code removed (and I wonder if it's thorough enough as it is right now), but it may be better to morph it to an `action`-based permissions-control system.

**Comment by zcwilt** [comment]
Agree that removing this does tidy up code and given it is a very niche requirement.
@scottcwilson  have a really simple idea about how we can do this as an addon. will ping you with details later.

**Comment by drbyte** [comment]
Note: for a true demo-only site, setting a cron job to replace the database daily is probably an even better option. And probably hard-code a few feature overrides like config settings, as constants instead of loading them from the db.

**Pull request merged**
