### PR TITLE
Lookup customer by id, not email

### PR DESCRIPTION
**Pull request by scottcwilson**
> What's the problem that we're trying to solve with this change?

It's a faster operation on a large database.

### CODE REVIEW

**Comment by drbyte** [comment]
This would break lookups for guest shoppers, right?

How about a hybrid by passing both and the lookup does a fallback?

**Comment by scottcwilson** [comment]
Don't guests also have their own customer id?   Or are they customer id 0?   (Different mods may have handled this in different ways over the years I suppose).

**Comment by drbyte** [comment]
No guarantees. Especially for older mods. Or for newer ones that don’t create a pseudo account

**Comment by lat9** [comment]
FWIW, **_One-Page Checkout_** re-uses a fixed `customer_id` for all guest orders, so searching on the customers_id will bring up **all** guest-checkout coupons.

What's the problem that we're trying to solve with this change?

**Comment by scottcwilson** [comment]
> What's the problem that we're trying to solve with this change?
It's a faster operation on a large database.

**Comment by wiztechinc** [comment]
Original COWOA just had a extra field for guest versus signed up buyer so that it can be determined in admin which is which. No difference otherwise.

**Comment by lat9** [comment]
> > It's a faster operation on a large database.

That makes sense; noting that for _OPC_, that click will present the common guest-customer's record.

**Comment by scottcwilson** [comment]
I'm not convinced that there is ever *not* a customer table record for an order.  I think this change is OK as-is.

**Comment by lat9** [comment]
Agreed, unless it's been removed.

**Comment by drbyte** [comment]
> FWIW, **_One-Page Checkout_** re-uses a fixed `customer_id` for all guest orders, so searching on the customers_id will bring up **all** guest-checkout coupons.

Ya, this is going to be a problem. Until changes to core can allow that to not be an issue, we shouldn't make this proposed change.  After that I'm all for a change that allows speed improvements.

**Pull request closed without merging**
