### PR TITLE
Changing admin image display to size via CSS instead of HTML attribute

### PR DESCRIPTION
**Pull request by retched**
This change allows the image to be resized dynamically via CSS instead of hardcoded via HTML  attributes.

For example: the pictures in the category listing would be stretched to fit both the height and width of the image settings as designated in the admin backend. This change moves the setting of the image's height and width to CSS where appropriate (ie. where the image's height or width are set in the function call).

### CODE REVIEW

**Comment by drbyte** [comment]
I see your point, and like it. 
One problem I see caused by this change is the loss of the ability to continue using a single-pixel gif to draw a divider line, which is still in use around a lot of the admin pages (due for conversion to an HR or some other divider at some point, probably in the Spring for v3.0)

Before:
before

After:
after

**Comment by retched** [comment]
Dang it! I was on the lookout for that thing!

The only other thing I could think of would be to create a new function solely for the listing grid (call it like `zen_product_image` or something) and change the category_listing calls for images to that new one. But I feel there is a better way to go about it.

**Comment by drbyte** [comment]
You had used `style="width="22px;""`, where the `=` should have been `:`, and the extra quotes were wrong too.

I reworked it to sus out whether `style=` had already been passed, and to conditionally add height/width where not already present, and to account for already being set as `%` or not.

This appears to work harmoniously with `zen_black_line()` and `zen_draw_separator()`.

**Comment by drbyte** [comment]
But does that let the proportional stuff work that you were after initially?

**Comment by retched** [comment]
> But does that let the proportional stuff work that you were after initially?

Close to the desired effect. Added in a `, 'style="object-fit: contain;"'` to the call params from category_product_listing.php file. This way it forces the listing to use the proportional fit.

These are the results:

image

**Comment by lat9** [comment]
> You had used `style="width="22px;""`, where the `=` should have been `:`, and the extra quotes were wrong too.
> 
> I reworked it to sus out whether `style=` had already been passed, and to conditionally add height/width where not already present, and to account for already being set as `%` or not.
> 
> This appears to work harmoniously with `zen_black_line()` and `zen_draw_separator()`.

Don't the `width=` and `height=` just want to be numbers?  That is, no `px` added.

**Comment by retched** [comment]
> > You had used `style="width="22px;""`, where the `=` should have been `:`, and the extra quotes were wrong too.
> > I reworked it to sus out whether `style=` had already been passed, and to conditionally add height/width where not already present, and to account for already being set as `%` or not.
> > This appears to work harmoniously with `zen_black_line()` and `zen_draw_separator()`.
> 
> Don't the `width=` and `height=` just want to be numbers? That is, no `px` added.

Effectively yes. The numbers used in `category_display` are the `SHOPPING_CART_HEIGHT` and `SHOPPING_CART_WIDTH` defines. Those are normally used in HTML attributes of the image tag and only accept the number of pixels and not percentages.

**Comment by drbyte** [comment]
> Don't the `width=` and `height=` just want to be numbers?  That is, no `px` added.

Yes. When used as ``. But this PR is dropping those and replacing them with CSS syntax via a `style="width: 20px; height=40px;"` attribute. CSS syntax wants the units, because they could be `px` or `%` or `rem` etc.

**Pull request merged**
