### PR TITLE
Add mysql version check

### LINKED ISSUE #6002: zc_install: Need to check for minimum MySQL version prior to continuing
As described in [this](https://www.zen-cart.com/showthread.php?229421-1-5-8a-Missing-customer_groups-field-in-DB) Zen Cart bug-report, there have been a couple of sites that have undergone a _successful_ install/upgrade only to find that the `customer_groups` and `customers_to_groups` tables are missing:
```
PHP Fatal error: 1146:Table 'xxx.customer_groups' doesn't exist :: SELECT count(*) as total FROM (SELECT cg.*, count(ctg.customer_id) as customer_count FROM customer_groups cg LEFT JOIN customers_to_groups ctg USING (group_id) GROUP BY cg.group_id ORDER BY group_name, group_id) countresults ==> (as called by) /xxxxxxxxxxxxx/includes/classes/split_page_results.php on line 220 <== in /includes/classes/db/mysql/query_factory.php on line 667.
```

Shouldn't the zc_install process be checking for a minimum MySQL/MariaDB version before proceeding with the install/upgrade to prevent these issues?  This issue, for instance, was reported for a site running MySQL 5.5.68-MariaDB .

### PR DESCRIPTION
**Pull request by brittainmark**
Add a check into the install to ensure that the database is at least the minimum version of Mysql of MariaDB. The check only fails if it is able to perform a version check and the version is less than that specified in systemChecks.yml.

fixes  #6002

### CODE REVIEW

**Comment by drbyte** [comment]
Looks fine at first glance, but I've not tested it with anything yet.

I'd prefer that the mention of "Mysql" be "MySQL" in the error messages, but that's merely a minor cosmetic tweak.

**Comment by brittainmark** [comment]
Changed as requested

**Comment by drbyte** [comment]
Thanks.

**Comment by drbyte** [comment]
Thanks for taking care of this!

**Pull request merged**
