### PR TITLE
Windows server, php-generated utf-8 days with accents not displayed correctly

### LINKED ISSUE #973: Windows server, php-generated utf-8 days with accents not displayed correctly
This has always been a problem on the Windows Xampp servers I use and is no different on Windows 10/php 7 for locale Spanish_Spain.1252.

clipboard02
clipboard01

I could not find any other way to solve this apart from treating windows differently as this is not a problem on my Nix server.
So for the two function zen_date_long,
I have had this in place for a long time:
`return ( stristr(PHP_OS,"win") ? 
	utf8_encode(strftime(DATE_FORMAT_LONG, mktime($hour, $minute, $second, $month, $day, $year))) : 
	strftime(DATE_FORMAT_LONG, mktime($hour, $minute, $second, $month, $day, $year)) );`

Maybe someone could comment if IIS has the same issue...

Note I have a working spanish language pack in progress for 1.6 if anyone wants it for testing.

### PR DESCRIPTION
**Pull request by drbyte**
Fixes #973 using suggestion by @torvista

### CODE REVIEW

**Comment by drbyte** [comment]
@torvista do you mind testing this out as confirmation?

**Comment by zcwilt** [comment]
:+1:

**Comment by torvista** [comment]
This works as tested with today's 1.6 on Xampp 7.04 Windows 10.

**Comment by ajeh** [comment]
:+1:

**Comment by torvista** [comment]
Local Windows Server

https://github.com/zencart/zencart/blob/f07e2e6e726a8e2db486066502e3d81a0ed42ea1/admin/includes/header.php#L203

7.4.33
datetime 7 4 33

8.0.30
datetime 8 0 30

8.1.25
datetime 8 1 25

8.2.12
datetime 8 2 12

8.3.0RC6
datetime 8 3 0RC6

Suggest removing the iconv and ignoring Windows.

**Pull request merged**
