### PR TITLE
simple aliasing for notifier eventID

### PR DESCRIPTION
**Pull request by zcwilt**

### CODE REVIEW

**Comment by drbyte** [comment]
Should the alias being set up here be put the other way around? Where the misspelling is the thing being "accommodated"?

ie: by default I think core code should have what we "want it to be", and then the aliases can be patches that bridge things to accommodate for past errors

eg: reverse the array, and also fix the misspelling in the order class

**Comment by zcwilt** [comment]
In legacy code the notifier would be NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE
In that case we don't want anything to change
In new code the notifier would be NOTIFY_ORDER_CART_SUBTOTAL_CALCULATE
In that case we want to replace it with NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE so legacy observers will still fire.

**Comment by zcwilt** [comment]
Hmm, but I see what you mean. In this case new code would have to use the legacy notifier name in its `update` method.

**Comment by zcwilt** [comment]
k, going to close this. 
It's probably better to do the aliasing at the observer point.
e.g. if $obs[NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE]  exists, alias it too NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE

and in that case you are right in that would have to reverse the array

**Comment by scottcwilson** [comment]
> e.g. if $obs[NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE] exists, alias it ... 
Wait - you mean if $obs[NOTIFY_ORDER_CART_SUBTOTAL_CALCULATE] (correctly spelled) exists, then alias - right?

**Comment by zcwilt** [comment]
So what is the intent of aliasing.
If legacy code is using an observer based on an old notifier name it will fail.
So the test we currently do is 

`if ($obs['eventID'] == $eventID || $obs['eventID'] === '*')`

In the legacy code the `$obs['eventID'] = NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE`
and `$eventID = NOTIFY_ORDER_CART_SUBTOTAL_CALCULATE`

So we need to check for an alias using $obs['eventID'] and then  `'temporarily` alias $eventID to NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE
and use that to build the update method call.



if

**Comment by zcwilt** [comment]
Testing some new code now.

**Comment by scottcwilson** [comment]
Your update "k, going to close this." has the alias and the observer both misspelled.  Which one should be the correctly spelled one?

**Comment by zcwilt** [comment]
should read 
e.g. if $obs[NOTIFY_ORDER_CART_SUBTOTAL_CALCULATE] exists, alias it too NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE

Although even that doesn't quite capture what needs to happen

Should have something shortly

**Pull request closed without merging**
