### PR TITLE
Add a notification for zen_get_products_special_price

### PR DESCRIPTION
**Pull request by lat9**
Add a notification for the subject function, enabling a site to override the default salemaker sale behavior, e.g. enabling the site to include products linked to a sale category.

Also restores the commentary that describes what the 'sale_deduction_type' values actually mean.

### CODE REVIEW

**Comment by lat9** [comment]
OK, so the question of the day (mine, anyways):  Why the heck does the admin not share `functions_prices.php` with the storefront?

**Comment by marco-pm** [comment]
> OK, so the question of the day (mine, anyways): Why the heck does the admin not share `functions_prices.php` with the storefront?

Isn't that already the case for ZC v158?

**Comment by lat9** [comment]
> Isn't that already the case for ZC v158?

Unfortunately, no.  It's one of the few function-files that isn't shared.  That (and for whatever reason) `html_output.php`.

**Comment by marco-pm** [comment]
> Unfortunately, no. It's one of the few function-files that isn't shared.

https://github.com/zencart/zencart/blob/078b509bb514ab344a034e89508eb02f1e63854c/admin/includes/functions/functions_prices.php

🤨

**Comment by lat9** [comment]
OK, so I'm having a bad day/week/month ...

**Comment by scottcwilson** [comment]
> Why the heck does the admin not share functions_prices.php with the storefront?

Fair question.  In at least some cases, there is enough difference between admin/storefront function implementations that it was too just much work (at least at the time, given other commitments).  

PRs would be welcome for either or both.   Maybe @marco-pm needs a project! :)

**Comment by lat9** [comment]
> > Why the heck does the admin not share functions_prices.php with the storefront?
> 
> Fair question. In at least some cases, there is enough difference between admin/storefront function implementations that it was too just much work (at least at the time, given other commitments).
> 
> PRs would be welcome for either or both. Maybe @marco-pm needs a project! :)

Turns out, per @marco-pm's reply that the module in the admin is a "remove me" stub.

**Comment by scottcwilson** [comment]
Yes for functions_prices.php, but no for html_output.php.

**Pull request merged**
