### PR TITLE
Correct duplicate, linked products in mfgrs listing

### PR DESCRIPTION
**Pull request by lat9**
As identified in [this](https://www.zen-cart.com/showthread.php?225669-Item-showing-twice-(or-more)&p=1359616#post1359616) Zen Cart forum posting.

### CODE REVIEW

**Comment by drbyte** [comment]
While DISTINCT works, I wonder if there's a tweak to the linking of the `products_to_categories` table that might be even more "correct"?

**Comment by drbyte** [comment]
@Zen4All did you see any of this when you were tweaking the filters?

**Comment by Zen4All** [comment]
Not that I remember, but is people report they do, we should put the DISTINCT back

**Comment by lat9** [comment]
@drbyte is correct; the 'culprit' in the duplication appears to be the clause `LEFT JOIN " . TABLE_PRODUCTS_TO_CATEGORIES . " p2c ON p2c.products_id = p.products_id`.  If a product is in multiple categories, i.e. linked, that will result in multiple copies of the product being displayed.

**Comment by drbyte** [comment]
Does this need backporting?

**Comment by drbyte** [comment]
And does it apply equally to other product-types?

**Comment by lat9** [comment]
Back-porting would be a "good thing" and yes, the change applies in a _similar_ manner to the other index-filters.

**Pull request merged**
