### PR TITLE
add http/s filter for url field user input

### PR DESCRIPTION
**Pull request by torvista**
subsequent to this, when collect_info PRs have been calmed down, I suggest

### CODE REVIEW

**Comment by scottcwilson** [comment]
Can you throw in blanking out  TEXT_PRODUCTS_URL_WITHOUT_HTTP  in includes/languages/english/product.php - we could remove it next release?

**Comment by torvista** [comment]
I was going to put suitable text inside the field, when the current PRs have been resolved for collect_info. My past experience with crossconnecting PRs is not good.

**Comment by scottcwilson** [comment]
If you get in first, you win! :)

**Comment by torvista** [comment]
closes https://github.com/zencart/zencart/issues/3157

**Pull request merged**
