### PR TITLE
functions: zen_set_field_length - remove spaces in tags

### PR DESCRIPTION
**Pull request by torvista**
Could these not be made identical?

### CODE REVIEW

**Comment by scottcwilson** [comment]
It doesn't make sense to do a whole lot of work on this because at some point these duplicated functions are going to be merged.

**Comment by torvista** [comment]
Sure, but it's easier if they are duplicated **and** correct.

What does "Draft" mean?

**Comment by drbyte** [comment]
> What does the "Draft" label mean?

Draft can be used for many things, often: "work in progress; more commits expected".

In this case I'm using it to "put it on hold because I'm undecided whether I will merge this"

**Comment by drbyte** [comment]
Did you intentionally uncheck the tickbox that allows commits/edits by maintainers?
If you let maintainers do edits, then we can make additional commits before merging.

Right now this PR seems to be disallowing me to do such edits, hence the question.

I was going to fix the docblocks.

**Comment by drbyte** [comment]
But perhaps this is another opportunity for you to practice `git commit --amend`

The docblocks you added via the IDE didn't declare that the first two params are string

**Comment by torvista** [comment]
>Did you intentionally uncheck the tickbox that allows commits/edits by maintainers?
Of course, I didn't want you tempted to go in there fixing things willy-nilly.

**Comment by drbyte** [comment]
> > Did you intentionally uncheck the tickbox that allows commits/edits by maintainers?
> 
> Of course, I didn't want you tempted to go in there fixing things willy-nilly.

😊

**Pull request merged**
