### PR TITLE
zen_update_orders_history: Correct PHP Notice

### PR DESCRIPTION
**Pull request by lat9**
... due to misspelled variable name.

### CODE REVIEW

**Comment by drbyte** [comment]
Aren't typos fun!?!!

**Comment by drbyte** [comment]
@lat9 what do you think about whether we should touch `NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE` in orders.php class? 
ie: the extra 'i'.

**Comment by lat9** [comment]
Yes, they are ... not!

For that notifier, it is (in my mind) a legacy value and should not be changed as the change would undercut any observer that's currently "watching".

**Comment by drbyte** [comment]
> For that notifier, it is (in my mind) a legacy value and should not be changed as the change would undercut any observer that's currently "watching".

Agreed. And adding a corrected spelling one beside it could make it double-fire if a plugin chooses to listen on both!  :(

**Pull request merged**
