### PR TITLE
Ignore

### LINKED ISSUE #3530: Search function in attributes controller seems to be useless
While working on some last minute UI updates, I was testing the search box.
No matter what i type in, the search always returns empty.
Furthermore, the file name in the form goes to category_product_listing, instead of attributes_controller.
Working on a PR to solve this.

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #3530

### CODE REVIEW

**Comment by Zen4All** [comment]
But that takes you to the category listing. 
Personally I would not want that.

**Comment by scottcwilson** [comment]
That's how it has always worked.  You can run a test in 1.5.6 and see this.
This function was broken in 1.5.7.

**Comment by scottcwilson** [comment]
Please see #3532 in lieu of this.

**Comment by scottcwilson** [comment]
Superseded by #3532

**Pull request closed without merging**
