### PR TITLE
Reduce complexity of code and refresh look of Attributes Controller

### PR DESCRIPTION
**Pull request by Zen4All**
These are the changes done to the attributes controller so far.
Maybe I have overdone it, but I tried to reduce the complexity of the file, ans also refresh its looks.

---
This change is [Reviewable](https://reviewable.io/reviews/zencart/zencart/1531)

### CODE REVIEW

**Comment by drbyte** [comment]
Liking it so far. Thanks!

How complete is this?

**Comment by Zen4All** [comment]
I'd say 99%

**Comment by drbyte** [comment]
Thanks. Will start reviewing more deeply...

**Comment by drbyte** [comment]
What do you think of converting the added `<h4>` and `<h5>` to `<h3>` and `<h4>` respectively? 

(The `<h5>` defaults are kinda tiny and undistinguished.)

**Comment by Zen4All** [comment]
That sounds okay to me. I'll make a comit for that

**Comment by drbyte** [comment]
Going to merge. 
Will do more testing after merge. Additional updates/fixes can be PR'd.

**Pull request merged**
