### PR TITLE
Allow admin javascript to have its own file instead of altering core

### PR DESCRIPTION
**Pull request by drbyte**
Custom admin javascript can now be added to `/admin/includes/javascript_loader.php` as needed.

### CODE REVIEW

**Comment by drbyte** [comment]
Good point. I've updated to harmonize them a bit. 

A wholesale admin rewrite with a complete templating system would make this simpler; developers love that idea, but storeowners/upgraders and plugin authors despise it. :(

**Comment by barco57** [comment]
anything that forces updates of add-on modules I am all for, Break all the things!

**Comment by zcwilt** [comment]
:+1:

**Comment by ajeh** [comment]
:+1:

**Pull request merged**
