### PR TITLE
check string before running operations

### LINKED ISSUE #4892: admin page registration: php 8.1 PHP Deprecated: strtr()
ZC158, php 8.1.7

> [19-Jun-2022 19:44:27 UTC] Request URI: /zencart/admin/index.php?cmd=admin_page_registration, IP address: 127.0.0.1
> #0 [internal function]: zen_debug_error_handler()
> #1 \zencart\includes\functions\functions_strings.php(24): strtr()
> #2 \zencart\admin\includes\functions\html_output.php(418): zen_output_string()
> #3 \zencart\admin\admin_page_registration.php(141): zen_draw_pull_down_menu()
> #4 \zencart\admin\index.php(11): require('zenca...')
> --> PHP Deprecated: strtr(): Passing null to parameter #1 ($string) of type string is deprecated in \zencart\includes\functions\functions_strings.php on line 24.

Back to the unresolved discussion to fix or bin this page:
https://github.com/zencart/zencart/pull/3533

### PR DESCRIPTION
**Pull request by scottcwilson**
Partial fix for issue raised in #4892.

### CODE REVIEW

**Comment by lat9** [comment]
Let's address the issue at its source; in /admin/admin_page_registration.php, the initialization of the `$menu_options` array sets the default 'id' to `NULL` instead of a _more proper_ empty string `''`.

https://github.com/zencart/zencart/blob/538601126506f1c3c80ed1a5b956f659b1043d94/admin/admin_page_registration.php#L90

**Comment by scottcwilson** [comment]
See #4898

**Comment by lat9** [comment]
#4898 looks good; please close this one.

**Comment by scottcwilson** [comment]
You don't think we should check inputs for one of our functions?

**Comment by lat9** [comment]
If you're going to 'check', then change the parameter type to `string` instead of blindly returning an invalid value.

**Comment by scottcwilson** [comment]
Let's close for now.  As you noted, the real error was in the caller, so that change might be the only one needed.

**Pull request closed without merging**
