### PR TITLE
EMAIL_ORDER_DATE is no longer used in email templates

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
What might this removal break?

**Comment by scottcwilson** [comment]
This setting of this entry in the `html_msg` array was introduced in zen-cart-v1.5.2-RC1-11262013 but it has never been referenced in any version of Zen Cart.   I don't see it in any plugins either.

**Comment by drbyte** [comment]
Does that mean the define for `ORDER_EMAIL_DATE_FORMAT` should be removed as well?

**Comment by scottcwilson** [comment]
I reckon so.  Good catch.

**Pull request merged**
