### PR TITLE
Correct inclusion of stylesheet

### LINKED ISSUE #3559: Is the profiles page supposed to look like this now?
edit_profiles_page

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #3559.

### CODE REVIEW

**Comment by drbyte** [comment]
This PR appears to add a new file, `/admin/includes/admin_access.css` which is not in the `css` subdirectory.
I think you meant to merely add some lines to the existing css file, not add a whole new one in a different location.

**Comment by scottcwilson** [comment]
Not really a new file - it existing in 1.5.6 as `admin/includes/admin_access.css`.

**Comment by drbyte** [comment]
I'm confused.

It appears that you're adding 
`/admin/includes/admin_access.css` 
when we already have 
`/admin/includes/css/admin_access.css`

**Comment by scottcwilson** [comment]
Yep.  Cleaned up.

**Pull request merged**
