### PR TITLE
Admin: Add ellipses to indicate truncation of ezpages content in sidebar

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
👍

**Comment by scottcwilson** [comment]
argh sorry for the confusing branch name - this does NOT fix 1268.  I have a fix for that at home - will check in tomorrow.

**Comment by zcwilt** [comment]
@scottcwilson Given you haven't added a Fixes #issuenumber to the commit, it's not going to trigger a close for that issue.

**Comment by zcwilt** [comment]
@scottwilson in terms of what appears after the merge, Zen Cart git won't really remember the branch name, so I wouldn't worry

**Comment by scottcwilson** [comment]
Understood - I just realized the branch name might be confusing.

**Comment by zcwilt** [comment]
@scottcwilson I very rarely look at the branch name. Just the commit message.
While it's a good idea for your personal Todo, to have a descriptive branch name it's not something that is going to mess up merges :)

**Comment by drbyte** [comment]
Also FYI:   It's not necessary to put "Fixes #xxxx" in the first line of the commit.  I generally put it somewhere on line 2 or 3.
(It doesn't need to be in the title; I find that "words" describe what was "fixed" much better than an issue number. Adding "Fixes" or "Closes" later in the body takes care of closing related tickets.)

**Pull request merged**
