### PR TITLE
Shopping cart define

### PR DESCRIPTION
**Pull request by wiztechinc**

### CODE REVIEW

**Comment by scottcwilson** [comment]
Good job.  Note that your editor has introduced some whitespace changes, so you'll want to tighten that up.

**Comment by wiztechinc** [comment]
Yay! Dang white spaces!

**Comment by wiztechinc** [comment]
I took a look and don't see the white spaces when doing a compare. Can you be specific? I've definitely seen these issues before and if it's due to my default editor, then I need to use another.

**Comment by scottcwilson** [comment]
Your compare tool likely is configured to ignore whitespace changes.
Look at the Files Changed tab.  Look at includes/filenames.php for example.  Lines 32 and 63 should not be changed.

**Comment by drbyte** [comment]
I think the lines Scott pointed out were probably using a wrong line-ending already.

I've updated other files by changing tabs to spaces, to conform with standard.

**Comment by drbyte** [comment]
Thanks Delia!

**Comment by wiztechinc** [comment]
You are welcome and yes, that was the problem. Once I told beyond compare to show the whitespaces, I see what he was talking about. I feel like dancing...............
image

**Comment by lat9** [comment]
@wiztechinc, I'm having the same issue with Beyond Compare.  Where did you find that setting?

**Comment by wiztechinc** [comment]
Kinda funny as it turns out I haven't updated it in years. Still on version 3 but the latest build of that version. 

image

**Comment by lat9** [comment]
Thanks, Delia!

**Pull request merged**
