### PR TITLE
Declare TEXT_GV_REDEEM once only

### LINKED ISSUE #2432: admin, constant TEXT_GV_REDEEM repeated
declared in english.php and again in gv_name.php

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #2432

### CODE REVIEW

**Comment by zcwilt** [comment]
I may be missing something, but should this commit not include the removal of the define from other language files.

**Comment by scottcwilson** [comment]
This was the only one.

**Comment by zcwilt** [comment]
lol.  totally misread the commit.

**Comment by scottcwilson** [comment]
We *will* do more of these later, but this is just for one that was particularly noisy.

**Pull request merged**
