### PR TITLE
Fix: Cheapest shipping not selected when storepickup is the only method and has multiple prices

### LINKED ISSUE #6023: Cheapest shipping not selected when storepickup is the only method and has multiple prices
... as identified in [this](https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1397522#post1397522) Zen Cart forum posting.

### PR DESCRIPTION
**Pull request by drbyte**
Fixes #6023

### CODE REVIEW

**Comment by lat9** [comment]
Noting pickup locations for configuration:
```
Loc_A, 9.50;Loc_B, 2.50;Loc_C, 4.50;Loc_D, 7.50;Loc_E, 0.50
```

**Comment by lat9** [comment]
Noting that the OP on the Zen Cart forums (from which this PR was born) has indicated that the supplied solution corrects the reported issue.

**Comment by drbyte** [comment]
> Noting that the OP on the Zen Cart forums (from which this PR was born) has indicated that the supplied solution corrects the reported issue.

Did they send their fix to you via PM? 
Ref: https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1397633#post1397633

**Comment by lat9** [comment]
They did ... and I "refined" that.

**Comment by drbyte** [comment]
Okay. Will merge.

**Pull request merged**
