### PR TITLE
Illuminate support request and routing

### PR DESCRIPTION
**Pull request by zcwilt**

### CODE REVIEW

**Comment by zcwilt** [comment]
Support for Arr/String/Collections
Support for Illuminate\Request Illuminate\Routing Illuminate\View

There is no intention to switch to routing for Zen Cart web routes just yet.
The support here will allow some testing for the future, and the possiblity of building
out an API based on routing.

Also updated the config define loader to cast some groups to int
as was done before.

**Comment by scottcwilson** [comment]
Exciting stuff!  Thanks for doing this.

**Comment by zcwilt** [comment]
Hoping to have a very simple example of an api route soon.

**Comment by scottcwilson** [comment]
Use case?

**Pull request merged**
