### PR TITLE
find zone id from state where addressbook is broken

### PR DESCRIPTION
**Pull request by zcwilt**
Note from @scottcwilson - please note this is a confirmed bug found during the investigation of #6008.

### CODE REVIEW

**Comment by zcwilt** [comment]
Note: this seems to work where there shipping tax is not set to store.
needs more work to cover that

**Comment by zcwilt** [comment]
updated to fix shipping tax where zone id = 0 
Still needs a few more tests to cover tax basis = store

**Comment by dbltoe** [comment]
As stated on the forum, we do not use a dropdown for state in the registration form.
Also, there are no entry_zone_id entries that are 0 except where the country has no states.  Then, the 0 is as it should be, correct?

**Comment by zcwilt** [comment]
@dbltoe On A clean install of Zencart, if I create a customer account in store then it doesn't set the address book entry_zone_id, regardless of whether zones exist or not.

**Comment by zcwilt** [comment]
@dbltoe as per my post on the thread. Contact me directly at ian@zen-cart.com to see if I can help more directly with your problem

**Pull request closed without merging**
