### PR TITLE
remove spiffyCal from stats_products_viewed #4363

### PR DESCRIPTION
**Pull request by proseLA**
@swguy this removes spiffycal from this script.  personally i am a fan of having built in functions do all of the validations, so i pulled a lot of that stuff out.  i'm not seeing complaints on datepicker (on other admin scripts) and its error checking so i think we are good there; but some additional testing and another set of eyes is always good.

on another note, in my testing the split page class does not provide accurate results.  which messes up the pager in this script.

in my testing this bug was independent of my branch and should be easily reproduced on the v158 branch.  at least it is for me.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Please open a new issue for the split page class problem you are reporting so it can be tracked.  Thank you!

**Comment by proseLA** [comment]
> Please open a new issue for the split page class problem you are reporting so it can be tracked. Thank you!

i will.  but i'm pretty sure i remember bringing up this issue before... or commented on it...  unfortunately i can not find it.  but i will open a new issue.

**Comment by scottcwilson** [comment]
This looks good but can you set decent defaults so the page isn't blank when it loads?  Say CURRENT_YEAR-01-01 to CURRENT_DATE?

**Comment by scottcwilson** [comment]
Great!  Please squash these two commits.

**Pull request merged**
