### PR TITLE
Pre-check for attacks

### PR DESCRIPTION
**Pull request by scottcwilson**
Bad guys submitting emails like ð\'\'ð\"\" which cause needless logs.

### CODE REVIEW

**Comment by mc12345678** [comment]
Doesn't the inserted "bypass" significantly change the operation of this section of code?

Previously, it was possible that the email address could be assigned to a set of single quotes and if the form was being submitted for processing the inner area would have been executed. Such single quotes would fail the: `filter_var($email_address, FILTER_VALIDATE_EMAIL)` test and therefore the inner area would no longer be processed.

Now I don't pretend to fully understand why it was permissible to move forwards with an empty email address, but at the same time the reported issue is against something other than `empty` (Perhaps that is the solution?)
````php
if ((!$error || empty($email_address)) && …
````

**Comment by drbyte** [comment]
Upon first review I don't think this is in the right location in relation to overall flow.

Also wondered why the ZC function for email validation wasn't used here, for sake of consistency.

**Comment by scottcwilson** [comment]
I can change it to call zen_validate_email if you'll take the PR.  I just wanted a quick check to prevent the log.

**Comment by drbyte** [comment]
I think this needs more study. I'm not comfortable with it as it is now in terms of overall flow for where this validation test is being done.

**Comment by scottcwilson** [comment]
To be clear: I have no preference where this check is done; I just don't want to get a log file.

**Comment by drbyte** [comment]
I meant to ask earlier: what exactly is the message in the log?

**Comment by scottcwilson** [comment]
Can't repro in 1.5.8.  Could be the template in question was lacking the type hint that modern templates use.

**Comment by scottcwilson** [comment]
Updating the template changes document to remind people to check for this improvement.

**Pull request closed without merging**
