### PR TITLE
admin, manufacturers, add column title for ID to listing page

### PR DESCRIPTION
**Pull request by torvista**
TABLE_HEADING_ID is ripe for rationalisation to main language file in due course, I think.

### CODE REVIEW

**Comment by drbyte** [comment]
Why does the `id` column need a title?

**Comment by torvista** [comment]
I think it looks odd without a title, consistency with other pages, and takes up no more space.

**Comment by drbyte** [comment]
>  and takes up no more space.

Maybe.

But it does take up a bunch more space in language-translation burden.

That's why I intentionally excluded/removed the ID column from the page.

**Comment by torvista** [comment]
> But it does take up a bunch more space in language-translation burden.

ID?

I can put this in the main lang file and take it out of the others now.

**Pull request merged**
