### PR TITLE
shipping estimator template: non-functionality changes

### PR DESCRIPTION
**Pull request by torvista**
tr tags: IDE was unable to balance the tr tags as correct, this is easier to read.

### CODE REVIEW

**Comment by torvista** [comment]
Do I need to do something with this, PR the tr change separately? 
As that's the only thing that is not easily checked by eye?

**Review by brittainmark — COMMENTED** [review]
Looks good to me. I like the <tr> change looks logically correct and easier to understand.

**Comment by torvista** [comment]
I'll squash when requested.

**Comment by torvista** [comment]
**>Do I need to do something with this**...

**Pull request merged**
