### PR TITLE
Admin: remove cols/width from function textarea calls

### PR DESCRIPTION
**Pull request by torvista**
I've checked each of these, to ensure they make no different to the display, which is set by css.

### CODE REVIEW

**Comment by scottcwilson** [comment]
This was more changes than I expected.  I thought we were just going to fix the ones that said "100%".

**Comment by torvista** [comment]
On a search, there were mixtures of %, sizes, missing soft, when all were in fact size-fixed by the css, so it seemed more natural to make them all the same/remove the cols when they were doing nothing.

**Comment by scottcwilson** [comment]
I'd really rather not change things that don't have to change.  Adding changes means more diffs and more frustration for upgraders.  Please remove the files that didn't use "100%" as a width so we can make this a smaller change.

**Comment by torvista** [comment]
To clarify, you want the ones with 100% to have the parameter empty or 100?

**Comment by scottcwilson** [comment]
Either empty or zero will work as expected (be dropped) by your change in the last PR.

**Comment by scottcwilson** [comment]
TY

**Pull request merged**
