### PR TITLE
fix group by for new pager

### PR DESCRIPTION
**Pull request by proseLA**
reviews currently generates fatal error.  apparently i (and maybe @torvista) missed this file when working on the new pager.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Please give specifics about the fatal error.  Any special config?

Going to http://localhost:8888/gh_demo_158/admin/index.php?cmd=reviews works fine for me in PHP 7.4.

**Comment by proseLA** [comment]
nothing special.  v158 test data installed.

image

image

```
[22-Apr-2022 16:06:51 America/Los_Angeles] Request URI: /admin/index.php?cmd=reviews, IP address: 192.168.14.74
#1  trigger_error() called at [/var/www/zcdev/includes/classes/db/mysql/query_factory.php:665]
#2  queryFactory->show_error() called at [/var/www/zcdev/includes/classes/db/mysql/query_factory.php:632]
#3  queryFactory->set_error() called at [/var/www/zcdev/includes/classes/db/mysql/query_factory.php:273]
#4  queryFactory->Execute() called at [/var/www/zcdev/admin/includes/classes/split_page_results.php:205]
#5  splitPageResults->numberRows() called at [/var/www/zcdev/admin/includes/classes/split_page_results.php:116]
#6  splitPageResults->__construct() called at [/var/www/zcdev/admin/reviews.php:328]
#7  require(/var/www/zcdev/admin/reviews.php) called at [/var/www/zcdev/admin/index.php:11]
--> PHP Fatal error: 1055:'zc157.r.products_id' isn't in GROUP BY :: SELECT count(*) as total FROM (SELECT r.reviews_id, r.products_id, r.customers_name, r.reviews_rating, r.date_added, r.status, r.last_modified, r.reviews_read,                                              rd.languages_id, rd.reviews_text,                                              pd.products_name,                                              p.products_model, p.products_image,                                              length(rd.reviews_text) AS reviews_text_size,                                              (AVG(r.reviews_rating) / 5 * 100) AS average_rating                                       FROM reviews r                                       LEFT JOIN reviews_description rd ON rd.reviews_id = r.reviews_id                                       LEFT JOIN products_description pd ON pd.products_id = r.products_id                                         AND pd.language_id = 1                                       LEFT JOIN products p ON p.products_id = r.products_id                                       WHERE r.products_id = p.products_id                                                                              GROUP BY r.reviews_id, rd.languages_id                                        ORDER BY r.status, r.date_added DESC) countresults ==> (as called by) /var/www/zcdev/admin/includes/classes/split_page_results.php on line 205 <== in /var/www/zcdev/includes/classes/db/mysql/query_factory.php on line 665.
```

**Comment by torvista** [comment]
I can't replicate the problem...is the query reference to zc157 indicating some mixup, possibly due to the recent branch renaming?

**Comment by scottcwilson** [comment]
I have the same MySQL Mode and it works ok for me.  Something related to STRICT?

**Comment by proseLA** [comment]
i am in strict mode for sure.

**Comment by lat9** [comment]
What version of MySQL is in use, @proseLA?

**Comment by torvista** [comment]
It is indeed the sql_mode.
If it is configured the same with this:

> define('DB_MYSQL_MODE', 'ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION');

the error **does** manifest as reported.

**Comment by torvista** [comment]
Setting the sql_mode as indicated also throws up a similar error with attributes controller.

**Comment by scottcwilson** [comment]
@torvista would you please verify that this fix prevents the log?  Seems like it would do so.

**Comment by torvista** [comment]
Yes it does.

**Comment by scottcwilson** [comment]
thanks.

**Comment by proseLA** [comment]
> Setting the sql_mode as indicated also throws up a similar error with attributes controller.

@torvista could you tell me exactly how you got the attributes controller to generate that error?  i was playing with it earlier with no errors; but my experience with that script is minimal.

**Comment by torvista** [comment]
Doh. There is no error in the vanilla file.
My version had extra code in it copied from when this error existed previously and since there was no line number in the error I didn't notice.

**Pull request merged**
