### PR TITLE
PRODUCT_THROWS_200_WHEN_DISABLED check condition is backwards

### PR DESCRIPTION
**Pull request by scottcwilson**
Logic should be: 

```
IF throw_200 is true THEN
   IF disabled THEN 
       SET not found 
   FI
FI 
```

### CODE REVIEW

**Comment by scottcwilson** [comment]
This can be easily tested simply by setting a product to disabled and adding 

`define('PRODUCT_THROWS_200_WHEN_DISABLED',false);`

to the configure.php, and then attempting to load the product_info page for the disabled product.  

You will observe that it does not work until this fix is applied.

**Comment by drbyte** [comment]
ALERT: changing this is will break whatever people have already implemented from the forum discussions that inspired these changes in the first place. Need to locate those discussions and discern why they were satisfied with the current implementation if indeed it is wrong.

**Comment by drbyte** [comment]
Hmmm ... While the code was heavily discussed on github, I was fairly certain there was a forum thread specific to this feature, where we tested its implementation.
Maybe I was only dreaming.

**Comment by scottcwilson** [comment]
If you can document how to make the current logic work I'd be interested.  It sure seems backwards to me.   I was one of the people who suggested such a flag but I don't recall any specific implementation discussions.

**Comment by drbyte** [comment]
Given there's no forum implementation, and that there's a notifier `NOTIFY_PRODUCT_INFO_PRODUCT_STATUS_CHECK` for it which provides all the same power, and more, maybe it's best to just remove that boolean constant check.

**Comment by scottcwilson** [comment]
As I said in #3789 this seems storeowner unfriendly - can we just do a config setting?

**Comment by drbyte** [comment]
Closed by #4037

**Pull request closed without merging**
