### PR TITLE
[v156] Freshen Docs Styling

### PR DESCRIPTION
**Pull request by dakanji**
Misc Other Updates:
1. Update Zen Cart Website Protocol to https
2. Added placeholders for some v1.5.6 files to be finalised post release
3. Updated instructions dating from v1.3.x about renaming Admin folder and so on

### CODE REVIEW

**Comment by proseLA** [comment]
is it possible to move away from in-line css to 1 css file that gets imported for all of the instruction pages?

**Comment by dakanji** [comment]
This commit was supposed to do what I think you are suggesting ... Can you clarify?

**Comment by barco57** [comment]
well, that is the point of this pull request...
Though I find myself wondering why oxygen.css?
The admin is using bootstrap, the zc_install is using foundation, and now adding a third css framework for another part...

**Comment by dakanji** [comment]
Oxygen.css is just a name I gave the css file and is not a framework albeit it draws on a subset of Hydrogen css >> https://github.com/pimbrouwers/hydrogen ... hence the play on words as in breathe some oxygen into the old staid styling the docs have. 

Could just as well have called it docs.css or anything else.

**Comment by barco57** [comment]
ah, I thought it had something to do with http://oxygencss.com/

**Comment by dakanji** [comment]
Aha! I thought I was being original with the name. 

Well, if the changes are fine in principle to the devs, the name of the css file can be changed to a boring but unambiguous "docs.css" or similar.

**Comment by proseLA** [comment]
i'm sorry.  my error.  i could blame it on 4/20, but my comment was from 4/19....

i admit, i also looked up the oxygen css as well...  but my comment was clearly misinformed, as i must have been looking at the diff incorrectly.

**Comment by dakanji** [comment]
Changed the name of the css file to "zen.css"

**Comment by dakanji** [comment]
Got too messy

**Pull request closed without merging**
