### PR TITLE
Admin orders

### PR DESCRIPTION
**Pull request by torvista**
short array syntax, sizeof to count, remove infobox br

### CODE REVIEW

**Comment by scottcwilson** [comment]
Not certain changing existing code from `array()` to `[]` is a big win.

**Comment by torvista** [comment]
I have more stuff to add, this is a bit of clearing the decks.

**Comment by drbyte** [comment]
> I have more stuff to add, this is a bit of clearing the decks.

Please provide a list. I'm not a fan of "dumping grounds" tossing a ton of stuff into one PR.

**Comment by torvista** [comment]
..I have lots of changes, but on further examination, not much for general consumption.
I was going to do them as individual PRs after this, but possibly not worth it:
make search term sticky/pre-populated search field
set min/max limits on order id search

**Comment by drbyte** [comment]
> I was going to do them as individual PRs after this

I'm open to these ideas: Just want to understand the use-case: 

> make search term sticky/pre-populated search field

Is it to refine the search by adding to it or editing it because of a typo?
Or is it something more complex like needing to re-do the identical search even though the results displayed are based on that same search but the results are stale because of using the browser's "back" button? 

> set min/max limits on order id search

Is this to trap for typos when entering an id number? 
or do you mean to limit the number of results shown?

**Comment by torvista** [comment]
>Is it to refine the search by adding to it or editing it because of a typo?

To pre-load the search term for correction/modification: due to no/bad results from a mis-type.

>Is this to trap for typos when entering an id number?
To set min-max values on the id search field so you can only enter a valid order id number/in the range available.

**Comment by drbyte** [comment]
> > > set min/max limits on order id search

> > Is this to trap for typos when entering an id number?

> To set min-max values on the id search field so you can only enter a valid order id number/in the range available.

I'm still not sure "why" on this. Are you typing ultra-long order id numbers somehow? or negative numbers?

**Comment by torvista** [comment]
The idea was to block invalid numbers in the browser to avoid making a pointless search.
Can't remember why I did it. Like all mods, they all seem necessary at the time, but a few years later...one forgets.
But still, since it gives visual indication of the limits, with no code necessary (for the display), when the user miss-keys out of range.

**Comment by scottcwilson** [comment]
Can this be closed?

**Comment by torvista** [comment]
whatever, too busy

**Pull request closed without merging**
