### PR TITLE
Admin page registration - minor fixes

### PR DESCRIPTION
**Pull request by torvista**
and clarifications of the text

### CODE REVIEW

**Comment by scottcwilson** [comment]
This does not fix any bugs.  Suggest deferral to 1.5.8.

**Comment by proseLA** [comment]
i can not comment on whether this addresses any bugs; however, the changes for the error messages i think are significant and worthy.  the error `The language key entered has not been defined. Please check that it has been spelt correctly.` requires someone to actually look at code and figure out what the error is.  there is nothing on the page that says language key.   the requirements to get something onto a menu are difficult enough; the error messages should be clear and concise as to where the error is.

**Comment by drbyte** [comment]
Argh. I'd intended to remove this entire thing because it all needs to be in code anyway. 
If one is adding a menu item there are multiple other dependencies that have to be in code. 

There's no point having this screen. There are already functions to create/remove entries. Those should be used instead.

Or, at least that's my take on it at this time.

**Comment by proseLA** [comment]
> Argh. I'd intended to remove this entire thing because it all needs to be in code anyway.
> If one is adding a menu item there are multiple other dependencies that have to be in code.
> 
> There's no point having this screen. There are already functions to create/remove entries. Those should be used instead.
> 
> Or, at least that's my take on it at this time.

oh, i disagree!  make this page better (i will do it!) and leave it in!

**Comment by drbyte** [comment]
The only time I've ever used this screen was to re-create a plugin-specific entry that had been manually deleted. It would have been more efficient to do it via the plugin's own install process.

**Comment by drbyte** [comment]
> oh, i disagree! make this page better (i will do it!) and leave it in!

Why?

**Comment by proseLA** [comment]
so confusing.  this page could be so much better.  what i was working on:

slightly off topic (but worthy for change in v1.5.8), why do we require a page key?  there is a need for an unique index; but is this not something that the code should maintain as opposed to the admin? in addition, i think we can make this process easier with better labeling, ie `Page Name` could be `Menu Entry`.  `Page Name` v `Page Filename` may make sense to core people, but when long time contributors need documentation for adding a menu entry, perhaps the process can be improved.

**Comment by proseLA** [comment]
`BOX_` this and `FILENAME_` that?  i get it.  but create a tool, you want it on a menu, what do you want the menu item to say, and where is the tool?  menu entries, for those that want to create them, should not be that hard.  i still struggle with it.

**Comment by drbyte** [comment]
> menu entries, for those that want to create them

Such as?  (ie: other than for anything related to plugins, which have PHP code to install/remove)

**Comment by drbyte** [comment]
The built-in functions `zen_register_admin_page()` and `zen_deregister_admin_pages()` can be called via a plugin's code to add/remove the menu items associated with the dependent defines that the plugin provides.

**Comment by proseLA** [comment]
[
Screenshot from 2020-06-03 08-23-32
]
i have taken to adding items into the header bar.  not every modification that a developer does make is to the ZC plugins.

**Comment by proseLA** [comment]
when cindy is adding items to the documentation, it says something to me:
https://github.com/zencart/documentation/commits/master/content/dev/code/creating_menu.md

i just know i have struggled with this in the past, and this page could be easier to understand for those of us that after we have put the work into a new tool, now have to review everything to get a menu item available.

besides, i don't want to change my documentation.  
https://github.com/proseLA/inventory/blob/e3f608ccb63299982a027814d9b7bbe82908f9c4/docs/index.html#L116-L125
:smile:

**Comment by drbyte** [comment]
> besides, i don't want to change my documentation.

Including one additional PHP file to do the page registration in code would mean you could remove those 10 lines of documentation. And make installation even simpler for the end-user.

**Comment by drbyte** [comment]
There could be value in replacing this page with an admin menu editor that allows changing sort orders and relocating menu items. 
Deletes are dangerous because most storeowners will ignorantly delete an entry when all they really wanted was to prevent other users from using certain entries ... and they should use a Profile for that, not a total delete. Support will be a nightmare if they start deleting things willy-nilly.
Adding new ones could be offered, but care needs to be taken with identifying the page key name so that it has both semantic meaning and can be controlled via Profiles. And not clash with plugins by the same name. And manage the case where someone thinks it's a good idea to add a duplicate (maybe under another submenu) but then wonders why Profiles are broken.
Oh, and still keep it multi-language-friendly.
And, again, ensure that Profile controls still work, even for non-displayed controls which govern subsections/subpages of some pages.
It would really be not just a "menu editor" but more of an enhanced/combined profiles+menus editor where every entry is linked to corresponding profiles with every edit. Both (profile control and menu entries) need to be kept in mind all the way through.

**Comment by proseLA** [comment]
deletes could be handled via changing the display flag to N.  i rarely delete anything.  one loses an audit trail.

**Comment by barco57** [comment]
"There could be value in replacing this page with an admin menu editor that allows changing sort orders and relocating menu items." - I read that and started to hyperventilate as I spend all day in and out of people's admins. I can only imagine how much stuff I would break throwing items around my office trying to find where store owners decided menu items should be in their mind... Then I read the rest of the post and thought Ok attached to admins profiles...wait, does that mean admin menu layout tied to profiles like Superuser, order processing, etc? so I would still be tied to the whims of the store owner as a superuser, kill me now. How about the superuser has a locked menu layout or even better when a new admin user is created a profile is picked at that time and is cloned and attached to that particular user. As it is I get annoyed when I go to the tools menu in 157 as that menu is ignoring sort orders and showing alphabetically instead. Thinking about support when someone asks how to do something, they have forgotten how to do, and I tell them the path to the menu item (admin>configuration>something) but they have moved things around in the admin, oh the support nightmare I see coming or am I reading too much into it?

**Comment by drbyte** [comment]
> "There could be value in replacing this page with an admin menu editor that allows changing sort orders and relocating menu items." - I read that and started to hyperventilate as I spend all day in and out of people's admins. I can only imagine how much stuff I would break throwing items around my office trying to find where store owners decided menu items should be in their mind... Then I read the rest of the post and thought Ok attached to admins profiles...wait, does that mean admin menu layout tied to profiles like Superuser, order processing, etc? so I would still be tied to the whims of the store owner as a superuser, kill me now. How about the superuser has a locked menu layout or even better when a new admin user is created a profile is picked at that time and is cloned and attached to that particular user. As it is I get annoyed when I go to the tools menu in 157 as that menu is ignoring sort orders and showing alphabetically instead. Thinking about support when someone asks how to do something, they have forgotten how to do, and I tell them the path to the menu item (admin>configuration>something) but they have moved things around in the admin, oh the support nightmare I see coming or am I reading too much into it?

Yup: with great power comes great responsibility. Giving the storeowner too much control makes it near impossible to effectively provide support for those who have (unwittingly or intentionally) broken things.

Usually the solution to that is to provide semi-strict opinionated restrictions (ie: not provide the flexibility in the first place)

**Comment by torvista** [comment]
So what does closed mean? I delete my PR?

**Comment by scottcwilson** [comment]
Look at the label.  "[Status] on hold" means they will move it back to open once the release is done.  They're trying to clear the deck so that only critical changes are shown.

**Comment by scottcwilson** [comment]
> As it is I get annoyed when I go to the tools menu in 157 as that menu is ignoring sort orders and showing alphabetically instead. 

This can be disabled.   In admin/includes/languages/english.php set MENU_CATEGORIES_TO_SORT_BY_NAME to ''.

**Comment by drbyte** [comment]
Leaving this on hold.

**Comment by torvista** [comment]
This page is slated for removal...I can delete this branch/PR?

**Comment by torvista** [comment]
I keep going to delete this branch but then I see the page still exists, the changes are still valid and I hate wasting work.
I can update this for ZC158 or it this really going to be removed?

**Comment by torvista** [comment]
never resolved...

**Pull request closed without merging**
