### PR TITLE
select does not allow rel element

### PR DESCRIPTION
**Pull request by proseLA**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel

image

### CODE REVIEW

**Comment by scottcwilson** [comment]
Seems like a good fix.  No visible change in testing?

**Comment by Zen4All** [comment]
Did you notice your label tag is missing a closing bracket? I see `</label` in your picture instead of `</label>`.

**Comment by proseLA** [comment]
> Did you notice your label tag is missing a closing bracket? I see `</label` in your picture instead of `</label>`.

hi erik,
feel free to bring it up here:
https://www.freeformatter.com/html-validator.html
the input file had all of the necessary closing brackets on every `label` tag.  and the validator did not complain about missing closing brackets.

i would encourage reading what the `rel` attribute is used for and what its potential values are.  `dropdown` is NOT a potential value. and it is not relevant to a `select` tag:

The rel attribute is relevant to the `link`, `a`, `area`, and `form` elements, but some values only relevant to a subset of those elements. Like all HTML keyword attribute values, these values are case-insensitive.

**Comment by Zen4All** [comment]
I was just curious it was not giving any false positives. And after reading the documentation there is no doubt at all.

FYI, the `rel` attribute was added in Zen Cart version 1.3.0

**Comment by scottcwilson** [comment]
I too checked for bad label closes and didn't find any.
Thanks for the fix!

**Pull request merged**
