### PR TITLE
Add more notifiers to shopping_cart for after-add/update

### PR DESCRIPTION
**Pull request by zenexpert**
Add notifiers for successful add to cart in case one wants to hook additional actions based on product(s) added to cart

### CODE REVIEW

**Comment by drbyte** [comment]
Interesting idea.

Do you have some scenarios in mind?

I'm also wondering why `NOTIFIER_CART_ADD_CART_END` or `NOTIFIER_CART_ADD_CART_START` doesn't suffice ... other than specifically wanting to fire only after "all" the adds are done when a group has been added.

**Comment by zenexpert** [comment]
I'm actually already using `NOTIFIER_CART_ADD_CART_END` but you read my mind - if you're adding multiple products from ie product_listing page, it might fire too early if condition is met before adding all products. 

As for scenarios - I'll PM you a link so you can see the idea and how it's being used, although I must admit it IS quite a specific setup... But in general, the idea would be to "force" a product (or any other page for that matter) if a certain product is added to cart.

**Comment by drbyte** [comment]
I wonder if `actionAddProduct()` and `actionUpdateProduct()` should have similar hooks?  In the case of `update`, perhaps handling conditions that need to undo the things you added/forced via those others?  I suppose existing other notifiers might cover the update action already. But maybe actionAddProduct might need its own because without it it'd have to use the NOTIFER_CART_ADD_CART_END already discussed

**Comment by zenexpert** [comment]
LOL, Doc, I need about 2 gallons of coffee and about 3 lifetimes to come up with a reply to THAT. The way I'm using it is reeeeeaaaaaly simplistic and I can't even imagine the scenarios you're probably already considering.

I'm guessing if you need to undo, then `update` could get tricky because of the `remove` when you remove multiple items from cart at once (checkboxes), but TBH, I wasn't really thinking that far...

**Comment by drbyte** [comment]
No worries.
I've added the others I was thinking of.
And did a bit of renaming.

**Comment by proseLA** [comment]
https://github.com/zencart/zencart/commit/b4764716724e6a441cb6b82c61084644257427e9#commitcomment-51775540

sorry, i'm not sure the proper place to post this....  are the `$_POST` vars necessary?

**Pull request merged**
