### PR TITLE
zc158: Consolidating jscript_addr_pulldowns

### LINKED ISSUE #4488: Consolidate functions in jscript_addr_pulldowns.php
At least some of these files are exact dups.  We should consolidate this code to a single place and reuse it so fixes don't have to be done multiple times. 

includes/modules/pages/checkout_payment_address/jscript_addr_pulldowns.php
includes/modules/pages/create_account/jscript_addr_pulldowns.php
includes/modules/pages/popup_shipping_estimator/jscript_addr_pulldowns.php
includes/modules/pages/checkout_shipping_address/jscript_addr_pulldowns.php
includes/modules/pages/login/jscript_addr_pulldowns.php
includes/modules/pages/address_book_process/jscript_addr_pulldowns.php

### PR DESCRIPTION
**Pull request by lat9**
Fixes #4488 for zc158:
- Moving the common script file to the template_default's `jscript` sub-directory
- Updating the shipping-estimator's template to acknowledge the `ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN` setting.
- Updating all in-core pages' use to simply load the common script file.
- Removing the onload element for those pages that references `update_zone`; that initialization is now provided by the common script file.

### CODE REVIEW

**Comment by torvista** [comment]
A very welcome effort as this is something I did long ago. I have a lot of custom JS associated with these instances so doubt I'll be able to implement/test soon. Just commenting, rather than appearing to ignore it!
Sooner it is in the core the better, for further enhancement, as commented elsewhere.

**Comment by lat9** [comment]
Noting that this (and possibly other changes) has also corrected the behavior identified in #4191.

**Comment by lat9** [comment]
Any ideas as to how those conflicts magically appeared?

**Comment by zcwilt** [comment]
probably from here https://github.com/zencart/zencart/commit/1d7e25823458231d5b0c1a8762dd3f93034ad7ab

**Comment by lat9** [comment]
> probably from here [1d7e258](https://github.com/zencart/zencart/commit/1d7e25823458231d5b0c1a8762dd3f93034ad7ab)

Thanks, @zcwilt!

**Pull request merged**
