### PR TITLE
Make Admin category/products and orders table rows clickable again

### LINKED ISSUE #3304: Bug admin, orders. Click on order listing does not update infobox
as per subject.

### PR DESCRIPTION
**Pull request by drbyte**
Fixes #3304

This uses the on-page action ideas offered by @lat9 in #3304, with some variations to use named classes for excluded columns.

Closes #3377 
Closes #3378

### CODE REVIEW

**Comment by scottcwilson** [comment]
If approved, could we have the same logic on the products list in admin > catalog > categories/products?

**Comment by scottcwilson** [comment]
Tested. Groovy.

**Comment by drbyte** [comment]
added category/product listing

**Comment by torvista** [comment]
Well, I've been trying to find why the html validator is complaining about an unclosed attribute ", but only when there is more than one product in the order. Something to do with the hr and br, but not of importance.

Then...takes deep breath...I realised I won't be using this popup at all, as it is.
It adds a column/wastes space, it takes a click to show it, a click to close it, the closing click will be on another line causing an unwanted refresh of the infobox and it is enormous (optional I know).



It the risk of repeating myself, I did similar but as popup on hover on the price.
No space wasted, all the info instantly, no obscuring of other useful info,  and no jumping through hoops to make it clickable. Obviously I have never formatted it much.
Compare how much easier this is to read, and how many orders it does not obscure.

mv

(Size is an issue I have with bootstrap in general. It is infantile for customers, but not appropriate for an admin interface, far too much space wasted. I use a css file to squash it all as much as possible.)

**Comment by scottcwilson** [comment]
@torvista The popup is not related to this issue.  Can you move your complaint to a new issue?

**Comment by torvista** [comment]
I understood that the row has become not-clickable due to the additional of this popop, so that appears relevant to me.

**Comment by scottcwilson** [comment]
Chris has been yanking out this functionality because he feels it's ugly HTML.  See https://github.com/zencart/zencart/issues/3304#issuecomment-621409122

That's why it was removed from the categories/products listing in 1.5.6.   

Your concern is valid, but it's separate, so it would help if you moved it from a PR comment to a new issue.

**Pull request merged**
