### PR TITLE
v158: Correcting redirect back to checkout_shipping when cart content…

### LINKED ISSUE #5292: Incorrect Checkout Flow Using PayPal Express Checkout
**Describe the bug**
If I put an item in the cart then click express checkout. I am taken to the paypal page.
I complete the paypal page, and I am returned to the checkout_payment.
If I complete the checkout_paymant page I am then sent to the checkout_shipping page.
The process then follows the normal route through checkout_payment then checkout_confirmation etc.

**Version**
Zen Cart version: 1.5.8

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Put item in cart without loging in.
2. Click on paypal express checkout.
3. login to paypal and pay for item
4. On return you are in the in the checkout_payment page with all the shipping etc calculated.
5. Click continue. You are sent to the checkout_shipping page.

**Expected behavior**
At step 5 you should be sent to the checkout_confirmation page.

### PR DESCRIPTION
**Pull request by lat9**
…s unchanged

Fixes #5292

Supercedes PR #5293

### CODE REVIEW

**Review by brittainmark — APPROVED** [review]
I don't know why 
```php
$zc_check_basket_before !== $zc_check_basket_after
```
```php
$zc_check_basket_before === $zc_check_basket_after
```
Are returning` false` when both are 1.

As I would rather see === used, I will change class  shopping_cart to return ->count_contents() cast to int

**Comment by lat9** [comment]
@brittainmark, please re-review.  I've added some commentary and changed the comparisons based on the fact that the `count_contents` actually sums the in-cart products' quantities ... which are of type `float` instead of `int`.

**Review by brittainmark — APPROVED** [review]
Yes works a treat.  Sorry I missed cartcount being float.

**Comment by brittainmark** [comment]
@lat9 will you make the php8.2 definition changes?

**Comment by lat9** [comment]
@brittainmark, I've made the update to define the class variables for PHP 8.2.  That also resulted in some unused variables being removed and some assignments modified so that the commentary identifying the variable 'type' was accurate.

**Pull request merged**
