### PR TITLE
156: remove extra enter

### PR DESCRIPTION
**Pull request by Zen4All**
This change is [Reviewable](https://reviewable.io/reviews/zencart/zencart/2200)

### CODE REVIEW

**Comment by drbyte** [comment]
In this case that linebreak was intentional.

**Comment by Zen4All** [comment]
Why?

**Comment by drbyte** [comment]
> Why?

To make the output html more readable. 
I suppose it could have been done with a bunch more code that wraps \n in double quotes or PHP_EOL constant etc. Line break was simpler.

**Comment by Zen4All** [comment]
Okay, that's clear. thanks. Maybe we should add a comment in the code to alert others the break is intentional?

**Pull request closed without merging**
