### PR TITLE
admin, category_product_listing, action 'setflag": remove ambiguity

### PR DESCRIPTION
**Pull request by torvista**
I got an error" Undefined array key "flag" for this line. Could not replicate it but I think it needs refactoring so the isset gets parsed first.

### CODE REVIEW

**Comment by proseLA** [comment]
pretty easy to replicate:
```
[31-Aug-2021 07:14:34 America/Los_Angeles] Request URI: /admin/index.php?cmd=category_product_listing&action=setflag&pID=1&cPath=1_4&page=1, IP address: 192.168.14.74
#1  require(/var/www/zcdev/admin/category_product_listing.php) called at [/var/www/zcdev/admin/index.php:11]
--> PHP Notice: Undefined index: flag in /var/www/zcdev/admin/category_product_listing.php on line 102.
```
@torvista this is NOT a refactor.  it is a bug.  refactoring does not change logic.

**Comment by torvista** [comment]
> pretty easy to replicate:

How exactly?  I knew it was with enabling, but could not trigger it myself.

**Comment by proseLA** [comment]
> > pretty easy to replicate:
> 
> How exactly? I knew it was with enabling, but could not trigger it myself.

i just used the developer tools to edit the html and remove the flag and then posted the form.

not sure how you got there; but i agree that the logic is wrong.

**Comment by mc12345678** [comment]
Might happen if admin has timed out (also ***assuming*** that keep alive "didn't work") and then product's status was clicked. At that point, the `$_POST` is lost, although the `$_GET` will remain on the link, login is attempted, once complete the `setflag` action is executed but because of left side and (`&&`) happening before evaluating the right side of the or (`||`), the left says no, the right says oops.

**Pull request merged**
