### PR TITLE
Add notifier for category image

### PR DESCRIPTION
**Pull request by scottcwilson**
Having a notifier would make the integration of a plugin like Automatic Category Images possible with no core file changes. 

https://www.zen-cart.com/downloads.php?do=file&id=1977

### CODE REVIEW

**Review by proseLA — CHANGES_REQUESTED** [review]
why don't you just add 1 line for the notifier, and move your conditionals to your observer?

ie:
```
$zco_notifier->notify('NOTIFY_CATEGORY_ROW_EMPTY_IMAGE', $categories, $categories);
```
this can be done either before or after the assignment of the `pixel_trans.gif`.

i think doing it this way provides more flexibility for others to use the observer as they see fit, as opposed to just your specific use scenario.

**Comment by scottcwilson** [comment]
There's no need to call the observer if the image is properly set.  And there's no sense setting the image to pixel_trans.gif if the observer has changed the value.

**Comment by proseLA** [comment]
- you are wrong.
- adding your conditional in the core code as opposed to in your observer only pollutes the core code.
- just because **you** can not see the need does not make it so.

> And there's no sense setting the image to pixel_trans.gif if the observer has changed the value.

who said that?  not me....

**Comment by scottcwilson** [comment]
I may not be understanding what you are suggesting.  The notifier is called `NOTIFY_CATEGORY_ROW_EMPTY_IMAGE` and I add it after a conditional that checks that the image is in fact empty.  What would you change about that?

**Comment by proseLA** [comment]
this is a new notifier.  so change the notifier name.  i think this code allows for more flexibility:
```
        $zco_notifier->notify('NOTIFY_CATEGORY_ROW_IMAGE', $categories->fields['categories_id'], $categories->fields['categories_image']); 
        if (empty($categories->fields['categories_image'])) {
           $categories->fields['categories_image'] = 'pixel_trans.gif';
        }
```
inside of your observer you can then do the 2nd conditional to test if it is empty, and change accordingly.

i just do not see the need to test for something prior to setting off an observer event.

i think if we are adding more observes (of which i am a fan), they should be as flexible as possible for others to use.

**Pull request merged**
