### PR TITLE
v158: Correcting PHP Deprecate/Warning logs issued during email-addre…

### LINKED ISSUE #4891: PHP 8.0+: Configuration validation warnings and deprecations
The majority of the issues previously identified by @mc12345678 in this (https://github.com/zencart/zencart/pull/4407) PR are still valid, even with the changes currently merged for this PR (https://github.com/zencart/zencart/pull/4881) and the corrections provided by this (https://github.com/zencart/zencart/pull/4890) one.

I'm still seeing this PHP Warning:
```
[19-Jun-2022 07:29:03 America/New_York] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=configuration&gID=12&cID=293&action=save, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\functions\configuration_checks.php(53): filter_var()
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\configuration.php(22): zen_validate_configuration_entry()
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
--> PHP Warning: configurationValidation::sanitizeEmailNullOK(): Argument #1 ($val) must be passed by reference, value given in C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\functions\configuration_checks.php on line 53.
```
and this PHP deprecation:
```
[19-Jun-2022 07:29:03 America/New_York] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=configuration&gID=12&cID=293&action=save, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\classes\configurationValidation.php(58): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\classes\configurationValidation.php(24): configurationValidation::sanitizeEmail()
#2 [internal function]: configurationValidation::sanitizeEmailNullOK()
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\functions\configuration_checks.php(53): filter_var()
#4 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\configuration.php(22): zen_validate_configuration_entry()
#5 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\classes\configurationValidation.php on line 58.
```

The warning is, I believe, due to the way that the base PHP `filter_var` function deals with the FILTER_CALLBACK handling.  I'll be re-reviewing @mc12345678's changes in the referenced PR as well as the expected behavior in the call-chain from `configuration.php` to `zen_validate_configuration_entry` to see how the behavior can remain the same without passing the values by reference.

### PR DESCRIPTION
**Pull request by lat9**
…ss configuration checks

I couldn't help myself for the refactoring of the `configuration_checks.php` function file.  Changes also made for the install/upgrade paths for `zc_install`.

Fixes #4891.

### CODE REVIEW

**Comment by scottcwilson** [comment]
I'm not sure the contact us email list should ever be empty.

**Comment by lat9** [comment]
> I'm not sure the contact us email list should ever be empty.

Er, that's its default value.  If a site doesn't have a contact-us list (like mine does), then the contact-us email just goes to the store owner.

**Comment by dbltoe** [comment]
I am seeing a problem in the contact_us email selection in Chrome but, will do a separate post on it.

Brief synopsis.  Landing focus is always Full Name even if there are Send Email To: options which causes users to miss options in the drop-down.

Its (drop-down) being propagated from the gitgo means the required will never fail.

**Comment by lat9** [comment]
> I am seeing a problem in the contact_us email selection in Chrome but, will do a separate post on it.
> 
> Brief synopsis. Landing focus is always Full Name even if there are Send Email To: options which causes users to miss options in the drop-down.
> 
> Its (drop-down) being propagated from the gitgo means the required will never fail.

Since this PR is all about the `configuration` of those settings, any storefront (mis-)use should, as you noted, be identified in a separate issue.

**Pull request merged**
