### PR TITLE
Fix date check where spiffyCal is used

### PR DESCRIPTION
**Pull request by scottcwilson**
Date check not correctly done in specials.  (Same bug exists in other places; I can fix if you accept this.)

### CODE REVIEW

**Comment by scottcwilson** [comment]
Fixes #1970 plus other bugs.
To test: use an invalid date (13/25/2018) in a special start or end date.  Without this fix it will produce a debug log and white page.

**Comment by scottcwilson** [comment]
Other admin functions which likely have this same problem:
./banner_manager.php
./coupon_admin.php
./featured.php
./products_price_manager.php
./salemaker.php

**Comment by drbyte** [comment]
The proposed fix looks good. Go ahead with the additional pages.

**Comment by scottcwilson** [comment]
OK I did all of them except products price manager.  Please merge this and create a new ticket for PPM and I'll do that next week. It's more complicated.

**Pull request merged**
