### PR TITLE
Ensure MIN  and MAX values from groups 2 and 3 are integer

### PR DESCRIPTION
**Pull request by scottcwilson**
Blocks script injection into fields used in Javascript validation.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Recommended for backport to 1.5.6c.

**Comment by mc12345678** [comment]
If this is to become a thing, then would suggest (at some point) using/populating the `val_function` for these constants to have them be integers as well possibly by the validation filter `FILTER_VALIDATE_INT`.

**Comment by scottcwilson** [comment]
I like that idea as a future enhancement, but this specific PR is an "anti-bad-guy" change. They're not using the admin panel - they're modifying the db directly.

**Comment by wiztechinc** [comment]
The fix is reasonable. I would like to know how in the world this is happening to begin with. That to me is the larger issue.

**Pull request merged**
